package com.fasterxml.jackson.core.sym;

import androidx.lifecycle.LifecycleKtExternalSyntheticBackportWithForwarding0;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.util.InternCache;
import java.util.Arrays;
import java.util.BitSet;
import java.util.concurrent.atomic.AtomicReference;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class CharsToNameCanonicalizer {
    private Bucket[] _buckets;
    private boolean _canonicalize;
    private final int _flags;
    private boolean _hashShared;
    private int _indexMask;
    private int _longestCollisionList;
    private BitSet _overflows;
    private final CharsToNameCanonicalizer _parent;
    private final int _seed;
    private int _size;
    private int _sizeThreshold;
    private String[] _symbols;
    private final AtomicReference<TableInfo> _tableInfo;

    private static int _thresholdSize(final int i2) {
        return i2 - (i2 >> 2);
    }

    private CharsToNameCanonicalizer(final int i2) {
        _parent = null;
        _seed = i2;
        _canonicalize = true;
        _flags = -1;
        _hashShared = false;
        _longestCollisionList = 0;
        _tableInfo = new AtomicReference<>(TableInfo.createInitial(64));
    }

    private CharsToNameCanonicalizer(final CharsToNameCanonicalizer charsToNameCanonicalizer, final int i2, final int i3, final TableInfo tableInfo) {
        _parent = charsToNameCanonicalizer;
        _seed = i3;
        _tableInfo = null;
        _flags = i2;
        _canonicalize = JsonFactory.Feature.CANONICALIZE_FIELD_NAMES.enabledIn(i2);
        final String[] strArr = tableInfo.symbols;
        _symbols = strArr;
        _buckets = tableInfo.buckets;
        _size = tableInfo.size;
        _longestCollisionList = tableInfo.longestCollisionList;
        final int length = strArr.length;
        _sizeThreshold = CharsToNameCanonicalizer._thresholdSize(length);
        _indexMask = length - 1;
        _hashShared = true;
    }

    public static CharsToNameCanonicalizer createRoot() {
        final long jCurrentTimeMillis = System.currentTimeMillis();
        return CharsToNameCanonicalizer.createRoot((((int) jCurrentTimeMillis) + ((int) (jCurrentTimeMillis >>> 32))) | 1);
    }

    private static CharsToNameCanonicalizer createRoot(final int i2) {
        return new CharsToNameCanonicalizer(i2);
    }

    public CharsToNameCanonicalizer makeChild(final int i2) {
        return new CharsToNameCanonicalizer(this, i2, _seed, _tableInfo.get());
    }

    public void release() {
        final CharsToNameCanonicalizer charsToNameCanonicalizer;
        if (this.maybeDirty() && null != (charsToNameCanonicalizer = this._parent) && _canonicalize) {
            charsToNameCanonicalizer.mergeChild(new TableInfo(this));
            _hashShared = true;
        }
    }

    private void mergeChild(TableInfo tableInfo) {
        final int i2 = tableInfo.size;
        final TableInfo tableInfo2 = _tableInfo.get();
        if (i2 == tableInfo2.size) {
            return;
        }
        if (12000 < i2) {
            tableInfo = TableInfo.createInitial(64);
        }
        LifecycleKtExternalSyntheticBackportWithForwarding0.m212m(_tableInfo, tableInfo2, tableInfo);
    }

    public boolean maybeDirty() {
        return !_hashShared;
    }

    public int hashSeed() {
        return _seed;
    }

    public String findSymbol(final char[] cArr, final int i2, final int i3, final int i4) {
        if (1 > i3) {
            return "";
        }
        if (!_canonicalize) {
            return new String(cArr, i2, i3);
        }
        final int i_hashToIndex = this._hashToIndex(i4);
        final String str = _symbols[i_hashToIndex];
        if (null != str) {
            if (str.length() == i3) {
                int i5 = 0;
                while (str.charAt(i5) == cArr[i2 + i5]) {
                    i5++;
                    if (i5 == i3) {
                        return str;
                    }
                }
            }
            final Bucket bucket = _buckets[i_hashToIndex >> 1];
            if (null != bucket) {
                final String strHas = bucket.has(cArr, i2, i3);
                if (null != strHas) {
                    return strHas;
                }
                final String str_findSymbol2 = this._findSymbol2(cArr, i2, i3, bucket.next);
                if (null != str_findSymbol2) {
                    return str_findSymbol2;
                }
            }
        }
        return this._addSymbol(cArr, i2, i3, i4, i_hashToIndex);
    }

    private String _findSymbol2(final char[] cArr, final int i2, final int i3, Bucket bucket) {
        while (null != bucket) {
            final String strHas = bucket.has(cArr, i2, i3);
            if (null != strHas) {
                return strHas;
            }
            bucket = bucket.next;
        }
        return null;
    }

    private String _addSymbol(final char[] cArr, final int i2, final int i3, final int i4, int i5) {
        if (_hashShared) {
            this.copyArrays();
            _hashShared = false;
        } else if (_size >= _sizeThreshold) {
            this.rehash();
            i5 = this._hashToIndex(this.calcHash(cArr, i2, i3));
        }
        String str = new String(cArr, i2, i3);
        if (JsonFactory.Feature.INTERN_FIELD_NAMES.enabledIn(_flags)) {
            str = InternCache.instance.intern(str);
        }
        _size++;
        final String[] strArr = _symbols;
        if (null == strArr[i5]) {
            strArr[i5] = str;
        } else {
            final int i6 = i5 >> 1;
            final Bucket bucket = new Bucket(str, _buckets[i6]);
            final int i7 = bucket.length;
            if (100 < i7) {
                this._handleSpillOverflow(i6, bucket, i5);
            } else {
                _buckets[i6] = bucket;
                _longestCollisionList = Math.max(i7, _longestCollisionList);
            }
        }
        return str;
    }

    private void _handleSpillOverflow(final int i2, final Bucket bucket, final int i3) {
        final BitSet bitSet = _overflows;
        if (null == bitSet) {
            final BitSet bitSet2 = new BitSet();
            _overflows = bitSet2;
            bitSet2.set(i2);
        } else if (bitSet.get(i2)) {
            if (JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW.enabledIn(_flags)) {
                this.reportTooManyCollisions(100);
            }
            _canonicalize = false;
        } else {
            _overflows.set(i2);
        }
        _symbols[i3] = bucket.symbol;
        _buckets[i2] = null;
        _size -= bucket.length;
        _longestCollisionList = -1;
    }

    public int _hashToIndex(final int i2) {
        final int i3 = i2 + (i2 >>> 15);
        final int i4 = i3 ^ (i3 << 7);
        return (i4 + (i4 >>> 3)) & _indexMask;
    }

    public int calcHash(final char[] cArr, int i2, final int i3) {
        int i4 = _seed;
        final int i5 = i3 + i2;
        while (i2 < i5) {
            i4 = (i4 * 33) + cArr[i2];
            i2++;
        }
        if (0 == i4) {
            return 1;
        }
        return i4;
    }

    public int calcHash(final String str) {
        final int length = str.length();
        int iCharAt = _seed;
        for (int i2 = 0; i2 < length; i2++) {
            iCharAt = (iCharAt * 33) + str.charAt(i2);
        }
        if (0 == iCharAt) {
            return 1;
        }
        return iCharAt;
    }

    private void copyArrays() {
        final String[] strArr = _symbols;
        _symbols = Arrays.copyOf(strArr, strArr.length);
        final Bucket[] bucketArr = _buckets;
        _buckets = Arrays.copyOf(bucketArr, bucketArr.length);
    }

    private void rehash() {
        final String[] strArr = _symbols;
        final int length = strArr.length;
        final int i2 = length + length;
        if (65536 < i2) {
            _size = 0;
            _canonicalize = false;
            _symbols = new String[64];
            _buckets = new Bucket[32];
            _indexMask = 63;
            _hashShared = false;
            return;
        }
        final Bucket[] bucketArr = _buckets;
        _symbols = new String[i2];
        _buckets = new Bucket[i2 >> 1];
        _indexMask = i2 - 1;
        _sizeThreshold = CharsToNameCanonicalizer._thresholdSize(i2);
        int i3 = 0;
        int iMax = 0;
        for (final String str : strArr) {
            if (null != str) {
                i3++;
                final int i_hashToIndex = this._hashToIndex(this.calcHash(str));
                final String[] strArr2 = _symbols;
                if (null == strArr2[i_hashToIndex]) {
                    strArr2[i_hashToIndex] = str;
                } else {
                    final int i4 = i_hashToIndex >> 1;
                    final Bucket bucket = new Bucket(str, _buckets[i4]);
                    _buckets[i4] = bucket;
                    iMax = Math.max(iMax, bucket.length);
                }
            }
        }
        final int i5 = length >> 1;
        for (int i6 = 0; i6 < i5; i6++) {
            for (Bucket bucket2 = bucketArr[i6]; null != bucket2; bucket2 = bucket2.next) {
                i3++;
                final String str2 = bucket2.symbol;
                final int i_hashToIndex2 = this._hashToIndex(this.calcHash(str2));
                final String[] strArr3 = _symbols;
                if (null == strArr3[i_hashToIndex2]) {
                    strArr3[i_hashToIndex2] = str2;
                } else {
                    final int i7 = i_hashToIndex2 >> 1;
                    final Bucket bucket3 = new Bucket(str2, _buckets[i7]);
                    _buckets[i7] = bucket3;
                    iMax = Math.max(iMax, bucket3.length);
                }
            }
        }
        _longestCollisionList = iMax;
        _overflows = null;
        if (i3 != _size) {
            throw new IllegalStateException(String.format("Internal error on SymbolTable.rehash(): had %d entries; now have %d", Integer.valueOf(_size), Integer.valueOf(i3)));
        }
    }

    private void reportTooManyCollisions(final int i2) {
        throw new IllegalStateException("Longest collision chain in symbol table (of size " + _size + ") now exceeds maximum, " + i2 + " -- suspect a DoS attack based on hash collisions");
    }

    static final class Bucket {
        public final int length;
        public final Bucket next;
        public final String symbol;

        public Bucket(final String str, final Bucket bucket) {
            symbol = str;
            next = bucket;
            length = null != bucket ? 1 + bucket.length : 1;
        }

        public String has(final char[] cArr, final int i2, final int i3) {
            if (symbol.length() != i3) {
                return null;
            }
            int i4 = 0;
            while (symbol.charAt(i4) == cArr[i2 + i4]) {
                i4++;
                if (i4 >= i3) {
                    return symbol;
                }
            }
            return null;
        }
    }

    private static final class TableInfo {
        final Bucket[] buckets;
        final int longestCollisionList;
        final int size;
        final String[] symbols;

        public TableInfo(final int i2, final int i3, final String[] strArr, final Bucket[] bucketArr) {
            size = i2;
            longestCollisionList = i3;
            symbols = strArr;
            buckets = bucketArr;
        }

        public TableInfo(final CharsToNameCanonicalizer charsToNameCanonicalizer) {
            size = charsToNameCanonicalizer._size;
            longestCollisionList = charsToNameCanonicalizer._longestCollisionList;
            symbols = charsToNameCanonicalizer._symbols;
            buckets = charsToNameCanonicalizer._buckets;
        }

        public static TableInfo createInitial(final int i2) {
            return new TableInfo(0, 0, new String[i2], new Bucket[i2 >> 1]);
        }
    }
}
