package okhttp3.internal.tls;

import androidx.webkit.ProxyConfig;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.Intrinsics;
import kotlin.text.StringsKt;
import okhttp3.internal.Util;
import okhttp3.internal.hostnames;
import okio.Utf8;

import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLException;
import javax.net.ssl.SSLSession;
import java.security.cert.Certificate;
import java.security.cert.CertificateParsingException;
import java.security.cert.X509Certificate;
import java.util.*;

import static kotlin.jvm.internal.Intrinsics.*;

// Class generated by  decompiler (1.5.3)
/* compiled from: OkHostnameVerifier.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class OkHostnameVerifier implements HostnameVerifier {
    public static final OkHostnameVerifier INSTANCE = new OkHostnameVerifier();
    private static final int ALT_DNS_NAME = 2;
    private static final int ALT_IPA_NAME = 7;

    private OkHostnameVerifier() {
    }

    @Override // javax.net.ssl.HostnameVerifier
    public boolean verify(final String host, final SSLSession session) {
        Intrinsics.checkNotNullParameter(host, "host");
        Intrinsics.checkNotNullParameter(session, "session");
        if (!this.isAscii(host)) {
            return false;
        }
        try {
            final Certificate certificate = session.getPeerCertificates()[0];
            if (null != certificate) {
                return this.verify(host, (X509Certificate) certificate);
            }
            throw new NullPointerException("null cannot be cast to non-null type java.security.cert.X509Certificate");
        } catch (final SSLException unused) {
            return false;
        }
    }

    public boolean verify(final String host, final X509Certificate certificate) {
        Intrinsics.checkNotNullParameter(host, "host");
        Intrinsics.checkNotNullParameter(certificate, "certificate");
        return Util.canParseAsIpAddress(host) ? this.verifyIpAddress(host, certificate) : this.verifyHostname(host, certificate);
    }

    private boolean verifyIpAddress(final String str, final X509Certificate x509Certificate) throws CertificateParsingException {
        final String canonicalHost = hostnames.toCanonicalHost(str);
        final List<String> subjectAltNames = this.getSubjectAltNames(x509Certificate, 7);
        if (null != subjectAltNames && subjectAltNames.isEmpty()) {
            return false;
        }
        final Iterator<T> it = subjectAltNames.iterator();
        while (it.hasNext()) {
            if (areEqual(canonicalHost, hostnames.toCanonicalHost((String) it.next()))) {
                return true;
            }
        }
        return false;
    }

    private boolean verifyHostname(final String str, final X509Certificate x509Certificate) throws CertificateParsingException {
        final String strAsciiToLowercase = this.asciiToLowercase(str);
        final List<String> subjectAltNames = this.getSubjectAltNames(x509Certificate, 2);
        if (null != subjectAltNames && subjectAltNames.isEmpty()) {
            return false;
        }
        final Iterator<T> it = subjectAltNames.iterator();
        while (it.hasNext()) {
            if (OkHostnameVerifier.INSTANCE.verifyHostname(strAsciiToLowercase, (String) it.next())) {
                return true;
            }
        }
        return false;
    }

    private String asciiToLowercase(final String str) {
        if (!this.isAscii(str)) {
            return str;
        }
        final Locale US = Locale.US;
        checkNotNullExpressionValue(US, "US");
        final String lowerCase = str.toLowerCase(US);
        checkNotNullExpressionValue(lowerCase, "this as java.lang.String).toLowerCase(locale)");
        return lowerCase;
    }

    private boolean isAscii(final String str) {
        return str.length() == ((int) Utf8.sizedefault(str, 0, 0, 3, null));
    }

    private boolean verifyHostname(String str, String str2) {
        if (null != str && 0 != str.length() && !StringsKt.startsWithdefault(str, ".", false, 2, (Object) null) && !StringsKt.endsWithdefault(str, "..", false, 2, (Object) null) && null != str2 && 0 != str2.length() && !StringsKt.startsWithdefault(str2, ".", false, 2, (Object) null) && !StringsKt.endsWithdefault(str2, "..", false, 2, (Object) null)) {
            if (!StringsKt.endsWithdefault(str, ".", false, 2, (Object) null)) {
                str = stringPlus(str, ".");
            }
            final String str3 = str;
            if (!StringsKt.endsWithdefault(str2, ".", false, 2, (Object) null)) {
                str2 = stringPlus(str2, ".");
            }
            final String strAsciiToLowercase = this.asciiToLowercase(str2);
            if (!StringsKt.containsdefault((CharSequence) strAsciiToLowercase, (CharSequence) ProxyConfig.MATCH_ALL_SCHEMES, false, 2, (Object) null)) {
                return areEqual(str3, strAsciiToLowercase);
            }
            if (!StringsKt.startsWithdefault(strAsciiToLowercase, "*.", false, 2, (Object) null) || -1 != StringsKt.indexOfdefault((CharSequence) strAsciiToLowercase, '*', 1, false, 4, (Object) null) || str3.length() < strAsciiToLowercase.length() || areEqual("*.", strAsciiToLowercase)) {
                return false;
            }
            final String strSubstring = strAsciiToLowercase.substring(1);
            checkNotNullExpressionValue(strSubstring, "this as java.lang.String).substring(startIndex)");
            if (!StringsKt.endsWithdefault(str3, strSubstring, false, 2, (Object) null)) {
                return false;
            }
            final int length = str3.length() - strSubstring.length();
            return 0 >= length || -1 == StringsKt.lastIndexOfdefault((CharSequence) str3, '.', length + (-1), false, 4, (Object) null);
        }
        return false;
    }

    public List<String> allSubjectAltNames(final X509Certificate certificate) {
        Intrinsics.checkNotNullParameter(certificate, "certificate");
        return CollectionsKt.plus((Collection) this.getSubjectAltNames(certificate, 7), (Iterable) this.getSubjectAltNames(certificate, 2));
    }

    private List<String> getSubjectAltNames(final X509Certificate x509Certificate, final int i2) throws CertificateParsingException {
        Object obj;
        try {
            final Collection<List<?>> subjectAlternativeNames = x509Certificate.getSubjectAlternativeNames();
            if (null == subjectAlternativeNames) {
                return CollectionsKt.emptyList();
            }
            final ArrayList arrayList = new ArrayList();
            for (final List<?> list : subjectAlternativeNames) {
                if (null != list && 2 <= list.size() && areEqual(list.get(0), Integer.valueOf(i2)) && null != (obj = list.get(1))) {
                    arrayList.add(obj);
                }
            }
            return arrayList;
        } catch (final CertificateParsingException unused) {
            return CollectionsKt.emptyList();
        }
    }
}
