package com.fasterxml.jackson.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

// Class generated by  decompiler (1.5.3)
@Target({ElementType.ANNOTATION_TYPE, ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public @interface JsonAnyGetter {
    boolean enabled() default true;
}
