package com.fasterxml.jackson.databind.jsontype.impl;

import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.cfg.MapperConfig;
import com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator;
import com.fasterxml.jackson.databind.type.TypeFactory;
import com.fasterxml.jackson.databind.util.ClassUtil;
import java.io.IOException;
import java.util.EnumMap;
import java.util.EnumSet;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class ClassNameIdResolver extends TypeIdResolverBase {
    protected final PolymorphicTypeValidator _subTypeValidator;

    public ClassNameIdResolver(final JavaType javaType, final TypeFactory typeFactory, final PolymorphicTypeValidator polymorphicTypeValidator) {
        super(javaType, typeFactory);
        _subTypeValidator = polymorphicTypeValidator;
    }

    public static ClassNameIdResolver construct(final JavaType javaType, final MapperConfig<?> mapperConfig, final PolymorphicTypeValidator polymorphicTypeValidator) {
        return new ClassNameIdResolver(javaType, mapperConfig.getTypeFactory(), polymorphicTypeValidator);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public String idFromValue(final Object obj) {
        return this._idFrom(obj, obj.getClass(), _typeFactory);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public String idFromValueAndType(final Object obj, final Class<?> cls) {
        return this._idFrom(obj, cls, _typeFactory);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase, com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public JavaType typeFromId(final DatabindContext databindContext, final String str) throws IOException {
        return this._typeFromId(str, databindContext);
    }

    protected JavaType _typeFromId(final String str, final DatabindContext databindContext) throws IOException, IllegalArgumentException {
        final JavaType javaTypeResolveAndValidateSubType = databindContext.resolveAndValidateSubType(_baseType, str, _subTypeValidator);
        return (null == javaTypeResolveAndValidateSubType && (databindContext instanceof DeserializationContext)) ? ((DeserializationContext) databindContext).handleUnknownTypeId(_baseType, str, this, "no such class found") : javaTypeResolveAndValidateSubType;
    }

    protected String _idFrom(final Object obj, Class<?> cls, final TypeFactory typeFactory) {
        if (ClassUtil.isEnumType(cls) && !cls.isEnum()) {
            cls = cls.getSuperclass();
        }
        final String name = cls.getName();
        if (!name.startsWith("java.util.")) {
            return (0 > name.indexOf(36) || null == ClassUtil.getOuterClass(cls) || null != ClassUtil.getOuterClass(this._baseType.getRawClass())) ? name : _baseType.getRawClass().getName();
        }
        if (obj instanceof EnumSet) {
            return typeFactory.constructCollectionType(EnumSet.class, ClassUtil.findEnumType((EnumSet<?>) obj)).toCanonical();
        }
        return obj instanceof EnumMap ? typeFactory.constructMapType(EnumMap.class, ClassUtil.findEnumType((EnumMap<?, ?>) obj), Object.class).toCanonical() : name;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase, com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public String getDescForKnownTypeIds() {
        return "class name used as type id";
    }
}
