package com.fasterxml.jackson.databind.jsontype.impl;

import com.fasterxml.jackson.databind.AnnotationIntrospector;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.cfg.MapperConfig;
import com.fasterxml.jackson.databind.introspect.AnnotatedClass;
import com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.jsontype.NamedType;
import com.fasterxml.jackson.databind.jsontype.SubtypeResolver;
import java.io.Serializable;
import java.lang.reflect.Modifier;
import java.util.*;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class StdSubtypeResolver extends SubtypeResolver implements Serializable {
    private static final long serialVersionUID = 1;
    protected LinkedHashSet<NamedType> _registeredSubtypes;

    public StdSubtypeResolver() {
    }

    protected StdSubtypeResolver(final StdSubtypeResolver stdSubtypeResolver) {
        final LinkedHashSet<NamedType> linkedHashSet = stdSubtypeResolver._registeredSubtypes;
        _registeredSubtypes = null == linkedHashSet ? null : new LinkedHashSet<>(linkedHashSet);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public SubtypeResolver copy() {
        return new StdSubtypeResolver(this);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public void registerSubtypes(final NamedType... namedTypeArr) {
        if (null == this._registeredSubtypes) {
            _registeredSubtypes = new LinkedHashSet<>();
        }
        Collections.addAll(_registeredSubtypes, namedTypeArr);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public void registerSubtypes(final Class<?>... clsArr) {
        final NamedType[] namedTypeArr = new NamedType[clsArr.length];
        final int length = clsArr.length;
        for (int i2 = 0; i2 < length; i2++) {
            namedTypeArr[i2] = new NamedType(clsArr[i2]);
        }
        this.registerSubtypes(namedTypeArr);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public void registerSubtypes(final Collection<Class<?>> collection) {
        final NamedType[] namedTypeArr = new NamedType[collection.size()];
        final Iterator<Class<?>> it = collection.iterator();
        int i2 = 0;
        while (it.hasNext()) {
            namedTypeArr[i2] = new NamedType(it.next());
            i2++;
        }
        this.registerSubtypes(namedTypeArr);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public Collection<NamedType> collectAndResolveSubtypesByClass(final MapperConfig<?> mapperConfig, final AnnotatedMember annotatedMember, final JavaType javaType) {
        final List<NamedType> listFindSubtypes;
        final AnnotationIntrospector annotationIntrospector = mapperConfig.getAnnotationIntrospector();
        final Class<?> rawType = null == javaType ? annotatedMember.getRawType() : javaType.getRawClass();
        final HashMap<NamedType, NamedType> map = new HashMap<>();
        final LinkedHashSet<NamedType> linkedHashSet = _registeredSubtypes;
        if (null != linkedHashSet) {
            final Iterator<NamedType> it = linkedHashSet.iterator();
            while (it.hasNext()) {
                final NamedType next = it.next();
                if (rawType.isAssignableFrom(next.getType())) {
                    this._collectAndResolve(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, next.getType()), next, mapperConfig, annotationIntrospector, map);
                }
            }
        }
        if (null != annotatedMember && null != (listFindSubtypes = annotationIntrospector.findSubtypes(annotatedMember))) {
            for (final NamedType namedType : listFindSubtypes) {
                this._collectAndResolve(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, namedType.getType()), namedType, mapperConfig, annotationIntrospector, map);
            }
        }
        this._collectAndResolve(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, rawType), new NamedType(rawType, null), mapperConfig, annotationIntrospector, map);
        return new ArrayList(map.values());
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public Collection<NamedType> collectAndResolveSubtypesByClass(final MapperConfig<?> mapperConfig, final AnnotatedClass annotatedClass) {
        final AnnotationIntrospector annotationIntrospector = mapperConfig.getAnnotationIntrospector();
        final HashMap<NamedType, NamedType> map = new HashMap<>();
        if (null != this._registeredSubtypes) {
            final Class<?> rawType = annotatedClass.getRawType();
            final Iterator<NamedType> it = _registeredSubtypes.iterator();
            while (it.hasNext()) {
                final NamedType next = it.next();
                if (rawType.isAssignableFrom(next.getType())) {
                    this._collectAndResolve(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, next.getType()), next, mapperConfig, annotationIntrospector, map);
                }
            }
        }
        this._collectAndResolve(annotatedClass, new NamedType(annotatedClass.getRawType(), null), mapperConfig, annotationIntrospector, map);
        return new ArrayList(map.values());
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public Collection<NamedType> collectAndResolveSubtypesByTypeId(final MapperConfig<?> mapperConfig, final AnnotatedMember annotatedMember, final JavaType javaType) {
        final List<NamedType> listFindSubtypes;
        final AnnotationIntrospector annotationIntrospector = mapperConfig.getAnnotationIntrospector();
        final Class<?> rawClass = javaType.getRawClass();
        final HashSet hashSet = new HashSet();
        final LinkedHashMap linkedHashMap = new LinkedHashMap();
        this._collectAndResolveByTypeId(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, rawClass), new NamedType(rawClass, null), mapperConfig, hashSet, linkedHashMap);
        if (null != annotatedMember && null != (listFindSubtypes = annotationIntrospector.findSubtypes(annotatedMember))) {
            for (final NamedType namedType : listFindSubtypes) {
                this._collectAndResolveByTypeId(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, namedType.getType()), namedType, mapperConfig, hashSet, linkedHashMap);
            }
        }
        final LinkedHashSet<NamedType> linkedHashSet = _registeredSubtypes;
        if (null != linkedHashSet) {
            final Iterator<NamedType> it = linkedHashSet.iterator();
            while (it.hasNext()) {
                final NamedType next = it.next();
                if (rawClass.isAssignableFrom(next.getType())) {
                    this._collectAndResolveByTypeId(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, next.getType()), next, mapperConfig, hashSet, linkedHashMap);
                }
            }
        }
        return this._combineNamedAndUnnamed(rawClass, hashSet, linkedHashMap);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.SubtypeResolver
    public Collection<NamedType> collectAndResolveSubtypesByTypeId(final MapperConfig<?> mapperConfig, final AnnotatedClass annotatedClass) {
        final Class<?> rawType = annotatedClass.getRawType();
        final HashSet hashSet = new HashSet();
        final LinkedHashMap linkedHashMap = new LinkedHashMap();
        this._collectAndResolveByTypeId(annotatedClass, new NamedType(rawType, null), mapperConfig, hashSet, linkedHashMap);
        final LinkedHashSet<NamedType> linkedHashSet = _registeredSubtypes;
        if (null != linkedHashSet) {
            final Iterator<NamedType> it = linkedHashSet.iterator();
            while (it.hasNext()) {
                final NamedType next = it.next();
                if (rawType.isAssignableFrom(next.getType())) {
                    this._collectAndResolveByTypeId(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, next.getType()), next, mapperConfig, hashSet, linkedHashMap);
                }
            }
        }
        return this._combineNamedAndUnnamed(rawType, hashSet, linkedHashMap);
    }

    protected void _collectAndResolve(final AnnotatedClass annotatedClass, NamedType namedType, final MapperConfig<?> mapperConfig, final AnnotationIntrospector annotationIntrospector, final HashMap<NamedType, NamedType> map) {
        final String strFindTypeName;
        if (!namedType.hasName() && null != (strFindTypeName = annotationIntrospector.findTypeName(annotatedClass))) {
            namedType = new NamedType(namedType.getType(), strFindTypeName);
        }
        final NamedType namedType2 = new NamedType(namedType.getType());
        if (map.containsKey(namedType2)) {
            if (!namedType.hasName() || map.get(namedType2).hasName()) {
                return;
            }
            map.put(namedType2, namedType);
            return;
        }
        map.put(namedType2, namedType);
        final List<NamedType> listFindSubtypes = annotationIntrospector.findSubtypes(annotatedClass);
        if (null == listFindSubtypes || listFindSubtypes.isEmpty()) {
            return;
        }
        for (final NamedType namedType3 : listFindSubtypes) {
            this._collectAndResolve(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, namedType3.getType()), namedType3, mapperConfig, annotationIntrospector, map);
        }
    }

    protected void _collectAndResolveByTypeId(final AnnotatedClass annotatedClass, NamedType namedType, final MapperConfig<?> mapperConfig, final Set<Class<?>> set, final Map<String, NamedType> map) {
        final List<NamedType> listFindSubtypes;
        final String strFindTypeName;
        final AnnotationIntrospector annotationIntrospector = mapperConfig.getAnnotationIntrospector();
        if (!namedType.hasName() && null != (strFindTypeName = annotationIntrospector.findTypeName(annotatedClass))) {
            namedType = new NamedType(namedType.getType(), strFindTypeName);
        }
        if (namedType.hasName()) {
            map.put(namedType.getName(), namedType);
        }
        if (!set.add(namedType.getType()) || null == (listFindSubtypes = annotationIntrospector.findSubtypes(annotatedClass)) || listFindSubtypes.isEmpty()) {
            return;
        }
        for (final NamedType namedType2 : listFindSubtypes) {
            this._collectAndResolveByTypeId(AnnotatedClassResolver.resolveWithoutSuperTypes(mapperConfig, namedType2.getType()), namedType2, mapperConfig, set, map);
        }
    }

    protected Collection<NamedType> _combineNamedAndUnnamed(final Class<?> cls, final Set<Class<?>> set, final Map<String, NamedType> map) {
        final ArrayList arrayList = new ArrayList(map.values());
        final Iterator<NamedType> it = map.values().iterator();
        while (it.hasNext()) {
            set.remove(it.next().getType());
        }
        for (final Class<?> cls2 : set) {
            if (cls2 != cls || !Modifier.isAbstract(cls2.getModifiers())) {
                arrayList.add(new NamedType(cls2));
            }
        }
        return arrayList;
    }
}
