package com.fasterxml.jackson.databind.jsontype.impl;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.DeserializationConfig;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.annotation.NoClass;
import com.fasterxml.jackson.databind.cfg.MapperConfig;
import com.fasterxml.jackson.databind.jsontype.*;
import com.fasterxml.jackson.databind.util.ClassUtil;

import java.util.Collection;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class StdTypeResolverBuilder implements TypeResolverBuilder<StdTypeResolverBuilder> {
    protected TypeIdResolver _customIdResolver;
    protected Class<?> _defaultImpl;
    protected JsonTypeInfo.EnumC1185Id _idType;
    protected JsonTypeInfo.EnumC1184As _includeAs;
    protected boolean _typeIdVisible;
    protected String _typeProperty;

    protected boolean allowPrimitiveTypes(final MapperConfig<?> mapperConfig, final JavaType javaType) {
        return false;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public TypeResolverBuilder defaultImpl(final Class cls) {
        return this.defaultImpl((Class<?>) cls);
    }

    public StdTypeResolverBuilder() {
    }

    protected StdTypeResolverBuilder(final JsonTypeInfo.EnumC1185Id enumC1185Id, final JsonTypeInfo.EnumC1184As enumC1184As, final String str) {
        _idType = enumC1185Id;
        _includeAs = enumC1184As;
        _typeProperty = str;
    }

    public static StdTypeResolverBuilder noTypeInfoBuilder() {
        return new StdTypeResolverBuilder().init(JsonTypeInfo.EnumC1185Id.NONE, null);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public StdTypeResolverBuilder init(final JsonTypeInfo.EnumC1185Id enumC1185Id, final TypeIdResolver typeIdResolver) {
        if (null == enumC1185Id) {
            throw new IllegalArgumentException("idType cannot be null");
        }
        _idType = enumC1185Id;
        _customIdResolver = typeIdResolver;
        _typeProperty = enumC1185Id.getDefaultPropertyName();
        return this;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public TypeSerializer buildTypeSerializer(final SerializationConfig serializationConfig, final JavaType javaType, final Collection<NamedType> collection) {
        if (JsonTypeInfo.EnumC1185Id.NONE == this._idType) {
            return null;
        }
        if (javaType.isPrimitive() && !this.allowPrimitiveTypes(serializationConfig, javaType)) {
            return null;
        }
        final TypeIdResolver typeIdResolverIdResolver = this.idResolver(serializationConfig, javaType, this.subTypeValidator(serializationConfig), collection, true, false);
        if (JsonTypeInfo.EnumC1185Id.DEDUCTION == this._idType) {
            return new AsExistingPropertyTypeSerializer(typeIdResolverIdResolver, null, _typeProperty);
        }
        final int i2 = C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs[_includeAs.ordinal()];
        if (1 == i2) {
            return new AsArrayTypeSerializer(typeIdResolverIdResolver, null);
        }
        if (2 == i2) {
            return new AsPropertyTypeSerializer(typeIdResolverIdResolver, null, _typeProperty);
        }
        if (3 == i2) {
            return new AsWrapperTypeSerializer(typeIdResolverIdResolver, null);
        }
        if (4 == i2) {
            return new AsExternalTypeSerializer(typeIdResolverIdResolver, null, _typeProperty);
        }
        if (5 == i2) {
            return new AsExistingPropertyTypeSerializer(typeIdResolverIdResolver, null, _typeProperty);
        }
        throw new IllegalStateException("Do not know how to construct standard type serializer for inclusion type: " + _includeAs);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public TypeDeserializer buildTypeDeserializer(final DeserializationConfig deserializationConfig, final JavaType javaType, final Collection<NamedType> collection) {
        if (JsonTypeInfo.EnumC1185Id.NONE == this._idType) {
            return null;
        }
        if (javaType.isPrimitive() && !this.allowPrimitiveTypes(deserializationConfig, javaType)) {
            return null;
        }
        final TypeIdResolver typeIdResolverIdResolver = this.idResolver(deserializationConfig, javaType, this.verifyBaseTypeValidity(deserializationConfig, javaType), collection, false, true);
        final JavaType javaTypeDefineDefaultImpl = this.defineDefaultImpl(deserializationConfig, javaType);
        if (JsonTypeInfo.EnumC1185Id.DEDUCTION == this._idType) {
            return new AsDeductionTypeDeserializer(javaType, typeIdResolverIdResolver, javaTypeDefineDefaultImpl, deserializationConfig, collection);
        }
        final int i2 = C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs[_includeAs.ordinal()];
        if (1 == i2) {
            return new AsArrayTypeDeserializer(javaType, typeIdResolverIdResolver, _typeProperty, _typeIdVisible, javaTypeDefineDefaultImpl);
        }
        if (2 != i2) {
            if (3 == i2) {
                return new AsWrapperTypeDeserializer(javaType, typeIdResolverIdResolver, _typeProperty, _typeIdVisible, javaTypeDefineDefaultImpl);
            }
            if (4 == i2) {
                return new AsExternalTypeDeserializer(javaType, typeIdResolverIdResolver, _typeProperty, _typeIdVisible, javaTypeDefineDefaultImpl);
            }
            if (5 != i2) {
                throw new IllegalStateException("Do not know how to construct standard type serializer for inclusion type: " + _includeAs);
            }
        }
        return new AsPropertyTypeDeserializer(javaType, typeIdResolverIdResolver, _typeProperty, _typeIdVisible, javaTypeDefineDefaultImpl, _includeAs);
    }

    protected JavaType defineDefaultImpl(final DeserializationConfig deserializationConfig, final JavaType javaType) {
        final Class<?> cls = _defaultImpl;
        if (null == cls) {
            if (deserializationConfig.isEnabled(MapperFeature.USE_BASE_TYPE_AS_DEFAULT_IMPL) && !javaType.isAbstract()) {
                return javaType;
            }
        } else {
            if (Void.class == cls || NoClass.class == cls) {
                return deserializationConfig.getTypeFactory().constructType(_defaultImpl);
            }
            if (javaType.hasRawClass(cls)) {
                return javaType;
            }
            if (javaType.isTypeOrSuperTypeOf(_defaultImpl)) {
                return deserializationConfig.getTypeFactory().constructSpecializedType(javaType, _defaultImpl);
            }
        }
        return null;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public StdTypeResolverBuilder inclusion(final JsonTypeInfo.EnumC1184As enumC1184As) {
        if (null == enumC1184As) {
            throw new IllegalArgumentException("includeAs cannot be null");
        }
        _includeAs = enumC1184As;
        return this;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public StdTypeResolverBuilder typeProperty(String str) {
        if (null == str || str.isEmpty()) {
            str = _idType.getDefaultPropertyName();
        }
        _typeProperty = str;
        return this;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public StdTypeResolverBuilder defaultImpl(final Class<?> cls) {
        _defaultImpl = cls;
        return this;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public StdTypeResolverBuilder typeIdVisibility(final boolean z) {
        _typeIdVisible = z;
        return this;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
    public Class<?> getDefaultImpl() {
        return _defaultImpl;
    }

    public String getTypeProperty() {
        return _typeProperty;
    }

    public boolean isTypeIdVisible() {
        return _typeIdVisible;
    }

    protected TypeIdResolver idResolver(final MapperConfig<?> mapperConfig, final JavaType javaType, final PolymorphicTypeValidator polymorphicTypeValidator, final Collection<NamedType> collection, final boolean z, final boolean z2) {
        final TypeIdResolver typeIdResolver = _customIdResolver;
        if (null != typeIdResolver) {
            return typeIdResolver;
        }
        final JsonTypeInfo.EnumC1185Id enumC1185Id = _idType;
        if (null == enumC1185Id) {
            throw new IllegalStateException("Cannot build, 'init()' not yet called");
        }
        final int i2 = C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId[enumC1185Id.ordinal()];
        if (1 == i2 || 2 == i2) {
            return ClassNameIdResolver.construct(javaType, mapperConfig, polymorphicTypeValidator);
        }
        if (3 == i2) {
            return MinimalClassNameIdResolver.construct(javaType, mapperConfig, polymorphicTypeValidator);
        }
        if (4 == i2) {
            return TypeNameIdResolver.construct(mapperConfig, javaType, collection, z, z2);
        }
        if (5 == i2) {
            return null;
        }
        throw new IllegalStateException("Do not know how to construct standard type id resolver for idType: " + _idType);
    }

    /* renamed from: com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder1 */
    enum C12111 {
        ;
        static final int[] SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs;
        static final int[] SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId;

        static {
            final int[] iArr = new int[JsonTypeInfo.EnumC1185Id.values().length];
            SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId = iArr;
            try {
                iArr[JsonTypeInfo.EnumC1185Id.DEDUCTION.ordinal()] = 1;
            } catch (final NoSuchFieldError unused) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId[JsonTypeInfo.EnumC1185Id.CLASS.ordinal()] = 2;
            } catch (final NoSuchFieldError unused2) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId[JsonTypeInfo.EnumC1185Id.MINIMAL_CLASS.ordinal()] = 3;
            } catch (final NoSuchFieldError unused3) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId[JsonTypeInfo.EnumC1185Id.NAME.ordinal()] = 4;
            } catch (final NoSuchFieldError unused4) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId[JsonTypeInfo.EnumC1185Id.NONE.ordinal()] = 5;
            } catch (final NoSuchFieldError unused5) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoId[JsonTypeInfo.EnumC1185Id.CUSTOM.ordinal()] = 6;
            } catch (final NoSuchFieldError unused6) {
            }
            final int[] iArr2 = new int[JsonTypeInfo.EnumC1184As.values().length];
            SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs = iArr2;
            try {
                iArr2[JsonTypeInfo.EnumC1184As.WRAPPER_ARRAY.ordinal()] = 1;
            } catch (final NoSuchFieldError unused7) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs[JsonTypeInfo.EnumC1184As.PROPERTY.ordinal()] = 2;
            } catch (final NoSuchFieldError unused8) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs[JsonTypeInfo.EnumC1184As.WRAPPER_OBJECT.ordinal()] = 3;
            } catch (final NoSuchFieldError unused9) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs[JsonTypeInfo.EnumC1184As.EXTERNAL_PROPERTY.ordinal()] = 4;
            } catch (final NoSuchFieldError unused10) {
            }
            try {
                C12111.SwitchMapcomfasterxmljacksonannotationJsonTypeInfoAs[JsonTypeInfo.EnumC1184As.EXISTING_PROPERTY.ordinal()] = 5;
            } catch (final NoSuchFieldError unused11) {
            }
        }
    }

    public PolymorphicTypeValidator subTypeValidator(final MapperConfig<?> mapperConfig) {
        return mapperConfig.getPolymorphicTypeValidator();
    }

    protected PolymorphicTypeValidator verifyBaseTypeValidity(final MapperConfig<?> mapperConfig, final JavaType javaType) {
        final PolymorphicTypeValidator polymorphicTypeValidatorSubTypeValidator = this.subTypeValidator(mapperConfig);
        final JsonTypeInfo.EnumC1185Id enumC1185Id = _idType;
        if (JsonTypeInfo.EnumC1185Id.CLASS == enumC1185Id || JsonTypeInfo.EnumC1185Id.MINIMAL_CLASS == enumC1185Id) {
            final PolymorphicTypeValidator.Validity validityValidateBaseType = polymorphicTypeValidatorSubTypeValidator.validateBaseType(mapperConfig, javaType);
            if (PolymorphicTypeValidator.Validity.DENIED == validityValidateBaseType) {
                return this.reportInvalidBaseType(mapperConfig, javaType, polymorphicTypeValidatorSubTypeValidator);
            }
            if (PolymorphicTypeValidator.Validity.ALLOWED == validityValidateBaseType) {
                return LaissezFaireSubTypeValidator.instance;
            }
        }
        return polymorphicTypeValidatorSubTypeValidator;
    }

    protected PolymorphicTypeValidator reportInvalidBaseType(final MapperConfig<?> mapperConfig, final JavaType javaType, final PolymorphicTypeValidator polymorphicTypeValidator) {
        throw new IllegalArgumentException(String.format("Configured `PolymorphicTypeValidator` (of type %s) denied resolution of all subtypes of base type %s", ClassUtil.classNameOf(polymorphicTypeValidator), ClassUtil.classNameOf(javaType.getRawClass())));
    }
}
