package com.fasterxml.jackson.databind.jsontype.impl;

import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.cfg.MapperConfig;
import com.fasterxml.jackson.databind.jsontype.NamedType;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeSet;
import java.util.concurrent.ConcurrentHashMap;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class TypeNameIdResolver extends TypeIdResolverBase {
    protected final boolean _caseInsensitive;
    protected final MapperConfig<?> _config;
    protected final Map<String, JavaType> _idToType;
    protected final ConcurrentHashMap<String, String> _typeToId;

    protected TypeNameIdResolver(final MapperConfig<?> mapperConfig, final JavaType javaType, final ConcurrentHashMap<String, String> concurrentHashMap, final HashMap<String, JavaType> map) {
        super(javaType, mapperConfig.getTypeFactory());
        _config = mapperConfig;
        _typeToId = concurrentHashMap;
        _idToType = map;
        _caseInsensitive = mapperConfig.isEnabled(MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES);
    }

    public static TypeNameIdResolver construct(final MapperConfig<?> mapperConfig, final JavaType javaType, final Collection<NamedType> collection, final boolean z, final boolean z2) {
        final HashMap map;
        final ConcurrentHashMap concurrentHashMap;
        if (z == z2) {
            throw new IllegalArgumentException();
        }
        if (z) {
            concurrentHashMap = new ConcurrentHashMap();
            map = null;
        } else {
            map = new HashMap();
            concurrentHashMap = new ConcurrentHashMap(4);
        }
        final boolean zIsEnabled = mapperConfig.isEnabled(MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES);
        if (null != collection) {
            for (final NamedType namedType : collection) {
                final Class<?> type = namedType.getType();
                String name = namedType.hasName() ? namedType.getName() : TypeNameIdResolver._defaultTypeId(type);
                if (z) {
                    concurrentHashMap.put(type.getName(), name);
                }
                if (z2) {
                    if (zIsEnabled) {
                        name = name.toLowerCase();
                    }
                    final JavaType javaType2 = (JavaType) map.get(name);
                    if (null == javaType2 || !type.isAssignableFrom(javaType2.getRawClass())) {
                        map.put(name, mapperConfig.constructType(type));
                    }
                }
            }
        }
        return new TypeNameIdResolver(mapperConfig, javaType, concurrentHashMap, map);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public String idFromValue(final Object obj) {
        return this.idFromClass(obj.getClass());
    }

    protected String idFromClass(final Class<?> cls) {
        if (null == cls) {
            return null;
        }
        final String name = cls.getName();
        String str_defaultTypeId = _typeToId.get(name);
        if (null == str_defaultTypeId) {
            final Class<?> rawClass = _typeFactory.constructType(cls).getRawClass();
            if (_config.isAnnotationProcessingEnabled()) {
                str_defaultTypeId = _config.getAnnotationIntrospector().findTypeName(_config.introspectClassAnnotations(rawClass).getClassInfo());
            }
            if (null == str_defaultTypeId) {
                str_defaultTypeId = TypeNameIdResolver._defaultTypeId(rawClass);
            }
            _typeToId.put(name, str_defaultTypeId);
        }
        return str_defaultTypeId;
    }

    @Override // com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public String idFromValueAndType(final Object obj, final Class<?> cls) {
        if (null == obj) {
            return this.idFromClass(cls);
        }
        return this.idFromValue(obj);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase, com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public JavaType typeFromId(final DatabindContext databindContext, final String str) {
        return this._typeFromId(str);
    }

    protected JavaType _typeFromId(String str) {
        if (_caseInsensitive) {
            str = str.toLowerCase();
        }
        return _idToType.get(str);
    }

    @Override // com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase, com.fasterxml.jackson.databind.jsontype.TypeIdResolver
    public String getDescForKnownTypeIds() {
        final TreeSet treeSet = new TreeSet();
        for (final Map.Entry<String, JavaType> entry : _idToType.entrySet()) {
            if (entry.getValue().isConcrete()) {
                treeSet.add(entry.getKey());
            }
        }
        return treeSet.toString();
    }

    public String toString() {
        return String.format("[%s; id-to-type=%s]", this.getClass().getName(), _idToType);
    }

    protected static String _defaultTypeId(final Class<?> cls) {
        final String name = cls.getName();
        final int iLastIndexOf = name.lastIndexOf(46);
        return 0 > iLastIndexOf ? name : name.substring(iLastIndexOf + 1);
    }
}
