package com.fasterxml.jackson.core.util;

import java.io.OutputStream;
import java.util.Iterator;
import java.util.LinkedList;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class ByteArrayBuilder extends OutputStream {
    public static final byte[] NO_BYTES = new byte[0];
    private final BufferRecycler _bufferRecycler;
    private byte[] _currBlock;
    private int _currBlockPtr;
    private final LinkedList<byte[]> _pastBlocks;
    private int _pastLen;

    @Override // java.io.OutputStream, java.io.Closeable, java.lang.AutoCloseable
    public void close() {
    }

    @Override // java.io.OutputStream, java.io.Flushable
    public void flush() {
    }

    public ByteArrayBuilder() {
        this(null);
    }

    public ByteArrayBuilder(final BufferRecycler bufferRecycler) {
        this(bufferRecycler, 500);
    }

    public ByteArrayBuilder(final int i2) {
        this(null, i2);
    }

    public ByteArrayBuilder(final BufferRecycler bufferRecycler, final int i2) {
        _pastBlocks = new LinkedList<>();
        _bufferRecycler = bufferRecycler;
        _currBlock = null == bufferRecycler ? new byte[131072 < i2 ? 131072 : i2] : bufferRecycler.allocByteBuffer(2);
    }

    private ByteArrayBuilder(final BufferRecycler bufferRecycler, final byte[] bArr, final int i2) {
        _pastBlocks = new LinkedList<>();
        _bufferRecycler = null;
        _currBlock = bArr;
        _currBlockPtr = i2;
    }

    public static ByteArrayBuilder fromInitial(final byte[] bArr, final int i2) {
        return new ByteArrayBuilder(null, bArr, i2);
    }

    public void reset() {
        _pastLen = 0;
        _currBlockPtr = 0;
        if (_pastBlocks.isEmpty()) {
            return;
        }
        _pastBlocks.clear();
    }

    public void release() {
        final byte[] bArr;
        this.reset();
        final BufferRecycler bufferRecycler = _bufferRecycler;
        if (null == bufferRecycler || null == (bArr = this._currBlock)) {
            return;
        }
        bufferRecycler.releaseByteBuffer(2, bArr);
        _currBlock = null;
    }

    public void append(final int i2) {
        if (_currBlockPtr >= _currBlock.length) {
            this._allocMore();
        }
        final byte[] bArr = _currBlock;
        final int i3 = _currBlockPtr;
        _currBlockPtr = i3 + 1;
        bArr[i3] = (byte) i2;
    }

    public void appendTwoBytes(final int i2) {
        final int i3 = _currBlockPtr;
        final int i4 = i3 + 1;
        final byte[] bArr = _currBlock;
        if (i4 < bArr.length) {
            final int i5 = i3 + 1;
            _currBlockPtr = i5;
            bArr[i3] = (byte) (i2 >> 8);
            _currBlockPtr = i3 + 2;
            bArr[i5] = (byte) i2;
            return;
        }
        this.append(i2 >> 8);
        this.append(i2);
    }

    public void appendThreeBytes(final int i2) {
        final int i3 = _currBlockPtr;
        final int i4 = i3 + 2;
        final byte[] bArr = _currBlock;
        if (i4 < bArr.length) {
            final int i5 = i3 + 1;
            _currBlockPtr = i5;
            bArr[i3] = (byte) (i2 >> 16);
            final int i6 = i3 + 2;
            _currBlockPtr = i6;
            bArr[i5] = (byte) (i2 >> 8);
            _currBlockPtr = i3 + 3;
            bArr[i6] = (byte) i2;
            return;
        }
        this.append(i2 >> 16);
        this.append(i2 >> 8);
        this.append(i2);
    }

    public byte[] toByteArray() {
        final int i2 = _pastLen + _currBlockPtr;
        if (0 == i2) {
            return ByteArrayBuilder.NO_BYTES;
        }
        final byte[] bArr = new byte[i2];
        final Iterator<byte[]> it = _pastBlocks.iterator();
        int i3 = 0;
        while (it.hasNext()) {
            final byte[] next = it.next();
            final int length = next.length;
            System.arraycopy(next, 0, bArr, i3, length);
            i3 += length;
        }
        System.arraycopy(_currBlock, 0, bArr, i3, _currBlockPtr);
        final int i4 = i3 + _currBlockPtr;
        if (i4 != i2) {
            throw new RuntimeException("Internal error: total len assumed to be " + i2 + ", copied " + i4 + " bytes");
        }
        if (!_pastBlocks.isEmpty()) {
            this.reset();
        }
        return bArr;
    }

    public byte[] finishCurrentSegment() {
        this._allocMore();
        return _currBlock;
    }

    public byte[] completeAndCoalesce(final int i2) {
        _currBlockPtr = i2;
        return this.toByteArray();
    }

    public byte[] getCurrentSegment() {
        return _currBlock;
    }

    public void setCurrentSegmentLength(final int i2) {
        _currBlockPtr = i2;
    }

    public int getCurrentSegmentLength() {
        return _currBlockPtr;
    }

    @Override // java.io.OutputStream
    public void write(final byte[] bArr) {
        this.write(bArr, 0, bArr.length);
    }

    @Override // java.io.OutputStream
    public void write(final byte[] bArr, int i2, int i3) {
        while (true) {
            final int iMin = Math.min(_currBlock.length - _currBlockPtr, i3);
            if (0 < iMin) {
                System.arraycopy(bArr, i2, _currBlock, _currBlockPtr, iMin);
                i2 += iMin;
                _currBlockPtr += iMin;
                i3 -= iMin;
            }
            if (0 >= i3) {
                return;
            } else {
                this._allocMore();
            }
        }
    }

    @Override // java.io.OutputStream
    public void write(final int i2) {
        this.append(i2);
    }

    private void _allocMore() {
        final int length = _pastLen + _currBlock.length;
        if (0 > length) {
            throw new IllegalStateException("Maximum Java array size (2GB) exceeded by `ByteArrayBuilder`");
        }
        _pastLen = length;
        int iMax = Math.max(length >> 1, 1000);
        if (131072 < iMax) {
            iMax = 131072;
        }
        _pastBlocks.add(_currBlock);
        _currBlock = new byte[iMax];
        _currBlockPtr = 0;
    }
}
