package okhttp3.internal.platform.android;

import kotlin.jvm.internal.Intrinsics;
import okhttp3.Protocol;

import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.X509TrustManager;
import java.util.List;

// Class generated by  decompiler (1.5.3)
/* compiled from: SocketAdapter.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public interface SocketAdapter {

    void configureTlsExtensions(SSLSocket sSLSocket, String str, List<Protocol> list);

    String getSelectedProtocol(SSLSocket sSLSocket);

    boolean isSupported();

    boolean matchesSocket(SSLSocket sSLSocket);

    boolean matchesSocketFactory(SSLSocketFactory sSLSocketFactory);

    X509TrustManager trustManager(SSLSocketFactory sSLSocketFactory) throws IllegalAccessException;

    /* compiled from: SocketAdapter.kt */
    enum DefaultImpls {
        ;

        public static boolean matchesSocketFactory(final SocketAdapter socketAdapter, final SSLSocketFactory sslSocketFactory) {
            Intrinsics.checkNotNullParameter(socketAdapter, "this");
            Intrinsics.checkNotNullParameter(sslSocketFactory, "sslSocketFactory");
            return false;
        }

        public static X509TrustManager trustManager(final SocketAdapter socketAdapter, final SSLSocketFactory sslSocketFactory) {
            Intrinsics.checkNotNullParameter(socketAdapter, "this");
            Intrinsics.checkNotNullParameter(sslSocketFactory, "sslSocketFactory");
            return null;
        }
    }
}
