package com.fasterxml.jackson.databind.ser.std;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.WritableTypeId;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsonschema.JsonSchema;
import com.fasterxml.jackson.databind.jsonschema.SchemaAware;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.ser.ContainerSerializer;
import com.fasterxml.jackson.databind.ser.ContextualSerializer;
import com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap;
import com.google.firebase.analytics.FirebaseAnalytics;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.Objects;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public abstract class AsArraySerializerBase<T> extends ContainerSerializer<T> implements ContextualSerializer {
    protected PropertySerializerMap _dynamicSerializers;
    protected final JsonSerializer<Object> _elementSerializer;
    protected final JavaType _elementType;
    protected final BeanProperty _property;
    protected final boolean _staticTyping;
    protected final Boolean _unwrapSingle;
    protected final TypeSerializer _valueTypeSerializer;

    protected abstract void serializeContents(T t, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException;

    public abstract AsArraySerializerBase<T> withResolved(BeanProperty beanProperty, TypeSerializer typeSerializer, JsonSerializer<?> jsonSerializer, Boolean bool);

    protected AsArraySerializerBase(final Class<?> cls, final JavaType javaType, final boolean z, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer) {
        this(cls, javaType, z, typeSerializer, null, jsonSerializer, null);
    }

    @Deprecated
    protected AsArraySerializerBase(final Class<?> cls, final JavaType javaType, final boolean z, final TypeSerializer typeSerializer, final BeanProperty beanProperty, final JsonSerializer<Object> jsonSerializer) {
        this(cls, javaType, z, typeSerializer, beanProperty, jsonSerializer, null);
    }


    protected AsArraySerializerBase(final Class<?> cls, final JavaType javaType, final boolean z, final TypeSerializer typeSerializer, final BeanProperty beanProperty, final JsonSerializer<?> jsonSerializer, final Boolean bool) {
        super(cls, false);
        boolean z2 = false;
        _elementType = javaType;
        if (z || (null != javaType && javaType.isFinal())) {
            z2 = true;
        }
        _staticTyping = z2;
        _valueTypeSerializer = typeSerializer;
        _property = beanProperty;
        _elementSerializer = jsonSerializer;
        _dynamicSerializers = PropertySerializerMap.emptyForProperties();
        _unwrapSingle = bool;
    }

    protected AsArraySerializerBase(final AsArraySerializerBase<?> asArraySerializerBase, final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer, final Boolean bool) {
        super(asArraySerializerBase);
        _elementType = asArraySerializerBase._elementType;
        _staticTyping = asArraySerializerBase._staticTyping;
        _valueTypeSerializer = typeSerializer;
        _property = beanProperty;
        _elementSerializer = jsonSerializer;
        _dynamicSerializers = PropertySerializerMap.emptyForProperties();
        _unwrapSingle = bool;
    }

    @Deprecated
    protected AsArraySerializerBase(final AsArraySerializerBase<?> asArraySerializerBase, final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer) {
        this(asArraySerializerBase, beanProperty, typeSerializer, jsonSerializer, asArraySerializerBase._unwrapSingle);
    }

    @Deprecated
    public final AsArraySerializerBase<T> withResolved(final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer) {
        return this.withResolved(beanProperty, typeSerializer, jsonSerializer, _unwrapSingle);
    }

    /*  WARN: Removed duplicated region for block: B:12:0x0020  */
    @Override // com.fasterxml.jackson.databind.ser.ContextualSerializer
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public JsonSerializer<?> createContextual(final SerializerProvider serializerProvider, final BeanProperty beanProperty) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializerSerializerInstance;
        final JavaType javaType;
        final Object objFindContentSerializer;
        TypeSerializer typeSerializerForProperty = _valueTypeSerializer;
        if (null != typeSerializerForProperty) {
            typeSerializerForProperty = typeSerializerForProperty.forProperty(beanProperty);
        }
        if (null != beanProperty) {
            final AnnotationIntrospector annotationIntrospector = serializerProvider.getAnnotationIntrospector();
            final AnnotatedMember member = beanProperty.getMember();
            jsonSerializerSerializerInstance = (null == member || null == (objFindContentSerializer = annotationIntrospector.findContentSerializer(member))) ? null : serializerProvider.serializerInstance(member, objFindContentSerializer);
        }
        final JsonFormat.Value valueFindFormatOverrides = this.findFormatOverrides(serializerProvider, beanProperty, this.handledType());
        final Boolean feature = null != valueFindFormatOverrides ? valueFindFormatOverrides.getFeature(JsonFormat.Feature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED) : null;
        if (null == jsonSerializerSerializerInstance) {
            jsonSerializerSerializerInstance = _elementSerializer;
        }
        JsonSerializer<?> jsonSerializerFindContextualConvertingSerializer = this.findContextualConvertingSerializer(serializerProvider, beanProperty, jsonSerializerSerializerInstance);
        if (null == jsonSerializerFindContextualConvertingSerializer && null != (javaType = this._elementType) && _staticTyping && !javaType.isJavaLangObject()) {
            jsonSerializerFindContextualConvertingSerializer = serializerProvider.findContentValueSerializer(_elementType, beanProperty);
        }
        return (jsonSerializerFindContextualConvertingSerializer == _elementSerializer && beanProperty == _property && _valueTypeSerializer == typeSerializerForProperty && Objects.equals(_unwrapSingle, feature)) ? this : this.withResolved(beanProperty, typeSerializerForProperty, jsonSerializerFindContextualConvertingSerializer, feature);
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public JavaType getContentType() {
        return _elementType;
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public JsonSerializer<?> getContentSerializer() {
        return _elementSerializer;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void serialize(final T t, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        if (serializerProvider.isEnabled(SerializationFeature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED) && this.hasSingleElement(t)) {
            this.serializeContents(t, jsonGenerator, serializerProvider);
            return;
        }
        jsonGenerator.writeStartArray(t);
        this.serializeContents(t, jsonGenerator, serializerProvider);
        jsonGenerator.writeEndArray();
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public void serializeWithType(final T t, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider, final TypeSerializer typeSerializer) throws IOException {
        final WritableTypeId writableTypeIdWriteTypePrefix = typeSerializer.writeTypePrefix(jsonGenerator, typeSerializer.typeId(t, JsonToken.START_ARRAY));
        jsonGenerator.setCurrentValue(t);
        this.serializeContents(t, jsonGenerator, serializerProvider);
        typeSerializer.writeTypeSuffix(jsonGenerator, writableTypeIdWriteTypePrefix);
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.jsonschema.SchemaAware
    public JsonNode getSchema(final SerializerProvider serializerProvider, final Type type) throws JsonMappingException {
        final ObjectNode objectNodeCreateSchemaNode = this.createSchemaNode("array", true);
        final Object obj = _elementSerializer;
        if (null != obj) {
            JsonNode schema = obj instanceof SchemaAware ? ((SchemaAware) obj).getSchema(serializerProvider, null) : null;
            if (null == schema) {
                schema = JsonSchema.getDefaultSchemaNode();
            }
            objectNodeCreateSchemaNode.set(FirebaseAnalytics.Param.ITEMS, schema);
        }
        return objectNodeCreateSchemaNode;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void acceptJsonFormatVisitor(final JsonFormatVisitorWrapper jsonFormatVisitorWrapper, final JavaType javaType) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializerFindContentValueSerializer = _elementSerializer;
        if (null == jsonSerializerFindContentValueSerializer && null != this._elementType) {
            jsonSerializerFindContentValueSerializer = jsonFormatVisitorWrapper.getProvider().findContentValueSerializer(_elementType, _property);
        }
        this.visitArrayFormat(jsonFormatVisitorWrapper, javaType, jsonSerializerFindContentValueSerializer, _elementType);
    }

    protected final JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final Class<?> cls, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddSecondarySerializer = propertySerializerMap.findAndAddSecondarySerializer(cls, serializerProvider, _property);
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddSecondarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddSecondarySerializer.serializer();
    }

    protected final JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final JavaType javaType, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddSecondarySerializer = propertySerializerMap.findAndAddSecondarySerializer(javaType, serializerProvider, _property);
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddSecondarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddSecondarySerializer.serializer();
    }
}
