package com.fasterxml.jackson.databind.ser.std;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.lifecycle.LifecycleKtExternalSyntheticBackportWithForwarding0;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonValueFormat;
import com.fasterxml.jackson.databind.ser.ContextualSerializer;
import com.fasterxml.jackson.databind.util.StdDateFormat;

import java.io.IOException;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;
import java.util.concurrent.atomic.AtomicReference;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public abstract class DateTimeSerializerBase<T> extends StdScalarSerializer<T> implements ContextualSerializer {
    protected final DateFormat _customFormat;
    protected final AtomicReference<DateFormat> _reusedCustomFormat;
    protected final Boolean _useTimestamp;

    protected abstract long _timestamp(T t);

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public boolean isEmpty(final SerializerProvider serializerProvider, final T t) {
        return false;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public abstract void serialize(T t, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException;

    /* renamed from: withFormat */
    public abstract DateTimeSerializerBase<T> withFormat2(Boolean bool, DateFormat dateFormat);

    protected DateTimeSerializerBase(final Class<T> cls, final Boolean bool, final DateFormat dateFormat) {
        super(cls);
        _useTimestamp = bool;
        _customFormat = dateFormat;
        _reusedCustomFormat = null == dateFormat ? null : new AtomicReference<>();
    }

    @Override // com.fasterxml.jackson.databind.ser.ContextualSerializer
    public JsonSerializer<?> createContextual(final SerializerProvider serializerProvider, final BeanProperty beanProperty) throws JsonMappingException {
        final SimpleDateFormat simpleDateFormat;
        final Locale locale;
        final JsonFormat.Value valueFindFormatOverrides = this.findFormatOverrides(serializerProvider, beanProperty, this.handledType());
        if (null == valueFindFormatOverrides) {
            return this;
        }
        final JsonFormat.Shape shape = valueFindFormatOverrides.getShape();
        if (shape.isNumeric()) {
            return this.withFormat2(Boolean.TRUE, null);
        }
        if (valueFindFormatOverrides.hasPattern()) {
            if (valueFindFormatOverrides.hasLocale()) {
                locale = valueFindFormatOverrides.getLocale();
            } else {
                locale = serializerProvider.getLocale();
            }
            final SimpleDateFormat simpleDateFormat2 = new SimpleDateFormat(valueFindFormatOverrides.getPattern(), locale);
            simpleDateFormat2.setTimeZone(valueFindFormatOverrides.hasTimeZone() ? valueFindFormatOverrides.getTimeZone() : serializerProvider.getTimeZone());
            return this.withFormat2(Boolean.FALSE, simpleDateFormat2);
        }
        final boolean zHasLocale = valueFindFormatOverrides.hasLocale();
        final boolean zHasTimeZone = valueFindFormatOverrides.hasTimeZone();
        final boolean z = JsonFormat.Shape.STRING == shape;
        if (!zHasLocale && !zHasTimeZone && !z) {
            return this;
        }
        final DateFormat dateFormat = serializerProvider.getConfig().getDateFormat();
        if (dateFormat instanceof StdDateFormat stdDateFormatWithTimeZone) {
            if (valueFindFormatOverrides.hasLocale()) {
                stdDateFormatWithTimeZone = stdDateFormatWithTimeZone.withLocale(valueFindFormatOverrides.getLocale());
            }
            if (valueFindFormatOverrides.hasTimeZone()) {
                stdDateFormatWithTimeZone = stdDateFormatWithTimeZone.withTimeZone(valueFindFormatOverrides.getTimeZone());
            }
            return this.withFormat2(Boolean.FALSE, stdDateFormatWithTimeZone);
        }
        if (!(dateFormat instanceof SimpleDateFormat)) {
            serializerProvider.reportBadDefinition((Class<?>) this.handledType(), String.format("Configured `DateFormat` (%s) not a `SimpleDateFormat`; cannot configure `Locale` or `TimeZone`", dateFormat.getClass().getName()));
        }
        final SimpleDateFormat simpleDateFormat3 = (SimpleDateFormat) dateFormat;
        if (zHasLocale) {
            simpleDateFormat = new SimpleDateFormat(simpleDateFormat3.toPattern(), valueFindFormatOverrides.getLocale());
        } else {
            simpleDateFormat = (SimpleDateFormat) simpleDateFormat3.clone();
        }
        final TimeZone timeZone = valueFindFormatOverrides.getTimeZone();
        if (null != timeZone && !timeZone.equals(simpleDateFormat.getTimeZone())) {
            simpleDateFormat.setTimeZone(timeZone);
        }
        return this.withFormat2(Boolean.FALSE, simpleDateFormat);
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdScalarSerializer, com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.jsonschema.SchemaAware
    public JsonNode getSchema(final SerializerProvider serializerProvider, final Type type) {
        return this.createSchemaNode(this._asTimestamp(serializerProvider) ? "number" : TypedValues.Custom.S_STRING, true);
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdScalarSerializer, com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void acceptJsonFormatVisitor(final JsonFormatVisitorWrapper jsonFormatVisitorWrapper, final JavaType javaType) throws JsonMappingException {
        this._acceptJsonFormatVisitor(jsonFormatVisitorWrapper, javaType, this._asTimestamp(jsonFormatVisitorWrapper.getProvider()));
    }

    protected boolean _asTimestamp(final SerializerProvider serializerProvider) {
        final Boolean bool = _useTimestamp;
        if (null != bool) {
            return bool.booleanValue();
        }
        if (null != this._customFormat) {
            return false;
        }
        if (null != serializerProvider) {
            return serializerProvider.isEnabled(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        }
        throw new IllegalArgumentException("Null SerializerProvider passed for " + this.handledType().getName());
    }

    protected void _acceptJsonFormatVisitor(final JsonFormatVisitorWrapper jsonFormatVisitorWrapper, final JavaType javaType, final boolean z) throws JsonMappingException {
        if (z) {
            this.visitIntFormat(jsonFormatVisitorWrapper, javaType, JsonParser.NumberType.LONG, JsonValueFormat.UTC_MILLISEC);
        } else {
            this.visitStringFormat(jsonFormatVisitorWrapper, javaType, JsonValueFormat.DATE_TIME);
        }
    }

    protected void _serializeAsString(final Date date, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        if (null == this._customFormat) {
            serializerProvider.defaultSerializeDateValue(date, jsonGenerator);
            return;
        }
        DateFormat andSet = _reusedCustomFormat.getAndSet(null);
        if (null == andSet) {
            andSet = (DateFormat) _customFormat.clone();
        }
        jsonGenerator.writeString(andSet.format(date));
        LifecycleKtExternalSyntheticBackportWithForwarding0.m212m(_reusedCustomFormat, null, andSet);
    }
}
