package com.fasterxml.jackson.databind.ser.std;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.JacksonStdImpl;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.ser.ContainerSerializer;
import com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap;

import java.io.IOException;
import java.util.Objects;

// Class generated by  decompiler (1.5.3)
@JacksonStdImpl
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class ObjectArraySerializer extends ArraySerializerBase<Object[]> {
    protected PropertySerializerMap _dynamicSerializers;
    protected JsonSerializer<Object> _elementSerializer;
    protected final JavaType _elementType;
    protected final boolean _staticTyping;
    protected final TypeSerializer _valueTypeSerializer;

    public ObjectArraySerializer(final JavaType javaType, final boolean z, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer) {
        super(Object[].class);
        _elementType = javaType;
        _staticTyping = z;
        _valueTypeSerializer = typeSerializer;
        _dynamicSerializers = PropertySerializerMap.emptyForProperties();
        _elementSerializer = jsonSerializer;
    }

    public ObjectArraySerializer(final ObjectArraySerializer objectArraySerializer, final TypeSerializer typeSerializer) {
        super(objectArraySerializer);
        _elementType = objectArraySerializer._elementType;
        _valueTypeSerializer = typeSerializer;
        _staticTyping = objectArraySerializer._staticTyping;
        _dynamicSerializers = objectArraySerializer._dynamicSerializers;
        _elementSerializer = objectArraySerializer._elementSerializer;
    }

    public ObjectArraySerializer(final ObjectArraySerializer objectArraySerializer, final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer, final Boolean bool) {
        super(objectArraySerializer, beanProperty, bool);
        _elementType = objectArraySerializer._elementType;
        _valueTypeSerializer = typeSerializer;
        _staticTyping = objectArraySerializer._staticTyping;
        _dynamicSerializers = PropertySerializerMap.emptyForProperties();
        _elementSerializer = jsonSerializer;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.ArraySerializerBase
    public JsonSerializer<?> _withResolved(final BeanProperty beanProperty, final Boolean bool) {
        return new ObjectArraySerializer(this, beanProperty, _valueTypeSerializer, _elementSerializer, bool);
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public ContainerSerializer<?> _withValueTypeSerializer(final TypeSerializer typeSerializer) {
        return new ObjectArraySerializer(_elementType, _staticTyping, typeSerializer, _elementSerializer);
    }

    public ObjectArraySerializer withResolved(final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer, final Boolean bool) {
        return (_property == beanProperty && jsonSerializer == _elementSerializer && _valueTypeSerializer == typeSerializer && Objects.equals(_unwrapSingle, bool)) ? this : new ObjectArraySerializer(this, beanProperty, typeSerializer, jsonSerializer, bool);
    }


    /*  WARN: Removed duplicated region for block: B:12:0x0020  */
    @Override // com.fasterxml.jackson.databind.ser.std.ArraySerializerBase, com.fasterxml.jackson.databind.ser.ContextualSerializer
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public JsonSerializer<?> createContextual(final SerializerProvider serializerProvider, final BeanProperty beanProperty) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializerSerializerInstance;
        final JavaType javaType;
        final Object objFindContentSerializer;
        TypeSerializer typeSerializerForProperty = _valueTypeSerializer;
        if (null != typeSerializerForProperty) {
            typeSerializerForProperty = typeSerializerForProperty.forProperty(beanProperty);
        }
        if (null != beanProperty) {
            final AnnotatedMember member = beanProperty.getMember();
            jsonSerializerSerializerInstance = (null == member || null == (objFindContentSerializer = serializerProvider.getAnnotationIntrospector().findContentSerializer(member))) ? null : serializerProvider.serializerInstance(member, objFindContentSerializer);
        }
        final JsonFormat.Value valueFindFormatOverrides = this.findFormatOverrides(serializerProvider, beanProperty, this.handledType());
        final Boolean feature = null != valueFindFormatOverrides ? valueFindFormatOverrides.getFeature(JsonFormat.Feature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED) : null;
        if (null == jsonSerializerSerializerInstance) {
            jsonSerializerSerializerInstance = _elementSerializer;
        }
        JsonSerializer<?> jsonSerializerFindContextualConvertingSerializer = this.findContextualConvertingSerializer(serializerProvider, beanProperty, jsonSerializerSerializerInstance);
        if (null == jsonSerializerFindContextualConvertingSerializer && null != (javaType = this._elementType) && _staticTyping && !javaType.isJavaLangObject()) {
            jsonSerializerFindContextualConvertingSerializer = serializerProvider.findContentValueSerializer(_elementType, beanProperty);
        }
        return this.withResolved(beanProperty, typeSerializerForProperty, jsonSerializerFindContextualConvertingSerializer, feature);
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public JavaType getContentType() {
        return _elementType;
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public JsonSerializer<?> getContentSerializer() {
        return _elementSerializer;
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public boolean isEmpty(final SerializerProvider serializerProvider, final Object[] objArr) {
        return 0 == objArr.length;
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public boolean hasSingleElement(final Object[] objArr) {
        return 1 == objArr.length;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.ArraySerializerBase, com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public final void serialize(final Object[] objArr, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        final int length = objArr.length;
        if (1 == length && ((null == this._unwrapSingle && serializerProvider.isEnabled(SerializationFeature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED)) || _unwrapSingle == Boolean.TRUE)) {
            this.serializeContents(objArr, jsonGenerator, serializerProvider);
            return;
        }
        jsonGenerator.writeStartArray(objArr, length);
        this.serializeContents(objArr, jsonGenerator, serializerProvider);
        jsonGenerator.writeEndArray();
    }

    @Override // com.fasterxml.jackson.databind.ser.std.ArraySerializerBase
    public void serializeContents(final Object[] objArr, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        final int length = objArr.length;
        if (0 == length) {
            return;
        }
        final JsonSerializer<Object> jsonSerializer = _elementSerializer;
        if (null != jsonSerializer) {
            this.serializeContentsUsing(objArr, jsonGenerator, serializerProvider, jsonSerializer);
            return;
        }
        if (null != this._valueTypeSerializer) {
            this.serializeTypedContents(objArr, jsonGenerator, serializerProvider);
            return;
        }
        int i2 = 0;
        Object obj = null;
        try {
            final PropertySerializerMap propertySerializerMap = _dynamicSerializers;
            while (i2 < length) {
                obj = objArr[i2];
                if (null == obj) {
                    serializerProvider.defaultSerializeNull(jsonGenerator);
                } else {
                    final Class<?> cls = obj.getClass();
                    JsonSerializer<Object> jsonSerializerSerializerFor = propertySerializerMap.serializerFor(cls);
                    if (null == jsonSerializerSerializerFor) {
                        if (_elementType.hasGenericTypes()) {
                            jsonSerializerSerializerFor = this._findAndAddDynamic(propertySerializerMap, serializerProvider.constructSpecializedType(_elementType, cls), serializerProvider);
                        } else {
                            jsonSerializerSerializerFor = this._findAndAddDynamic(propertySerializerMap, cls, serializerProvider);
                        }
                    }
                    jsonSerializerSerializerFor.serialize(obj, jsonGenerator, serializerProvider);
                }
                i2++;
            }
        } catch (final Exception e2) {
            this.wrapAndThrow(serializerProvider, e2, obj, i2);
        }
    }

    public void serializeContentsUsing(final Object[] objArr, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider, final JsonSerializer<Object> jsonSerializer) throws IOException {
        final int length = objArr.length;
        final TypeSerializer typeSerializer = _valueTypeSerializer;
        Object obj = null;
        for (int i2 = 0; i2 < length; i2++) {
            try {
                obj = objArr[i2];
                if (null == obj) {
                    serializerProvider.defaultSerializeNull(jsonGenerator);
                } else if (null == typeSerializer) {
                    jsonSerializer.serialize(obj, jsonGenerator, serializerProvider);
                } else {
                    jsonSerializer.serializeWithType(obj, jsonGenerator, serializerProvider, typeSerializer);
                }
            } catch (final Exception e2) {
                this.wrapAndThrow(serializerProvider, e2, obj, i2);
                return;
            }
        }
    }

    public void serializeTypedContents(final Object[] objArr, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        final int length = objArr.length;
        final TypeSerializer typeSerializer = _valueTypeSerializer;
        int i2 = 0;
        Object obj = null;
        try {
            final PropertySerializerMap propertySerializerMap = _dynamicSerializers;
            while (i2 < length) {
                obj = objArr[i2];
                if (null == obj) {
                    serializerProvider.defaultSerializeNull(jsonGenerator);
                } else {
                    final Class<?> cls = obj.getClass();
                    JsonSerializer<Object> jsonSerializerSerializerFor = propertySerializerMap.serializerFor(cls);
                    if (null == jsonSerializerSerializerFor) {
                        jsonSerializerSerializerFor = this._findAndAddDynamic(propertySerializerMap, cls, serializerProvider);
                    }
                    jsonSerializerSerializerFor.serializeWithType(obj, jsonGenerator, serializerProvider, typeSerializer);
                }
                i2++;
            }
        } catch (final Exception e2) {
            this.wrapAndThrow(serializerProvider, e2, obj, i2);
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void acceptJsonFormatVisitor(final JsonFormatVisitorWrapper jsonFormatVisitorWrapper, final JavaType javaType) throws JsonMappingException {
        jsonFormatVisitorWrapper.expectArrayFormat(javaType);
    }

    protected final JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final Class<?> cls, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddSecondarySerializer = propertySerializerMap.findAndAddSecondarySerializer(cls, serializerProvider, _property);
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddSecondarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddSecondarySerializer.serializer();
    }

    protected final JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final JavaType javaType, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddSecondarySerializer = propertySerializerMap.findAndAddSecondarySerializer(javaType, serializerProvider, _property);
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddSecondarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddSecondarySerializer.serializer();
    }
}
