package com.fasterxml.jackson.databind.ser.std;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.ser.ContextualSerializer;
import com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap;
import com.fasterxml.jackson.databind.type.ReferenceType;
import com.fasterxml.jackson.databind.util.ArrayBuilders;
import com.fasterxml.jackson.databind.util.BeanUtil;
import com.fasterxml.jackson.databind.util.NameTransformer;

import java.io.IOException;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public abstract class ReferenceTypeSerializer<T> extends StdSerializer<T> implements ContextualSerializer {
    public static final Object MARKER_FOR_EMPTY = JsonInclude.Include.NON_EMPTY;
    private static final long serialVersionUID = 1;
    protected transient PropertySerializerMap _dynamicSerializers;
    protected final BeanProperty _property;
    protected final JavaType _referredType;
    protected final boolean _suppressNulls;
    protected final Object _suppressableValue;
    protected final NameTransformer _unwrapper;
    protected final JsonSerializer<Object> _valueSerializer;
    protected final TypeSerializer _valueTypeSerializer;

    protected abstract Object _getReferenced(T t);

    protected abstract Object _getReferencedIfPresent(T t);

    protected abstract boolean _isValuePresent(T t);

    public abstract ReferenceTypeSerializer<T> withContentInclusion(Object obj, boolean z);

    protected abstract ReferenceTypeSerializer<T> withResolved(BeanProperty beanProperty, TypeSerializer typeSerializer, JsonSerializer<?> jsonSerializer, NameTransformer nameTransformer);

    protected ReferenceTypeSerializer(final ReferenceType referenceType, final boolean z, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer) {
        super(referenceType);
        _referredType = referenceType.getReferencedType();
        _property = null;
        _valueTypeSerializer = typeSerializer;
        _valueSerializer = jsonSerializer;
        _unwrapper = null;
        _suppressableValue = null;
        _suppressNulls = false;
        _dynamicSerializers = PropertySerializerMap.emptyForProperties();
    }

    protected ReferenceTypeSerializer(final ReferenceTypeSerializer<?> referenceTypeSerializer, final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer, final NameTransformer nameTransformer, final Object obj, final boolean z) {
        super(referenceTypeSerializer);
        _referredType = referenceTypeSerializer._referredType;
        _dynamicSerializers = PropertySerializerMap.emptyForProperties();
        _property = beanProperty;
        _valueTypeSerializer = typeSerializer;
        _valueSerializer = jsonSerializer;
        _unwrapper = nameTransformer;
        _suppressableValue = obj;
        _suppressNulls = z;
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public JsonSerializer<T> unwrappingSerializer(NameTransformer nameTransformer) {
        JsonSerializer<?> jsonSerializerUnwrappingSerializer = _valueSerializer;
        if (null != jsonSerializerUnwrappingSerializer && (jsonSerializerUnwrappingSerializer = jsonSerializerUnwrappingSerializer.unwrappingSerializer(nameTransformer)) == _valueSerializer) {
            return this;
        }
        final NameTransformer nameTransformer2 = _unwrapper;
        if (null != nameTransformer2) {
            nameTransformer = NameTransformer.chainedTransformer(nameTransformer, nameTransformer2);
        }
        return (_valueSerializer == jsonSerializerUnwrappingSerializer && _unwrapper == nameTransformer) ? this : this.withResolved(_property, _valueTypeSerializer, jsonSerializerUnwrappingSerializer, nameTransformer);
    }

    @Override // com.fasterxml.jackson.databind.ser.ContextualSerializer
    public JsonSerializer<?> createContextual(final SerializerProvider serializerProvider, final BeanProperty beanProperty) throws JsonMappingException {
        final JsonInclude.Value valueFindPropertyInclusion;
        final JsonInclude.Include contentInclusion;
        Object defaultValue;
        TypeSerializer typeSerializerForProperty = _valueTypeSerializer;
        if (null != typeSerializerForProperty) {
            typeSerializerForProperty = typeSerializerForProperty.forProperty(beanProperty);
        }
        JsonSerializer<?> jsonSerializerFindAnnotatedContentSerializer = this.findAnnotatedContentSerializer(serializerProvider, beanProperty);
        if (null == jsonSerializerFindAnnotatedContentSerializer) {
            jsonSerializerFindAnnotatedContentSerializer = _valueSerializer;
            if (null == jsonSerializerFindAnnotatedContentSerializer) {
                if (this._useStatic(serializerProvider, beanProperty, _referredType)) {
                    jsonSerializerFindAnnotatedContentSerializer = this._findSerializer(serializerProvider, _referredType, beanProperty);
                }
            } else {
                jsonSerializerFindAnnotatedContentSerializer = serializerProvider.handlePrimaryContextualization(jsonSerializerFindAnnotatedContentSerializer, beanProperty);
            }
        }
        final ReferenceTypeSerializer<T> referenceTypeSerializerWithResolved = (_property == beanProperty && _valueTypeSerializer == typeSerializerForProperty && _valueSerializer == jsonSerializerFindAnnotatedContentSerializer) ? this : this.withResolved(beanProperty, typeSerializerForProperty, jsonSerializerFindAnnotatedContentSerializer, _unwrapper);
        if (null == beanProperty || null == (valueFindPropertyInclusion = beanProperty.findPropertyInclusion(serializerProvider.getConfig(), handledType())) || JsonInclude.Include.USE_DEFAULTS == (contentInclusion = valueFindPropertyInclusion.getContentInclusion())) {
            return referenceTypeSerializerWithResolved;
        }
        final int i2 = C12221.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[contentInclusion.ordinal()];
        boolean zIncludeFilterSuppressNulls = true;
        if (1 != i2) {
            defaultValue = null;
            if (2 != i2) {
                if (3 == i2) {
                    defaultValue = ReferenceTypeSerializer.MARKER_FOR_EMPTY;
                } else if (4 == i2) {
                    defaultValue = serializerProvider.includeFilterInstance(null, valueFindPropertyInclusion.getContentFilter());
                    if (null != defaultValue) {
                        zIncludeFilterSuppressNulls = serializerProvider.includeFilterSuppressNulls(defaultValue);
                    }
                } else if (5 != i2) {
                    zIncludeFilterSuppressNulls = false;
                }
            } else if (_referredType.isReferenceType()) {
                defaultValue = ReferenceTypeSerializer.MARKER_FOR_EMPTY;
            }
        } else {
            defaultValue = BeanUtil.getDefaultValue(_referredType);
            if (null != defaultValue && defaultValue.getClass().isArray()) {
                defaultValue = ArrayBuilders.getArrayComparator(defaultValue);
            }
        }
        return (_suppressableValue == defaultValue && _suppressNulls == zIncludeFilterSuppressNulls) ? referenceTypeSerializerWithResolved : referenceTypeSerializerWithResolved.withContentInclusion(defaultValue, zIncludeFilterSuppressNulls);
    }

    /* renamed from: com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer1 */
    enum C12221 {
        ;
        static final int[] SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude;

        static {
            final int[] iArr = new int[JsonInclude.Include.values().length];
            SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude = iArr;
            try {
                iArr[JsonInclude.Include.NON_DEFAULT.ordinal()] = 1;
            } catch (final NoSuchFieldError unused) {
            }
            try {
                C12221.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.NON_ABSENT.ordinal()] = 2;
            } catch (final NoSuchFieldError unused2) {
            }
            try {
                C12221.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.NON_EMPTY.ordinal()] = 3;
            } catch (final NoSuchFieldError unused3) {
            }
            try {
                C12221.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.CUSTOM.ordinal()] = 4;
            } catch (final NoSuchFieldError unused4) {
            }
            try {
                C12221.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.NON_NULL.ordinal()] = 5;
            } catch (final NoSuchFieldError unused5) {
            }
            try {
                C12221.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.ALWAYS.ordinal()] = 6;
            } catch (final NoSuchFieldError unused6) {
            }
        }
    }

    protected boolean _useStatic(final SerializerProvider serializerProvider, final BeanProperty beanProperty, final JavaType javaType) {
        if (javaType.isJavaLangObject()) {
            return false;
        }
        if (javaType.isFinal() || javaType.useStaticType()) {
            return true;
        }
        final AnnotationIntrospector annotationIntrospector = serializerProvider.getAnnotationIntrospector();
        if (null != annotationIntrospector && null != beanProperty && null != beanProperty.getMember()) {
            final JsonSerialize.Typing typingFindSerializationTyping = annotationIntrospector.findSerializationTyping(beanProperty.getMember());
            if (JsonSerialize.Typing.STATIC == typingFindSerializationTyping) {
                return true;
            }
            if (JsonSerialize.Typing.DYNAMIC == typingFindSerializationTyping) {
                return false;
            }
        }
        return serializerProvider.isEnabled(MapperFeature.USE_STATIC_TYPING);
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public boolean isEmpty(final SerializerProvider serializerProvider, final T t) {
        if (!this._isValuePresent(t)) {
            return true;
        }
        final Object obj_getReferenced = this._getReferenced(t);
        if (null == obj_getReferenced) {
            return _suppressNulls;
        }
        if (null == this._suppressableValue) {
            return false;
        }
        JsonSerializer<Object> jsonSerializer_findCachedSerializer = _valueSerializer;
        if (null == jsonSerializer_findCachedSerializer) {
            try {
                jsonSerializer_findCachedSerializer = this._findCachedSerializer(serializerProvider, obj_getReferenced.getClass());
            } catch (final JsonMappingException e2) {
                throw new RuntimeJsonMappingException(e2);
            }
        }
        final Object obj = _suppressableValue;
        if (ReferenceTypeSerializer.MARKER_FOR_EMPTY == obj) {
            return jsonSerializer_findCachedSerializer.isEmpty(serializerProvider, obj_getReferenced);
        }
        return obj.equals(obj_getReferenced);
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public boolean isUnwrappingSerializer() {
        return null != this._unwrapper;
    }

    public JavaType getReferredType() {
        return _referredType;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void serialize(final T t, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        final Object obj_getReferencedIfPresent = this._getReferencedIfPresent(t);
        if (null == obj_getReferencedIfPresent) {
            if (null == this._unwrapper) {
                serializerProvider.defaultSerializeNull(jsonGenerator);
                return;
            }
            return;
        }
        JsonSerializer<Object> jsonSerializer_findCachedSerializer = _valueSerializer;
        if (null == jsonSerializer_findCachedSerializer) {
            jsonSerializer_findCachedSerializer = this._findCachedSerializer(serializerProvider, obj_getReferencedIfPresent.getClass());
        }
        final TypeSerializer typeSerializer = _valueTypeSerializer;
        if (null != typeSerializer) {
            jsonSerializer_findCachedSerializer.serializeWithType(obj_getReferencedIfPresent, jsonGenerator, serializerProvider, typeSerializer);
        } else {
            jsonSerializer_findCachedSerializer.serialize(obj_getReferencedIfPresent, jsonGenerator, serializerProvider);
        }
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public void serializeWithType(final T t, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider, final TypeSerializer typeSerializer) throws IOException {
        final Object obj_getReferencedIfPresent = this._getReferencedIfPresent(t);
        if (null == obj_getReferencedIfPresent) {
            if (null == this._unwrapper) {
                serializerProvider.defaultSerializeNull(jsonGenerator);
            }
        } else {
            JsonSerializer<Object> jsonSerializer_findCachedSerializer = _valueSerializer;
            if (null == jsonSerializer_findCachedSerializer) {
                jsonSerializer_findCachedSerializer = this._findCachedSerializer(serializerProvider, obj_getReferencedIfPresent.getClass());
            }
            jsonSerializer_findCachedSerializer.serializeWithType(obj_getReferencedIfPresent, jsonGenerator, serializerProvider, typeSerializer);
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void acceptJsonFormatVisitor(final JsonFormatVisitorWrapper jsonFormatVisitorWrapper, final JavaType javaType) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializer_findSerializer = _valueSerializer;
        if (null == jsonSerializer_findSerializer) {
            jsonSerializer_findSerializer = this._findSerializer(jsonFormatVisitorWrapper.getProvider(), _referredType, _property);
            final NameTransformer nameTransformer = _unwrapper;
            if (null != nameTransformer) {
                jsonSerializer_findSerializer = jsonSerializer_findSerializer.unwrappingSerializer(nameTransformer);
            }
        }
        jsonSerializer_findSerializer.acceptJsonFormatVisitor(jsonFormatVisitorWrapper, _referredType);
    }

    private final JsonSerializer<Object> _findCachedSerializer(final SerializerProvider serializerProvider, final Class<?> cls) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializerFindPrimaryPropertySerializer;
        final JsonSerializer<Object> jsonSerializerSerializerFor = _dynamicSerializers.serializerFor(cls);
        if (null != jsonSerializerSerializerFor) {
            return jsonSerializerSerializerFor;
        }
        if (_referredType.hasGenericTypes()) {
            jsonSerializerFindPrimaryPropertySerializer = serializerProvider.findPrimaryPropertySerializer(serializerProvider.constructSpecializedType(_referredType, cls), _property);
        } else {
            jsonSerializerFindPrimaryPropertySerializer = serializerProvider.findPrimaryPropertySerializer(cls, _property);
        }
        final NameTransformer nameTransformer = _unwrapper;
        if (null != nameTransformer) {
            jsonSerializerFindPrimaryPropertySerializer = jsonSerializerFindPrimaryPropertySerializer.unwrappingSerializer(nameTransformer);
        }
        final JsonSerializer<Object> jsonSerializer = jsonSerializerFindPrimaryPropertySerializer;
        _dynamicSerializers = _dynamicSerializers.newWith(cls, jsonSerializer);
        return jsonSerializer;
    }

    private final JsonSerializer<Object> _findSerializer(final SerializerProvider serializerProvider, final JavaType javaType, final BeanProperty beanProperty) throws JsonMappingException {
        return serializerProvider.findPrimaryPropertySerializer(javaType, beanProperty);
    }
}
