package com.fasterxml.jackson.databind.ser.std;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonArrayFormatVisitor;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.ser.ContextualSerializer;
import com.google.firebase.analytics.FirebaseAnalytics;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.Collection;
import java.util.Objects;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public abstract class StaticListSerializerBase<T extends Collection<?>> extends StdSerializer<T> implements ContextualSerializer {
    protected final Boolean _unwrapSingle;

    public abstract JsonSerializer<?> _withResolved(BeanProperty beanProperty, Boolean bool);

    protected abstract void acceptContentVisitor(JsonArrayFormatVisitor jsonArrayFormatVisitor) throws JsonMappingException;

    protected abstract JsonNode contentSchema();

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public abstract void serializeWithType(T t, JsonGenerator jsonGenerator, SerializerProvider serializerProvider, TypeSerializer typeSerializer) throws IOException;

    protected StaticListSerializerBase(final Class<?> cls) {
        super(cls, false);
        _unwrapSingle = null;
    }

    protected StaticListSerializerBase(final StaticListSerializerBase<?> staticListSerializerBase, final Boolean bool) {
        super(staticListSerializerBase);
        _unwrapSingle = bool;
    }

    /*  WARN: Removed duplicated region for block: B:9:0x0018  */
    @Override // com.fasterxml.jackson.databind.ser.ContextualSerializer
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public JsonSerializer<?> createContextual(final SerializerProvider serializerProvider, final BeanProperty beanProperty) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializerSerializerInstance;
        final Object objFindContentSerializer;
        if (null != beanProperty) {
            final AnnotationIntrospector annotationIntrospector = serializerProvider.getAnnotationIntrospector();
            final AnnotatedMember member = beanProperty.getMember();
            jsonSerializerSerializerInstance = (null == member || null == (objFindContentSerializer = annotationIntrospector.findContentSerializer(member))) ? null : serializerProvider.serializerInstance(member, objFindContentSerializer);
        }
        final JsonFormat.Value valueFindFormatOverrides = this.findFormatOverrides(serializerProvider, beanProperty, this.handledType());
        final Boolean feature = null != valueFindFormatOverrides ? valueFindFormatOverrides.getFeature(JsonFormat.Feature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED) : null;
        JsonSerializer<?> jsonSerializerFindContextualConvertingSerializer = this.findContextualConvertingSerializer(serializerProvider, beanProperty, jsonSerializerSerializerInstance);
        if (null == jsonSerializerFindContextualConvertingSerializer) {
            jsonSerializerFindContextualConvertingSerializer = serializerProvider.findContentValueSerializer(String.class, beanProperty);
        }
        if (this.isDefaultSerializer(jsonSerializerFindContextualConvertingSerializer)) {
            return Objects.equals(feature, _unwrapSingle) ? this : this._withResolved(beanProperty, feature);
        }
        return new CollectionSerializer(serializerProvider.constructType(String.class), true, null, jsonSerializerFindContextualConvertingSerializer);
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public boolean isEmpty(final SerializerProvider serializerProvider, final T t) {
        return null == t || 0 == t.size();
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.jsonschema.SchemaAware
    public JsonNode getSchema(final SerializerProvider serializerProvider, final Type type) {
        return this.createSchemaNode("array", true).set(FirebaseAnalytics.Param.ITEMS, this.contentSchema());
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void acceptJsonFormatVisitor(final JsonFormatVisitorWrapper jsonFormatVisitorWrapper, final JavaType javaType) throws JsonMappingException {
        jsonFormatVisitorWrapper.expectArrayFormat(javaType);
    }
}
