package com.fasterxml.jackson.databind.jsontype;

import java.io.Serializable;
import java.util.Objects;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class NamedType implements Serializable {
    private static final long serialVersionUID = 1;
    private final Class<?> _class;
    private final int _hashCode;
    private String _name;

    public NamedType(final Class<?> cls) {
        this(cls, null);
    }

    public NamedType(final Class<?> cls, final String str) {
        _class = cls;
        _hashCode = cls.getName().hashCode() + (null == str ? 0 : str.hashCode());
        this.setName(str);
    }

    public Class<?> getType() {
        return _class;
    }

    public String getName() {
        return _name;
    }

    public void setName(String str) {
        if (null == str || str.isEmpty()) {
            str = null;
        }
        _name = str;
    }

    public boolean hasName() {
        return null != this._name;
    }

    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (null == obj || NamedType.class != obj.getClass()) {
            return false;
        }
        final NamedType namedType = (NamedType) obj;
        return _class == namedType._class && Objects.equals(_name, namedType._name);
    }

    public int hashCode() {
        return _hashCode;
    }

    public String toString() {
        final String str;
        final StringBuilder sb = new StringBuilder();
        sb.append("[NamedType, class ");
        sb.append(_class.getName());
        sb.append(", name: ");
        if (null == this._name) {
            str = "null";
        } else {
            str = "'" + _name + "'";
        }
        sb.append(str);
        sb.append("]");
        return sb.toString();
    }
}
