package com.fasterxml.jackson.databind.ser.impl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.WritableTypeId;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.JacksonStdImpl;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.ser.ContainerSerializer;
import com.fasterxml.jackson.databind.ser.ContextualSerializer;
import com.fasterxml.jackson.databind.util.ArrayBuilders;
import com.fasterxml.jackson.databind.util.BeanUtil;

import java.io.IOException;
import java.util.Map;

// Class generated by  decompiler (1.5.3)
@JacksonStdImpl
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class MapEntrySerializer extends ContainerSerializer<Map.Entry<?, ?>> implements ContextualSerializer {
    public static final Object MARKER_FOR_EMPTY = JsonInclude.Include.NON_EMPTY;
    protected PropertySerializerMap _dynamicValueSerializers;
    protected final JavaType _entryType;
    protected JsonSerializer<Object> _keySerializer;
    protected final JavaType _keyType;
    protected final BeanProperty _property;
    protected final boolean _suppressNulls;
    protected final Object _suppressableValue;
    protected JsonSerializer<Object> _valueSerializer;
    protected final JavaType _valueType;
    protected final boolean _valueTypeIsStatic;
    protected final TypeSerializer _valueTypeSerializer;

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public boolean hasSingleElement(final Map.Entry<?, ?> entry) {
        return true;
    }

    public MapEntrySerializer(final JavaType javaType, final JavaType javaType2, final JavaType javaType3, final boolean z, final TypeSerializer typeSerializer, final BeanProperty beanProperty) {
        super(javaType);
        _entryType = javaType;
        _keyType = javaType2;
        _valueType = javaType3;
        _valueTypeIsStatic = z;
        _valueTypeSerializer = typeSerializer;
        _property = beanProperty;
        _dynamicValueSerializers = PropertySerializerMap.emptyForProperties();
        _suppressableValue = null;
        _suppressNulls = false;
    }

    @Deprecated
    protected MapEntrySerializer(final MapEntrySerializer mapEntrySerializer, final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer, final JsonSerializer<?> jsonSerializer2) {
        this(mapEntrySerializer, beanProperty, typeSerializer, jsonSerializer, jsonSerializer2, mapEntrySerializer._suppressableValue, mapEntrySerializer._suppressNulls);
    }

    protected MapEntrySerializer(final MapEntrySerializer mapEntrySerializer, final BeanProperty beanProperty, final TypeSerializer typeSerializer, final JsonSerializer<?> jsonSerializer, final JsonSerializer<?> jsonSerializer2, final Object obj, final boolean z) {
        super(Map.class, false);
        _entryType = mapEntrySerializer._entryType;
        _keyType = mapEntrySerializer._keyType;
        _valueType = mapEntrySerializer._valueType;
        _valueTypeIsStatic = mapEntrySerializer._valueTypeIsStatic;
        _valueTypeSerializer = mapEntrySerializer._valueTypeSerializer;
        _keySerializer = jsonSerializer;
        _valueSerializer = jsonSerializer2;
        _dynamicValueSerializers = PropertySerializerMap.emptyForProperties();
        _property = mapEntrySerializer._property;
        _suppressableValue = obj;
        _suppressNulls = z;
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public ContainerSerializer<?> _withValueTypeSerializer(final TypeSerializer typeSerializer) {
        return new MapEntrySerializer(this, _property, typeSerializer, _keySerializer, _valueSerializer, _suppressableValue, _suppressNulls);
    }

    public MapEntrySerializer withResolved(final BeanProperty beanProperty, final JsonSerializer<?> jsonSerializer, final JsonSerializer<?> jsonSerializer2, final Object obj, final boolean z) {
        return new MapEntrySerializer(this, beanProperty, _valueTypeSerializer, jsonSerializer, jsonSerializer2, obj, z);
    }

    public MapEntrySerializer withContentInclusion(final Object obj, final boolean z) {
        return (_suppressableValue == obj && _suppressNulls == z) ? this : new MapEntrySerializer(this, _property, _valueTypeSerializer, _keySerializer, _valueSerializer, obj, z);
    }

    @Override // com.fasterxml.jackson.databind.ser.ContextualSerializer
    public JsonSerializer<?> createContextual(final SerializerProvider serializerProvider, final BeanProperty beanProperty) throws JsonMappingException {
        JsonSerializer<Object> jsonSerializerSerializerInstance;
        JsonSerializer<?> jsonSerializerSerializerInstance2;
        final JsonSerializer<?> jsonSerializerHandleSecondaryContextualization;
        Object obj;
        boolean z;
        final JsonInclude.Value valueFindPropertyInclusion;
        final JsonInclude.Include contentInclusion;
        final boolean zIncludeFilterSuppressNulls;
        final AnnotationIntrospector annotationIntrospector = serializerProvider.getAnnotationIntrospector();
        Object defaultValue = null;
        final AnnotatedMember member = null == beanProperty ? null : beanProperty.getMember();
        if (null == member || null == annotationIntrospector) {
            jsonSerializerSerializerInstance = null;
            jsonSerializerSerializerInstance2 = null;
        } else {
            final Object objFindKeySerializer = annotationIntrospector.findKeySerializer(member);
            jsonSerializerSerializerInstance2 = null != objFindKeySerializer ? serializerProvider.serializerInstance(member, objFindKeySerializer) : null;
            final Object objFindContentSerializer = annotationIntrospector.findContentSerializer(member);
            jsonSerializerSerializerInstance = null != objFindContentSerializer ? serializerProvider.serializerInstance(member, objFindContentSerializer) : null;
        }
        if (null == jsonSerializerSerializerInstance) {
            jsonSerializerSerializerInstance = _valueSerializer;
        }
        JsonSerializer<?> jsonSerializerFindContextualConvertingSerializer = this.findContextualConvertingSerializer(serializerProvider, beanProperty, jsonSerializerSerializerInstance);
        if (null == jsonSerializerFindContextualConvertingSerializer && _valueTypeIsStatic && !_valueType.isJavaLangObject()) {
            jsonSerializerFindContextualConvertingSerializer = serializerProvider.findContentValueSerializer(_valueType, beanProperty);
        }
        final JsonSerializer<?> jsonSerializer = jsonSerializerFindContextualConvertingSerializer;
        if (null == jsonSerializerSerializerInstance2) {
            jsonSerializerSerializerInstance2 = _keySerializer;
        }
        if (null == jsonSerializerSerializerInstance2) {
            jsonSerializerHandleSecondaryContextualization = serializerProvider.findKeySerializer(_keyType, beanProperty);
        } else {
            jsonSerializerHandleSecondaryContextualization = serializerProvider.handleSecondaryContextualization(jsonSerializerSerializerInstance2, beanProperty);
        }
        final JsonSerializer<?> jsonSerializer2 = jsonSerializerHandleSecondaryContextualization;
        final Object obj2 = _suppressableValue;
        boolean z2 = _suppressNulls;
        if (null == beanProperty || null == (valueFindPropertyInclusion = beanProperty.findPropertyInclusion(serializerProvider.getConfig(), null)) || JsonInclude.Include.USE_DEFAULTS == (contentInclusion = valueFindPropertyInclusion.getContentInclusion())) {
            obj = obj2;
        } else {
            final int i2 = C12151.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[contentInclusion.ordinal()];
            z2 = true;
            if (1 == i2) {
                defaultValue = BeanUtil.getDefaultValue(_valueType);
                if (null != defaultValue && defaultValue.getClass().isArray()) {
                    defaultValue = ArrayBuilders.getArrayComparator(defaultValue);
                }
            } else if (2 != i2) {
                if (3 == i2) {
                    defaultValue = MapEntrySerializer.MARKER_FOR_EMPTY;
                } else {
                    if (4 == i2) {
                        defaultValue = serializerProvider.includeFilterInstance(null, valueFindPropertyInclusion.getContentFilter());
                        if (null != defaultValue) {
                            zIncludeFilterSuppressNulls = serializerProvider.includeFilterSuppressNulls(defaultValue);
                            z = zIncludeFilterSuppressNulls;
                            obj = defaultValue;
                        }
                    } else if (5 != i2) {
                        zIncludeFilterSuppressNulls = false;
                        z = zIncludeFilterSuppressNulls;
                        obj = defaultValue;
                    }
                    return this.withResolved(beanProperty, jsonSerializer2, jsonSerializer, obj, z);
                }
            } else if (_valueType.isReferenceType()) {
                defaultValue = MapEntrySerializer.MARKER_FOR_EMPTY;
            }
            obj = defaultValue;
        }
        z = z2;
        return this.withResolved(beanProperty, jsonSerializer2, jsonSerializer, obj, z);
    }

    /* renamed from: com.fasterxml.jackson.databind.ser.impl.MapEntrySerializer1 */
    enum C12151 {
        ;
        static final int[] SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude;

        static {
            final int[] iArr = new int[JsonInclude.Include.values().length];
            SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude = iArr;
            try {
                iArr[JsonInclude.Include.NON_DEFAULT.ordinal()] = 1;
            } catch (final NoSuchFieldError unused) {
            }
            try {
                C12151.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.NON_ABSENT.ordinal()] = 2;
            } catch (final NoSuchFieldError unused2) {
            }
            try {
                C12151.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.NON_EMPTY.ordinal()] = 3;
            } catch (final NoSuchFieldError unused3) {
            }
            try {
                C12151.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.CUSTOM.ordinal()] = 4;
            } catch (final NoSuchFieldError unused4) {
            }
            try {
                C12151.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.NON_NULL.ordinal()] = 5;
            } catch (final NoSuchFieldError unused5) {
            }
            try {
                C12151.SwitchMapcomfasterxmljacksonannotationJsonIncludeInclude[JsonInclude.Include.ALWAYS.ordinal()] = 6;
            } catch (final NoSuchFieldError unused6) {
            }
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public JavaType getContentType() {
        return _valueType;
    }

    @Override // com.fasterxml.jackson.databind.ser.ContainerSerializer
    public JsonSerializer<?> getContentSerializer() {
        return _valueSerializer;
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public boolean isEmpty(final SerializerProvider serializerProvider, final Map.Entry<?, ?> entry) {
        final Object value = entry.getValue();
        if (null == value) {
            return _suppressNulls;
        }
        if (null == this._suppressableValue) {
            return false;
        }
        JsonSerializer<Object> jsonSerializer_findAndAddDynamic = _valueSerializer;
        if (null == jsonSerializer_findAndAddDynamic) {
            final Class<?> cls = value.getClass();
            final JsonSerializer<Object> jsonSerializerSerializerFor = _dynamicValueSerializers.serializerFor(cls);
            if (null == jsonSerializerSerializerFor) {
                try {
                    jsonSerializer_findAndAddDynamic = this._findAndAddDynamic(_dynamicValueSerializers, cls, serializerProvider);
                } catch (final JsonMappingException unused) {
                    return false;
                }
            } else {
                jsonSerializer_findAndAddDynamic = jsonSerializerSerializerFor;
            }
        }
        final Object obj = _suppressableValue;
        if (MapEntrySerializer.MARKER_FOR_EMPTY == obj) {
            return jsonSerializer_findAndAddDynamic.isEmpty(serializerProvider, value);
        }
        return obj.equals(value);
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void serialize(final Map.Entry<?, ?> entry, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        jsonGenerator.writeStartObject(entry);
        this.serializeDynamic(entry, jsonGenerator, serializerProvider);
        jsonGenerator.writeEndObject();
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public void serializeWithType(final Map.Entry<?, ?> entry, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider, final TypeSerializer typeSerializer) throws IOException {
        jsonGenerator.setCurrentValue(entry);
        final WritableTypeId writableTypeIdWriteTypePrefix = typeSerializer.writeTypePrefix(jsonGenerator, typeSerializer.typeId(entry, JsonToken.START_OBJECT));
        this.serializeDynamic(entry, jsonGenerator, serializerProvider);
        typeSerializer.writeTypeSuffix(jsonGenerator, writableTypeIdWriteTypePrefix);
    }

    protected void serializeDynamic(final Map.Entry<?, ?> entry, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        final JsonSerializer<Object> jsonSerializerFindNullKeySerializer;
        JsonSerializer<Object> jsonSerializer_findAndAddDynamic;
        final TypeSerializer typeSerializer = _valueTypeSerializer;
        final Object key = entry.getKey();
        if (null == key) {
            jsonSerializerFindNullKeySerializer = serializerProvider.findNullKeySerializer(_keyType, _property);
        } else {
            jsonSerializerFindNullKeySerializer = _keySerializer;
        }
        final Object value = entry.getValue();
        if (null == value) {
            if (_suppressNulls) {
                return;
            } else {
                jsonSerializer_findAndAddDynamic = serializerProvider.getDefaultNullValueSerializer();
            }
        } else {
            jsonSerializer_findAndAddDynamic = _valueSerializer;
            if (null == jsonSerializer_findAndAddDynamic) {
                final Class<?> cls = value.getClass();
                final JsonSerializer<Object> jsonSerializerSerializerFor = _dynamicValueSerializers.serializerFor(cls);
                if (null != jsonSerializerSerializerFor) {
                    jsonSerializer_findAndAddDynamic = jsonSerializerSerializerFor;
                } else if (_valueType.hasGenericTypes()) {
                    jsonSerializer_findAndAddDynamic = this._findAndAddDynamic(_dynamicValueSerializers, serializerProvider.constructSpecializedType(_valueType, cls), serializerProvider);
                } else {
                    jsonSerializer_findAndAddDynamic = this._findAndAddDynamic(_dynamicValueSerializers, cls, serializerProvider);
                }
            }
            final Object obj = _suppressableValue;
            if (null != obj && ((MapEntrySerializer.MARKER_FOR_EMPTY == obj && jsonSerializer_findAndAddDynamic.isEmpty(serializerProvider, value)) || _suppressableValue.equals(value))) {
                return;
            }
        }
        jsonSerializerFindNullKeySerializer.serialize(key, jsonGenerator, serializerProvider);
        try {
            if (null == typeSerializer) {
                jsonSerializer_findAndAddDynamic.serialize(value, jsonGenerator, serializerProvider);
            } else {
                jsonSerializer_findAndAddDynamic.serializeWithType(value, jsonGenerator, serializerProvider, typeSerializer);
            }
        } catch (final Exception e2) {
            this.wrapAndThrow(serializerProvider, e2, entry, "" + key);
        }
    }

    protected final JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final Class<?> cls, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddSecondarySerializer = propertySerializerMap.findAndAddSecondarySerializer(cls, serializerProvider, _property);
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddSecondarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicValueSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddSecondarySerializer.serializer();
    }

    protected final JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final JavaType javaType, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddSecondarySerializer = propertySerializerMap.findAndAddSecondarySerializer(javaType, serializerProvider, _property);
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddSecondarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicValueSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddSecondarySerializer.serializer();
    }
}
