package com.fasterxml.jackson.databind.ser.impl;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.util.TypeKey;
import java.util.HashMap;
import java.util.Map;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class ReadOnlyClassToSerializerMap {
    private final Bucket[] _buckets;
    private final int _mask;
    private final int _size;

    private static int findSize(final int i2) {
        int i3 = 8;
        while (i3 < (64 >= i2 ? i2 + i2 : i2 + (i2 >> 2))) {
            i3 += i3;
        }
        return i3;
    }

    public ReadOnlyClassToSerializerMap(final Map<TypeKey, JsonSerializer<Object>> map) {
        final int iFindSize = ReadOnlyClassToSerializerMap.findSize(map.size());
        _size = iFindSize;
        _mask = iFindSize - 1;
        final Bucket[] bucketArr = new Bucket[iFindSize];
        for (final Map.Entry<TypeKey, JsonSerializer<Object>> entry : map.entrySet()) {
            final TypeKey key = entry.getKey();
            final int iHashCode = key.hashCode() & _mask;
            bucketArr[iHashCode] = new Bucket(bucketArr[iHashCode], key, entry.getValue());
        }
        _buckets = bucketArr;
    }

    public static ReadOnlyClassToSerializerMap from(final HashMap<TypeKey, JsonSerializer<Object>> map) {
        return new ReadOnlyClassToSerializerMap(map);
    }

    public JsonSerializer<Object> typedValueSerializer(final JavaType javaType) {
        Bucket bucket = _buckets[TypeKey.typedHash(javaType) & _mask];
        if (null == bucket) {
            return null;
        }
        if (bucket.matchesTyped(javaType)) {
            return bucket.value;
        }
        do {
            bucket = bucket.next;
            if (null == bucket) {
                return null;
            }
        } while (!bucket.matchesTyped(javaType));
        return bucket.value;
    }

    public JsonSerializer<Object> typedValueSerializer(final Class<?> cls) {
        Bucket bucket = _buckets[TypeKey.typedHash(cls) & _mask];
        if (null == bucket) {
            return null;
        }
        if (bucket.matchesTyped(cls)) {
            return bucket.value;
        }
        do {
            bucket = bucket.next;
            if (null == bucket) {
                return null;
            }
        } while (!bucket.matchesTyped(cls));
        return bucket.value;
    }

    public JsonSerializer<Object> untypedValueSerializer(final JavaType javaType) {
        Bucket bucket = _buckets[TypeKey.untypedHash(javaType) & _mask];
        if (null == bucket) {
            return null;
        }
        if (bucket.matchesUntyped(javaType)) {
            return bucket.value;
        }
        do {
            bucket = bucket.next;
            if (null == bucket) {
                return null;
            }
        } while (!bucket.matchesUntyped(javaType));
        return bucket.value;
    }

    public JsonSerializer<Object> untypedValueSerializer(final Class<?> cls) {
        Bucket bucket = _buckets[TypeKey.untypedHash(cls) & _mask];
        if (null == bucket) {
            return null;
        }
        if (bucket.matchesUntyped(cls)) {
            return bucket.value;
        }
        do {
            bucket = bucket.next;
            if (null == bucket) {
                return null;
            }
        } while (!bucket.matchesUntyped(cls));
        return bucket.value;
    }

    private static final class Bucket {
        private final Class<?> _class;
        private final boolean _isTyped;
        private final JavaType _type;
        public final Bucket next;
        public final JsonSerializer<Object> value;

        public Bucket(final Bucket bucket, final TypeKey typeKey, final JsonSerializer<Object> jsonSerializer) {
            next = bucket;
            value = jsonSerializer;
            _isTyped = typeKey.isTyped();
            _class = typeKey.getRawType();
            _type = typeKey.getType();
        }

        public boolean matchesTyped(final Class<?> cls) {
            return _class == cls && _isTyped;
        }

        public boolean matchesUntyped(final Class<?> cls) {
            return _class == cls && !_isTyped;
        }

        public boolean matchesTyped(final JavaType javaType) {
            return _isTyped && javaType.equals(_type);
        }

        public boolean matchesUntyped(final JavaType javaType) {
            return !_isTyped && javaType.equals(_type);
        }
    }
}
