package com.fasterxml.jackson.databind.ser.impl;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class UnsupportedTypeSerializer extends StdSerializer<Object> {
    private static final long serialVersionUID = 1;
    protected final String _message;
    protected final JavaType _type;

    public UnsupportedTypeSerializer(final JavaType javaType, final String str) {
        super(Object.class);
        _type = javaType;
        _message = str;
    }

    @Override // com.fasterxml.jackson.databind.ser.std.StdSerializer, com.fasterxml.jackson.databind.JsonSerializer
    public void serialize(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        serializerProvider.reportBadDefinition(_type, _message);
    }
}
