package com.fasterxml.jackson.databind.ser.impl;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.io.SerializedString;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonObjectFormatVisitor;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.ser.BeanPropertyWriter;
import com.fasterxml.jackson.databind.util.NameTransformer;

import java.util.Iterator;
import java.util.Map;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class UnwrappingBeanPropertyWriter extends BeanPropertyWriter {
    private static final long serialVersionUID = 1;
    protected final NameTransformer _nameTransformer;

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter
    public boolean isUnwrapping() {
        return true;
    }

    public UnwrappingBeanPropertyWriter(final BeanPropertyWriter beanPropertyWriter, final NameTransformer nameTransformer) {
        super(beanPropertyWriter);
        _nameTransformer = nameTransformer;
    }

    protected UnwrappingBeanPropertyWriter(final UnwrappingBeanPropertyWriter unwrappingBeanPropertyWriter, final NameTransformer nameTransformer, final SerializedString serializedString) {
        super(unwrappingBeanPropertyWriter, serializedString);
        _nameTransformer = nameTransformer;
    }

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter
    public UnwrappingBeanPropertyWriter rename(final NameTransformer nameTransformer) {
        return this._new(NameTransformer.chainedTransformer(nameTransformer, _nameTransformer), new SerializedString(nameTransformer.transform(_name.getValue())));
    }

    protected UnwrappingBeanPropertyWriter _new(final NameTransformer nameTransformer, final SerializedString serializedString) {
        return new UnwrappingBeanPropertyWriter(this, nameTransformer, serializedString);
    }

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter, com.fasterxml.jackson.databind.ser.PropertyWriter
    public void serializeAsField(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws Exception {
        final Object obj2 = this.get(obj);
        if (null == obj2) {
            return;
        }
        JsonSerializer<?> jsonSerializer_findAndAddDynamic = _serializer;
        if (null == jsonSerializer_findAndAddDynamic) {
            final Class<?> cls = obj2.getClass();
            final PropertySerializerMap propertySerializerMap = _dynamicSerializers;
            final JsonSerializer<?> jsonSerializerSerializerFor = propertySerializerMap.serializerFor(cls);
            jsonSerializer_findAndAddDynamic = null == jsonSerializerSerializerFor ? this._findAndAddDynamic(propertySerializerMap, cls, serializerProvider) : jsonSerializerSerializerFor;
        }
        final Object obj3 = _suppressableValue;
        if (null != obj3) {
            if (MARKER_FOR_EMPTY == obj3) {
                if (jsonSerializer_findAndAddDynamic.isEmpty(serializerProvider, obj2)) {
                    return;
                }
            } else if (obj3.equals(obj2)) {
                return;
            }
        }
        if (obj2 == obj && this._handleSelfReference(obj, jsonGenerator, serializerProvider, jsonSerializer_findAndAddDynamic)) {
            return;
        }
        if (!jsonSerializer_findAndAddDynamic.isUnwrappingSerializer()) {
            jsonGenerator.writeFieldName(_name);
        }
        final TypeSerializer typeSerializer = _typeSerializer;
        if (null == typeSerializer) {
            jsonSerializer_findAndAddDynamic.serialize(obj2, jsonGenerator, serializerProvider);
        } else {
            jsonSerializer_findAndAddDynamic.serializeWithType(obj2, jsonGenerator, serializerProvider, typeSerializer);
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter
    public void assignSerializer(JsonSerializer<Object> jsonSerializer) {
        if (null != jsonSerializer) {
            NameTransformer nameTransformerChainedTransformer = _nameTransformer;
            if (jsonSerializer.isUnwrappingSerializer() && (jsonSerializer instanceof UnwrappingBeanSerializer)) {
                nameTransformerChainedTransformer = NameTransformer.chainedTransformer(nameTransformerChainedTransformer, ((UnwrappingBeanSerializer) jsonSerializer)._nameTransformer);
            }
            jsonSerializer = jsonSerializer.unwrappingSerializer(nameTransformerChainedTransformer);
        }
        super.assignSerializer(jsonSerializer);
    }

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter, com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public void depositSchemaProperty(final JsonObjectFormatVisitor jsonObjectFormatVisitor, final SerializerProvider serializerProvider) throws JsonMappingException {
        final JsonSerializer<Object> jsonSerializerUnwrappingSerializer = serializerProvider.findValueSerializer(this.getType(), this).unwrappingSerializer(_nameTransformer);
        if (jsonSerializerUnwrappingSerializer.isUnwrappingSerializer()) {
            jsonSerializerUnwrappingSerializer.acceptJsonFormatVisitor(new JsonFormatVisitorWrapper.Base(serializerProvider, jsonObjectFormatVisitor) { // from class: com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.1
                @Override // com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper.Base, com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper
                public JsonObjectFormatVisitor expectObjectFormat(final JavaType javaType) throws JsonMappingException {
                    return null;
                }
            }, this.getType());
        } else {
            super.depositSchemaProperty(jsonObjectFormatVisitor, serializerProvider);
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter
    protected void _depositSchemaProperty(final ObjectNode objectNode, final JsonNode jsonNode) {
        final JsonNode jsonNode2 = jsonNode.get("properties");
        if (null != jsonNode2) {
            final Iterator<Map.Entry<String, JsonNode>> itFields = jsonNode2.fields();
            while (itFields.hasNext()) {
                final Map.Entry<String, JsonNode> next = itFields.next();
                String key = next.getKey();
                final NameTransformer nameTransformer = _nameTransformer;
                if (null != nameTransformer) {
                    key = nameTransformer.transform(key);
                }
                objectNode.set(key, next.getValue());
            }
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.BeanPropertyWriter
    protected JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final Class<?> cls, final SerializerProvider serializerProvider) throws JsonMappingException {
        final JsonSerializer<Object> jsonSerializerFindValueSerializer;
        final JavaType javaType = _nonTrivialBaseType;
        if (null != javaType) {
            jsonSerializerFindValueSerializer = serializerProvider.findValueSerializer(serializerProvider.constructSpecializedType(javaType, cls), this);
        } else {
            jsonSerializerFindValueSerializer = serializerProvider.findValueSerializer(cls, this);
        }
        NameTransformer nameTransformerChainedTransformer = _nameTransformer;
        if (jsonSerializerFindValueSerializer.isUnwrappingSerializer() && (jsonSerializerFindValueSerializer instanceof UnwrappingBeanSerializer)) {
            nameTransformerChainedTransformer = NameTransformer.chainedTransformer(nameTransformerChainedTransformer, ((UnwrappingBeanSerializer) jsonSerializerFindValueSerializer)._nameTransformer);
        }
        final JsonSerializer<Object> jsonSerializerUnwrappingSerializer = jsonSerializerFindValueSerializer.unwrappingSerializer(nameTransformerChainedTransformer);
        _dynamicSerializers = _dynamicSerializers.newWith(cls, jsonSerializerUnwrappingSerializer);
        return jsonSerializerUnwrappingSerializer;
    }
}
