package okhttp3.internal.ws;

import kotlin.jvm.internal.Intrinsics;
import okhttp3.internal.Util;
import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import java.io.Closeable;
import java.io.IOException;
import java.net.ProtocolException;
import java.util.concurrent.TimeUnit;
import java.util.zip.DataFormatException;

import static kotlin.jvm.internal.Intrinsics.checkNotNull;
import static kotlin.jvm.internal.Intrinsics.stringPlus;

// Class generated by  decompiler (1.5.3)
/* compiled from: WebSocketReader.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class WebSocketReader implements Closeable {
    private final Buffer controlFrameBuffer;
    private final FrameCallback frameCallback;
    private final boolean isClient;
    private final Buffer.UnsafeCursor maskCursor;
    private final byte[] maskKey;
    private final Buffer messageFrameBuffer;
    private final boolean noContextTakeover;
    private final boolean perMessageDeflate;
    private final BufferedSource source;
    private boolean closed;
    private long frameLength;
    private boolean isControlFrame;
    private boolean isFinalFrame;
    private MessageInflater messageInflater;
    private int opcode;
    private boolean readingCompressedMessage;

    public WebSocketReader(final boolean z, final BufferedSource source, final FrameCallback frameCallback, final boolean z2, final boolean z3) {
        Intrinsics.checkNotNullParameter(source, "source");
        Intrinsics.checkNotNullParameter(frameCallback, "frameCallback");
        isClient = z;
        this.source = source;
        this.frameCallback = frameCallback;
        perMessageDeflate = z2;
        noContextTakeover = z3;
        controlFrameBuffer = new Buffer();
        messageFrameBuffer = new Buffer();
        maskKey = z ? null : new byte[4];
        maskCursor = z ? null : new Buffer.UnsafeCursor();
    }

    public BufferedSource getSource() {
        return source;
    }

    public void processNextFrame() throws DataFormatException, IOException {
        this.readHeader();
        if (isControlFrame) {
            this.readControlFrame();
        } else {
            this.readMessageFrame();
        }
    }

    private void readHeader() throws IOException {
        final boolean z;
        final String str;
        if (closed) {
            throw new IOException("closed");
        }
        final long jTimeoutNanos = source.timeout().timeoutNanos();
        source.timeout().clearTimeout();
        try {
            final int iAnd = Util.and(source.readByte(), 255);
            source.timeout().timeout(jTimeoutNanos, TimeUnit.NANOSECONDS);
            final int i2 = iAnd & 15;
            opcode = i2;
            final boolean z2 = 0 != (iAnd & 128);
            isFinalFrame = z2;
            final boolean z3 = 0 != (iAnd & 8);
            isControlFrame = z3;
            if (z3 && !z2) {
                throw new ProtocolException("Control frames must be final.");
            }
            final boolean z4 = 0 != (iAnd & 64);
            if (1 == i2 || 2 == i2) {
                if (!z4) {
                    z = false;
                } else {
                    if (!perMessageDeflate) {
                        throw new ProtocolException("Unexpected rsv1 flag");
                    }
                    z = true;
                }
                readingCompressedMessage = z;
            } else if (z4) {
                throw new ProtocolException("Unexpected rsv1 flag");
            }
            if (0 != (iAnd & 32)) {
                throw new ProtocolException("Unexpected rsv2 flag");
            }
            if (0 != (iAnd & 16)) {
                throw new ProtocolException("Unexpected rsv3 flag");
            }
            final int iAnd2 = Util.and(source.readByte(), 255);
            final boolean z5 = 0 != (iAnd2 & 128);
            if (z5 == isClient) {
                if (isClient) {
                    str = "Server-sent frames must not be masked.";
                } else {
                    str = "Client-sent frames must be masked.";
                }
                throw new ProtocolException(str);
            }
            final long j2 = iAnd2 & 127;
            frameLength = j2;
            if (126 == j2) {
                frameLength = Util.and(source.readShort(), 65535);
            } else if (127 == j2) {
                final long j3 = source.readLong();
                frameLength = j3;
                if (0 > j3) {
                    throw new ProtocolException("Frame length 0x" + Util.toHexString(frameLength) + " > 0x7FFFFFFFFFFFFFFF");
                }
            }
            if (isControlFrame && 125 < this.frameLength) {
                throw new ProtocolException("Control frame must be less than 125B.");
            }
            if (z5) {
                final BufferedSource bufferedSource = source;
                final byte[] bArr = maskKey;
                checkNotNull(bArr);
                bufferedSource.readFully(bArr);
            }
        } catch (final Throwable th) {
            source.timeout().timeout(jTimeoutNanos, TimeUnit.NANOSECONDS);
            throw th;
        }
    }

    private void readControlFrame() throws IOException {
        final short s;
        final String utf8;
        final long j2 = frameLength;
        if (0 < j2) {
            source.readFully(controlFrameBuffer, j2);
            if (!isClient) {
                final Buffer buffer = controlFrameBuffer;
                final Buffer.UnsafeCursor unsafeCursor = maskCursor;
                checkNotNull(unsafeCursor);
                buffer.readAndWriteUnsafe(unsafeCursor);
                maskCursor.seek(0L);
                final WebSocketProtocol webSocketProtocol = WebSocketProtocol.INSTANCE;
                final Buffer.UnsafeCursor unsafeCursor2 = maskCursor;
                final byte[] bArr = maskKey;
                checkNotNull(bArr);
                webSocketProtocol.toggleMask(unsafeCursor2, bArr);
                maskCursor.close();
            }
        }
        switch (opcode) {
            case 8:
                final long size = controlFrameBuffer.size();
                if (1 == size) {
                    throw new ProtocolException("Malformed close payload length of 1.");
                }
                if (0 == size) {
                    s = 1005;
                    utf8 = "";
                } else {
                    s = controlFrameBuffer.readShort();
                    utf8 = controlFrameBuffer.readUtf8();
                    final String strCloseCodeExceptionMessage = WebSocketProtocol.INSTANCE.closeCodeExceptionMessage(s);
                    if (null != strCloseCodeExceptionMessage) {
                        throw new ProtocolException(strCloseCodeExceptionMessage);
                    }
                }
                frameCallback.onReadClose(s, utf8);
                closed = true;
                return;
            case 9:
                frameCallback.onReadPing(controlFrameBuffer.readByteString());
                return;
            case 10:
                frameCallback.onReadPong(controlFrameBuffer.readByteString());
                return;
            default:
                throw new ProtocolException(stringPlus("Unknown control opcode: ", Util.toHexString(opcode)));
        }
    }

    private void readMessageFrame() throws DataFormatException, IOException {
        final int i2 = opcode;
        if (1 != i2 && 2 != i2) {
            throw new ProtocolException(stringPlus("Unknown opcode: ", Util.toHexString(i2)));
        }
        this.readMessage();
        if (readingCompressedMessage) {
            MessageInflater messageInflater = this.messageInflater;
            if (null == messageInflater) {
                messageInflater = new MessageInflater(noContextTakeover);
                this.messageInflater = messageInflater;
            }
            messageInflater.inflate(messageFrameBuffer);
        }
        if (1 == i2) {
            frameCallback.onReadMessage(messageFrameBuffer.readUtf8());
        } else {
            frameCallback.onReadMessage(messageFrameBuffer.readByteString());
        }
    }

    private void readUntilNonControlFrame() throws IOException {
        while (!closed) {
            this.readHeader();
            if (!isControlFrame) {
                return;
            } else {
                this.readControlFrame();
            }
        }
    }

    private void readMessage() throws IOException {
        while (!closed) {
            final long j2 = frameLength;
            if (0 < j2) {
                source.readFully(messageFrameBuffer, j2);
                if (!isClient) {
                    final Buffer buffer = messageFrameBuffer;
                    final Buffer.UnsafeCursor unsafeCursor = maskCursor;
                    checkNotNull(unsafeCursor);
                    buffer.readAndWriteUnsafe(unsafeCursor);
                    maskCursor.seek(messageFrameBuffer.size() - frameLength);
                    final WebSocketProtocol webSocketProtocol = WebSocketProtocol.INSTANCE;
                    final Buffer.UnsafeCursor unsafeCursor2 = maskCursor;
                    final byte[] bArr = maskKey;
                    checkNotNull(bArr);
                    webSocketProtocol.toggleMask(unsafeCursor2, bArr);
                    maskCursor.close();
                }
            }
            if (isFinalFrame) {
                return;
            }
            this.readUntilNonControlFrame();
            if (0 != this.opcode) {
                throw new ProtocolException(stringPlus("Expected continuation opcode. Got: ", Util.toHexString(opcode)));
            }
        }
        throw new IOException("closed");
    }

    @Override // java.io.Closeable, java.lang.AutoCloseable
    public void close() throws IOException {
        final MessageInflater messageInflater = this.messageInflater;
        if (null == messageInflater) {
            return;
        }
        messageInflater.close();
    }

    /* compiled from: WebSocketReader.kt */
    public interface FrameCallback {
        void onReadClose(int i2, String str);

        void onReadMessage(String str) throws IOException;

        void onReadMessage(ByteString byteString) throws IOException;

        void onReadPing(ByteString byteString);

        void onReadPong(ByteString byteString);
    }
}
