package okhttp3.internal.ws;

import kotlin.jvm.internal.Intrinsics;
import okio.Buffer;
import okio.ByteString;

import static kotlin.jvm.internal.Intrinsics.checkNotNull;
import static kotlin.jvm.internal.Intrinsics.stringPlus;

// Class generated by  decompiler (1.5.3)
/* compiled from: WebSocketProtocol.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class WebSocketProtocol {
    public static final String ACCEPT_MAGIC = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
    public static final int B0_FLAG_FIN = 128;
    public static final int B0_FLAG_RSV1 = 64;
    public static final int B0_FLAG_RSV2 = 32;
    public static final int B0_FLAG_RSV3 = 16;
    public static final int B0_MASK_OPCODE = 15;
    public static final int B1_FLAG_MASK = 128;
    public static final int B1_MASK_LENGTH = 127;
    public static final int CLOSE_CLIENT_GOING_AWAY = 1001;
    public static final long CLOSE_MESSAGE_MAX = 123;
    public static final int CLOSE_NO_STATUS_CODE = 1005;
    public static final WebSocketProtocol INSTANCE = new WebSocketProtocol();
    public static final int OPCODE_BINARY = 2;
    public static final int OPCODE_CONTINUATION = 0;
    public static final int OPCODE_CONTROL_CLOSE = 8;
    public static final int OPCODE_CONTROL_PING = 9;
    public static final int OPCODE_CONTROL_PONG = 10;
    public static final int OPCODE_FLAG_CONTROL = 8;
    public static final int OPCODE_TEXT = 1;
    public static final long PAYLOAD_BYTE_MAX = 125;
    public static final int PAYLOAD_LONG = 127;
    public static final int PAYLOAD_SHORT = 126;
    public static final long PAYLOAD_SHORT_MAX = 65535;

    private WebSocketProtocol() {
    }

    public void toggleMask(final Buffer.UnsafeCursor cursor, final byte[] key) {
        Intrinsics.checkNotNullParameter(cursor, "cursor");
        Intrinsics.checkNotNullParameter(key, "key");
        final int length = key.length;
        int i2 = 0;
        do {
            final byte[] bArr = cursor.data;
            int i3 = cursor.start;
            final int i4 = cursor.end;
            if (null != bArr) {
                while (i3 < i4) {
                    final int i5 = i2 % length;
                    bArr[i3] = (byte) (bArr[i3] ^ key[i5]);
                    i3++;
                    i2 = i5 + 1;
                }
            }
        } while (-1 != cursor.next());
    }

    public String closeCodeExceptionMessage(final int i2) {
        if (1000 > i2 || 5000 <= i2) {
            return stringPlus("Code must be in range [1000,5000): ", Integer.valueOf(i2));
        }
        if ((1004 > i2 || 1007 <= i2) && (1015 > i2 || 3000 <= i2)) {
            return null;
        }
        return "Code " + i2 + " is reserved and may not be used.";
    }

    public void validateCloseCode(final int i2) {
        final String strCloseCodeExceptionMessage = this.closeCodeExceptionMessage(i2);
        if (null == strCloseCodeExceptionMessage) {
            return;
        }
        checkNotNull(strCloseCodeExceptionMessage);
        throw new IllegalArgumentException(strCloseCodeExceptionMessage);
    }

    public String acceptHeader(final String key) {
        Intrinsics.checkNotNullParameter(key, "key");
        return ByteString.Companion.encodeUtf8(stringPlus(key, WebSocketProtocol.ACCEPT_MAGIC)).sha1().base64();
    }
}
