package com.fasterxml.jackson.databind.introspect;

import com.fasterxml.jackson.databind.JavaType;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;

// Class generated by  decompiler (1.5.3)
/* loaded from: classes.dex */
public abstract class AnnotatedWithParams extends AnnotatedMember {
    private static final long serialVersionUID = 1;
    protected final AnnotationMap[] _paramAnnotations;

    public abstract Object call() throws Exception;

    public abstract Object call(Object[] objArr) throws Exception;

    public abstract Object call1(Object obj) throws Exception;

    @Deprecated
    public abstract Type getGenericParameterType(int r1);

    public abstract int getParameterCount();

    public abstract JavaType getParameterType(int r1);

    public abstract Class<?> getRawParameterType(int r1);

    protected AnnotatedWithParams(TypeResolutionContext typeResolutionContext, AnnotationMap annotationMap, AnnotationMap[] annotationMapArr) {
        super(typeResolutionContext, annotationMap);
        this._paramAnnotations = annotationMapArr;
    }

    protected AnnotatedWithParams(AnnotatedWithParams annotatedWithParams, AnnotationMap[] annotationMapArr) {
        super(annotatedWithParams);
        this._paramAnnotations = annotationMapArr;
    }

    public final void addOrOverrideParam(int r2, Annotation annotation) {
        AnnotationMap annotationMap = this._paramAnnotations[r2];
        if (annotationMap == null) {
            annotationMap = new AnnotationMap();
            this._paramAnnotations[r2] = annotationMap;
        }
        annotationMap.add(annotation);
    }

    protected AnnotatedParameter replaceParameterAnnotations(int r2, AnnotationMap annotationMap) {
        this._paramAnnotations[r2] = annotationMap;
        return getParameter(r2);
    }

    public final AnnotationMap getParameterAnnotations(int r2) {
        AnnotationMap[] annotationMapArr = this._paramAnnotations;
        if (annotationMapArr == null || r2 < 0 || r2 >= annotationMapArr.length) {
            return null;
        }
        return annotationMapArr[r2];
    }

    public final AnnotatedParameter getParameter(int r8) {
        return new AnnotatedParameter(this, getParameterType(r8), this._typeContext, getParameterAnnotations(r8), r8);
    }

    public final int getAnnotationCount() {
        return this._annotations.size();
    }
}
