package com.fasterxml.jackson.databind.type;

import com.fasterxml.jackson.databind.JavaType;
import java.lang.reflect.Array;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class ArrayType extends TypeBase {
    private static final long serialVersionUID = 1;
    private final JavaType _componentType;
    private final Object _emptyArray;

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean isAbstract() {
        return false;
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean isArrayType() {
        return true;
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean isConcrete() {
        return true;
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean isContainerType() {
        return true;
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public JavaType refine(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr) {
        return null;
    }

    private ArrayType(final JavaType javaType, final TypeBindings typeBindings, final Object obj, final Object obj2, final Object obj3, final boolean z) {
        super(obj.getClass(), typeBindings, null, null, javaType.hashCode(), obj2, obj3, z);
        _componentType = javaType;
        _emptyArray = obj;
    }

    public static ArrayType construct(final JavaType javaType, final TypeBindings typeBindings) {
        return ArrayType.construct(javaType, typeBindings, null, null);
    }

    public static ArrayType construct(final JavaType javaType, final TypeBindings typeBindings, final Object obj, final Object obj2) {
        return new ArrayType(javaType, typeBindings, Array.newInstance(javaType.getRawClass(), 0), obj, obj2, false);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public JavaType withContentType(final JavaType javaType) throws NegativeArraySizeException {
        return new ArrayType(javaType, _bindings, Array.newInstance(javaType.getRawClass(), 0), _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public ArrayType withTypeHandler(final Object obj) {
        return obj == _typeHandler ? this : new ArrayType(_componentType, _bindings, _emptyArray, _valueHandler, obj, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public ArrayType withContentTypeHandler(final Object obj) {
        return obj == _componentType.getTypeHandler() ? this : new ArrayType(_componentType.withTypeHandler(obj), _bindings, _emptyArray, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public ArrayType withValueHandler(final Object obj) {
        return obj == _valueHandler ? this : new ArrayType(_componentType, _bindings, _emptyArray, obj, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public ArrayType withContentValueHandler(final Object obj) {
        return obj == _componentType.getValueHandler() ? this : new ArrayType(_componentType.withValueHandler(obj), _bindings, _emptyArray, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public ArrayType withStaticTyping() {
        return _asStatic ? this : new ArrayType(_componentType.withStaticTyping(), _bindings, _emptyArray, _valueHandler, _typeHandler, true);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    @Deprecated
    protected JavaType _narrow(final Class<?> cls) {
        return this._reportUnsupported();
    }

    private JavaType _reportUnsupported() {
        throw new UnsupportedOperationException("Cannot narrow or widen array types");
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean hasGenericTypes() {
        return _componentType.hasGenericTypes();
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public JavaType getContentType() {
        return _componentType;
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public Object getContentValueHandler() {
        return _componentType.getValueHandler();
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public Object getContentTypeHandler() {
        return _componentType.getTypeHandler();
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public boolean hasHandlers() {
        return super.hasHandlers() || _componentType.hasHandlers();
    }

    @Override // com.fasterxml.jackson.databind.type.TypeBase, com.fasterxml.jackson.databind.JavaType
    public StringBuilder getGenericSignature(final StringBuilder sb) {
        sb.append('[');
        return _componentType.getGenericSignature(sb);
    }

    @Override // com.fasterxml.jackson.databind.type.TypeBase, com.fasterxml.jackson.databind.JavaType
    public StringBuilder getErasedSignature(final StringBuilder sb) {
        sb.append('[');
        return _componentType.getErasedSignature(sb);
    }

    public Object[] getEmptyArray() {
        return (Object[]) _emptyArray;
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public String toString() {
        return "[array type, component type: " + _componentType + "]";
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (null != obj && ArrayType.class == obj.getClass()) {
            return _componentType.equals(((ArrayType) obj)._componentType);
        }
        return false;
    }
}
