package com.fasterxml.jackson.databind.type;

import com.fasterxml.jackson.databind.JavaType;
import java.util.ArrayList;
import java.util.Iterator;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class ClassStack {
    private final Class<?> _current;
    private final ClassStack _parent;
    private ArrayList<ResolvedRecursiveType> _selfRefs;

    public ClassStack(final Class<?> cls) {
        this(null, cls);
    }

    private ClassStack(final ClassStack classStack, final Class<?> cls) {
        _parent = classStack;
        _current = cls;
    }

    public ClassStack child(final Class<?> cls) {
        return new ClassStack(this, cls);
    }

    public void addSelfReference(final ResolvedRecursiveType resolvedRecursiveType) {
        if (null == this._selfRefs) {
            _selfRefs = new ArrayList<>();
        }
        _selfRefs.add(resolvedRecursiveType);
    }

    public void resolveSelfReferences(final JavaType javaType) {
        final ArrayList<ResolvedRecursiveType> arrayList = _selfRefs;
        if (null != arrayList) {
            final Iterator<ResolvedRecursiveType> it = arrayList.iterator();
            while (it.hasNext()) {
                it.next().setReference(javaType);
            }
        }
    }

    public ClassStack find(final Class<?> cls) {
        if (_current == cls) {
            return this;
        }
        for (ClassStack classStack = _parent; null != classStack; classStack = classStack._parent) {
            if (classStack._current == cls) {
                return classStack;
            }
        }
        return null;
    }

    public String toString() {
        final StringBuilder sb = new StringBuilder();
        sb.append("[ClassStack (self-refs: ");
        final ArrayList<ResolvedRecursiveType> arrayList = _selfRefs;
        sb.append(null == arrayList ? "0" : String.valueOf(arrayList.size()));
        sb.append(')');
        for (ClassStack classStack = this; null != classStack; classStack = classStack._parent) {
            sb.append(' ');
            sb.append(classStack._current.getName());
        }
        sb.append(']');
        return sb.toString();
    }
}
