package com.fasterxml.jackson.databind.type;

import com.fasterxml.jackson.databind.JavaType;
import java.lang.reflect.TypeVariable;
import java.util.Collection;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class CollectionLikeType extends TypeBase {
    private static final long serialVersionUID = 1;
    protected final JavaType _elementType;

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean isCollectionLikeType() {
        return true;
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public boolean isContainerType() {
        return true;
    }

    protected CollectionLikeType(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr, final JavaType javaType2, final Object obj, final Object obj2, final boolean z) {
        super(cls, typeBindings, javaType, javaTypeArr, javaType2.hashCode(), obj, obj2, z);
        _elementType = javaType2;
    }

    protected CollectionLikeType(final TypeBase typeBase, final JavaType javaType) {
        super(typeBase);
        _elementType = javaType;
    }

    public static CollectionLikeType construct(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr, final JavaType javaType2) {
        return new CollectionLikeType(cls, typeBindings, javaType, javaTypeArr, javaType2, null, null, false);
    }

    @Deprecated
    public static CollectionLikeType construct(final Class<?> cls, final JavaType javaType) {
        final TypeBindings typeBindingsEmptyBindings;
        final TypeVariable<Class<?>>[] typeParameters = cls.getTypeParameters();
        if (null == typeParameters || 1 != typeParameters.length) {
            typeBindingsEmptyBindings = TypeBindings.emptyBindings();
        } else {
            typeBindingsEmptyBindings = TypeBindings.create(cls, javaType);
        }
        return new CollectionLikeType(cls, typeBindingsEmptyBindings, _bogusSuperClass(cls), null, javaType, null, null, false);
    }

    public static CollectionLikeType upgradeFrom(final JavaType javaType, final JavaType javaType2) {
        if (javaType instanceof TypeBase) {
            return new CollectionLikeType((TypeBase) javaType, javaType2);
        }
        throw new IllegalArgumentException("Cannot upgrade from an instance of " + javaType.getClass());
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    @Deprecated
    protected JavaType _narrow(final Class<?> cls) {
        return new CollectionLikeType(cls, _bindings, _superClass, _superInterfaces, _elementType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public JavaType withContentType(final JavaType javaType) {
        return _elementType == javaType ? this : new CollectionLikeType(_class, _bindings, _superClass, _superInterfaces, javaType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public CollectionLikeType withTypeHandler(final Object obj) {
        return new CollectionLikeType(_class, _bindings, _superClass, _superInterfaces, _elementType, _valueHandler, obj, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public CollectionLikeType withContentTypeHandler(final Object obj) {
        return new CollectionLikeType(_class, _bindings, _superClass, _superInterfaces, _elementType.withTypeHandler(obj), _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public CollectionLikeType withValueHandler(final Object obj) {
        return new CollectionLikeType(_class, _bindings, _superClass, _superInterfaces, _elementType, obj, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public CollectionLikeType withContentValueHandler(final Object obj) {
        return new CollectionLikeType(_class, _bindings, _superClass, _superInterfaces, _elementType.withValueHandler(obj), _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public JavaType withHandlersFrom(final JavaType javaType) {
        final JavaType javaTypeWithHandlersFrom;
        final JavaType javaTypeWithHandlersFrom2 = super.withHandlersFrom(javaType);
        final JavaType contentType = javaType.getContentType();
        return (null == contentType || (javaTypeWithHandlersFrom = _elementType.withHandlersFrom(contentType)) == _elementType) ? javaTypeWithHandlersFrom2 : javaTypeWithHandlersFrom2.withContentType(javaTypeWithHandlersFrom);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public CollectionLikeType withStaticTyping() {
        return _asStatic ? this : new CollectionLikeType(_class, _bindings, _superClass, _superInterfaces, _elementType.withStaticTyping(), _valueHandler, _typeHandler, true);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public JavaType refine(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr) {
        return new CollectionLikeType(cls, typeBindings, javaType, javaTypeArr, _elementType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.core.type.ResolvedType
    public JavaType getContentType() {
        return _elementType;
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public Object getContentValueHandler() {
        return _elementType.getValueHandler();
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public Object getContentTypeHandler() {
        return _elementType.getTypeHandler();
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public boolean hasHandlers() {
        return super.hasHandlers() || _elementType.hasHandlers();
    }

    @Override // com.fasterxml.jackson.databind.type.TypeBase, com.fasterxml.jackson.databind.JavaType
    public StringBuilder getErasedSignature(final StringBuilder sb) {
        return _classSignature(_class, sb, true);
    }

    @Override // com.fasterxml.jackson.databind.type.TypeBase, com.fasterxml.jackson.databind.JavaType
    public StringBuilder getGenericSignature(final StringBuilder sb) {
        _classSignature(_class, sb, false);
        sb.append('<');
        _elementType.getGenericSignature(sb);
        sb.append(">;");
        return sb;
    }

    @Override // com.fasterxml.jackson.databind.type.TypeBase
    protected String buildCanonicalName() {
        final StringBuilder sb = new StringBuilder();
        sb.append(_class.getName());
        if (null != this._elementType) {
            sb.append('<');
            sb.append(_elementType.toCanonical());
            sb.append('>');
        }
        return sb.toString();
    }

    @Deprecated
    public boolean isTrueCollectionType() {
        return Collection.class.isAssignableFrom(_class);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (null == obj || obj.getClass() != this.getClass()) {
            return false;
        }
        final CollectionLikeType collectionLikeType = (CollectionLikeType) obj;
        return _class == collectionLikeType._class && _elementType.equals(collectionLikeType._elementType);
    }

    @Override // com.fasterxml.jackson.databind.JavaType
    public String toString() {
        return "[collection-like type; class " + _class.getName() + ", contains " + _elementType + "]";
    }
}
