package com.fasterxml.jackson.databind.type;

import com.fasterxml.jackson.databind.JavaType;
import java.lang.reflect.TypeVariable;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class MapType extends MapLikeType {
    private static final long serialVersionUID = 1;

    private MapType(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr, final JavaType javaType2, final JavaType javaType3, final Object obj, final Object obj2, final boolean z) {
        super(cls, typeBindings, javaType, javaTypeArr, javaType2, javaType3, obj, obj2, z);
    }

    private MapType(final TypeBase typeBase, final JavaType javaType, final JavaType javaType2) {
        super(typeBase, javaType, javaType2);
    }

    public static MapType construct(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr, final JavaType javaType2, final JavaType javaType3) {
        return new MapType(cls, typeBindings, javaType, javaTypeArr, javaType2, javaType3, null, null, false);
    }

    @Deprecated
    public static MapType construct(final Class<?> cls, final JavaType javaType, final JavaType javaType2) {
        final TypeBindings typeBindingsEmptyBindings;
        final TypeVariable<Class<?>>[] typeParameters = cls.getTypeParameters();
        if (null == typeParameters || 2 != typeParameters.length) {
            typeBindingsEmptyBindings = TypeBindings.emptyBindings();
        } else {
            typeBindingsEmptyBindings = TypeBindings.create(cls, javaType, javaType2);
        }
        return new MapType(cls, typeBindingsEmptyBindings, _bogusSuperClass(cls), null, javaType, javaType2, null, null, false);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    @Deprecated
    protected JavaType _narrow(final Class<?> cls) {
        return new MapType(cls, _bindings, _superClass, _superInterfaces, _keyType, _valueType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public MapType withTypeHandler(final Object obj) {
        return new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType, _valueType, _valueHandler, obj, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public MapType withContentTypeHandler(final Object obj) {
        return new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType, _valueType.withTypeHandler(obj), _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public MapType withValueHandler(final Object obj) {
        return new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType, _valueType, obj, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public MapType withContentValueHandler(final Object obj) {
        return new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType, _valueType.withValueHandler(obj), _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public MapType withStaticTyping() {
        return _asStatic ? this : new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType.withStaticTyping(), _valueType.withStaticTyping(), _valueHandler, _typeHandler, true);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public JavaType withContentType(final JavaType javaType) {
        return _valueType == javaType ? this : new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType, javaType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType
    public MapType withKeyType(final JavaType javaType) {
        return javaType == _keyType ? this : new MapType(_class, _bindings, _superClass, _superInterfaces, javaType, _valueType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public JavaType refine(final Class<?> cls, final TypeBindings typeBindings, final JavaType javaType, final JavaType[] javaTypeArr) {
        return new MapType(cls, typeBindings, javaType, javaTypeArr, _keyType, _valueType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType
    public MapType withKeyTypeHandler(final Object obj) {
        return new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType.withTypeHandler(obj), _valueType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType
    public MapType withKeyValueHandler(final Object obj) {
        return new MapType(_class, _bindings, _superClass, _superInterfaces, _keyType.withValueHandler(obj), _valueType, _valueHandler, _typeHandler, _asStatic);
    }

    @Override // com.fasterxml.jackson.databind.type.MapLikeType, com.fasterxml.jackson.databind.JavaType
    public String toString() {
        return "[map type; class " + _class.getName() + ", " + _keyType + " -> " + _valueType + "]";
    }
}
