package com.fasterxml.jackson.databind.deser;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition;
import com.fasterxml.jackson.databind.type.*;

import java.util.List;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public abstract class BeanDeserializerModifier {
    public JsonDeserializer<?> modifyArrayDeserializer(final DeserializationConfig deserializationConfig, final ArrayType arrayType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public JsonDeserializer<?> modifyCollectionDeserializer(final DeserializationConfig deserializationConfig, final CollectionType collectionType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public JsonDeserializer<?> modifyCollectionLikeDeserializer(final DeserializationConfig deserializationConfig, final CollectionLikeType collectionLikeType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public JsonDeserializer<?> modifyDeserializer(final DeserializationConfig deserializationConfig, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public JsonDeserializer<?> modifyEnumDeserializer(final DeserializationConfig deserializationConfig, final JavaType javaType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public KeyDeserializer modifyKeyDeserializer(final DeserializationConfig deserializationConfig, final JavaType javaType, final KeyDeserializer keyDeserializer) {
        return keyDeserializer;
    }

    public JsonDeserializer<?> modifyMapDeserializer(final DeserializationConfig deserializationConfig, final MapType mapType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public JsonDeserializer<?> modifyMapLikeDeserializer(final DeserializationConfig deserializationConfig, final MapLikeType mapLikeType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public JsonDeserializer<?> modifyReferenceDeserializer(final DeserializationConfig deserializationConfig, final ReferenceType referenceType, final BeanDescription beanDescription, final JsonDeserializer<?> jsonDeserializer) {
        return jsonDeserializer;
    }

    public BeanDeserializerBuilder updateBuilder(final DeserializationConfig deserializationConfig, final BeanDescription beanDescription, final BeanDeserializerBuilder beanDeserializerBuilder) {
        return beanDeserializerBuilder;
    }

    public List<BeanPropertyDefinition> updateProperties(final DeserializationConfig deserializationConfig, final BeanDescription beanDescription, final List<BeanPropertyDefinition> list) {
        return list;
    }
}
