package kotlinx.parcelize;

import com.proje.mobilesales.core.base.BaseDbSalesFiche;

public interface Parceler<T> {
    final class DefaultImpls {
        public static <T> BaseDbSalesFiche[] newArray(Parceler<T> parceler, int i) {
            try {
                throw new Throwable("Generated by Android Extensions automatically");
            } catch (Throwable e) {
                throw new RuntimeException(e);
            }
        }
        public static BaseDbSalesFiche[] newArray() {
            return new BaseDbSalesFiche[0];
        }
    }
}
