package com.fasterxml.jackson.core.io;

import com.fasterxml.jackson.core.util.ByteArrayBuilder;
import com.fasterxml.jackson.core.util.TextBuffer;
import org.kxml2.wap.Wbxml;

import java.util.Arrays;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class JsonStringEncoder {

    /* renamed from: HC */
    private static final char[] f796HC = CharTypes.copyHexChars();

    /* renamed from: HB */
    private static final byte[] f795HB = CharTypes.copyHexBytes();
    private static final JsonStringEncoder instance = new JsonStringEncoder();

    public static JsonStringEncoder getInstance() {
        return JsonStringEncoder.instance;
    }

    /*  WARN: Code restructure failed: missing block: B:10:0x0024, code lost:

        r9 = r7 + 1;
        r7 = r13.charAt(r7);
        r10 = r1[r7];
     */
    /*  WARN: Code restructure failed: missing block: B:11:0x002c, code lost:

        if (r10 >= 0) goto L13;
     */
    /*  WARN: Code restructure failed: missing block: B:12:0x002e, code lost:

        r7 = _appendNumeric(r7, r6);
     */
    /*  WARN: Code restructure failed: missing block: B:13:0x0033, code lost:

        r7 = _appendNamed(r10, r6);
     */
    /*  WARN: Code restructure failed: missing block: B:14:0x0037, code lost:

        r10 = r8 + r7;
     */
    /*  WARN: Code restructure failed: missing block: B:15:0x003a, code lost:

        if (r10 <= r0.length) goto L22;
     */
    /*  WARN: Code restructure failed: missing block: B:16:0x003c, code lost:

        r10 = r0.length - r8;
     */
    /*  WARN: Code restructure failed: missing block: B:17:0x003e, code lost:

        if (r10 <= 0) goto L19;
     */
    /*  WARN: Code restructure failed: missing block: B:18:0x0040, code lost:

        java.lang.System.arraycopy(r6, 0, r0, r8, r10);
     */
    /*  WARN: Code restructure failed: missing block: B:19:0x0043, code lost:

        if (r5 != null) goto L21;
     */
    /*  WARN: Code restructure failed: missing block: B:20:0x0045, code lost:

        r5 = com.fasterxml.jackson.core.util.TextBuffer.fromInitial(r0);
     */
    /*  WARN: Code restructure failed: missing block: B:21:0x0049, code lost:

        r0 = r5.finishCurrentSegment();
        r7 = r7 - r10;
        java.lang.System.arraycopy(r6, r10, r0, 0, r7);
        r8 = r7;
     */
    /*  WARN: Code restructure failed: missing block: B:22:0x0053, code lost:

        java.lang.System.arraycopy(r6, 0, r0, r8, r7);
        r8 = r10;
     */
    /*  WARN: Code restructure failed: missing block: B:8:0x001e, code lost:

        if (r6 != null) goto L10;
     */
    /*  WARN: Code restructure failed: missing block: B:9:0x0020, code lost:

        r6 = _qbuf();
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public char[] quoteAsString(final String str) {
        int i2;
        char[] cArrFinishCurrentSegment = new char[120];
        final int[] iArr = CharTypes.get7BitOutputEscapes();
        final int length = iArr.length;
        final int length2 = str.length();
        TextBuffer textBufferFromInitial = null;
        int i3 = 0;
        int i4 = 0;
        final char[] cArr_qbuf = null;
        loop0: while (true) {
            if (i3 >= length2) {
                break;
            }
            while (true) {
                final char cCharAt = str.charAt(i3);
                if (cCharAt < length && 0 != iArr[cCharAt]) {
                    break;
                }
                if (i4 >= cArrFinishCurrentSegment.length) {
                    if (null == textBufferFromInitial) {
                        textBufferFromInitial = TextBuffer.fromInitial(cArrFinishCurrentSegment);
                    }
                    cArrFinishCurrentSegment = textBufferFromInitial.finishCurrentSegment();
                    i4 = 0;
                }
                final int i5 = i4 + 1;
                cArrFinishCurrentSegment[i4] = cCharAt;
                i3++;
                if (i3 >= length2) {
                    i4 = i5;
                    break loop0;
                }
                i4 = i5;
            }
            i3 = i2;
        }
        if (null == textBufferFromInitial) {
            return Arrays.copyOfRange(cArrFinishCurrentSegment, 0, i4);
        }
        textBufferFromInitial.setCurrentLength(i4);
        return textBufferFromInitial.contentsAsArray();
    }

    public byte[] quoteAsUTF8(final String str) {
        int i2;
        int i3;
        int i4;
        final int length = str.length();
        byte[] bArrFinishCurrentSegment = new byte[200];
        ByteArrayBuilder byteArrayBuilderFromInitial = null;
        int i5 = 0;
        int i_appendByte = 0;
        loop0: while (true) {
            if (i5 >= length) {
                break;
            }
            final int[] iArr = CharTypes.get7BitOutputEscapes();
            while (true) {
                final char cCharAt = str.charAt(i5);
                if ('\u007f' < cCharAt || 0 != iArr[cCharAt]) {
                    break;
                }
                if (i_appendByte >= bArrFinishCurrentSegment.length) {
                    if (null == byteArrayBuilderFromInitial) {
                        byteArrayBuilderFromInitial = ByteArrayBuilder.fromInitial(bArrFinishCurrentSegment, i_appendByte);
                    }
                    bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                    i_appendByte = 0;
                }
                final int i6 = i_appendByte + 1;
                bArrFinishCurrentSegment[i_appendByte] = (byte) cCharAt;
                i5++;
                if (i5 >= length) {
                    i_appendByte = i6;
                    break loop0;
                }
                i_appendByte = i6;
            }
            if (null == byteArrayBuilderFromInitial) {
                byteArrayBuilderFromInitial = ByteArrayBuilder.fromInitial(bArrFinishCurrentSegment, i_appendByte);
            }
            if (i_appendByte >= bArrFinishCurrentSegment.length) {
                bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                i_appendByte = 0;
            }
            int i7 = i5 + 1;
            final char cCharAt2 = str.charAt(i5);
            if ('\u007f' >= cCharAt2) {
                i_appendByte = this._appendByte(cCharAt2, iArr[cCharAt2], byteArrayBuilderFromInitial, i_appendByte);
                bArrFinishCurrentSegment = byteArrayBuilderFromInitial.getCurrentSegment();
            } else {
                if ('\u07ff' >= cCharAt2) {
                    i4 = i_appendByte + 1;
                    bArrFinishCurrentSegment[i_appendByte] = (byte) ((cCharAt2 >> 6) | Wbxml.EXT_0);
                    i3 = (cCharAt2 & '?') | 128;
                } else {
                    if ('\ud800' > cCharAt2 || '\udfff' < cCharAt2) {
                        int i8 = i_appendByte + 1;
                        bArrFinishCurrentSegment[i_appendByte] = (byte) ((cCharAt2 >> '\f') | 224);
                        if (i8 >= bArrFinishCurrentSegment.length) {
                            bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                            i8 = 0;
                        }
                        bArrFinishCurrentSegment[i8] = (byte) (((cCharAt2 >> 6) & 63) | 128);
                        i2 = i8 + 1;
                        i3 = (cCharAt2 & '?') | 128;
                    } else {
                        if ('\udbff' < cCharAt2) {
                            JsonStringEncoder._illegal(cCharAt2);
                        }
                        if (i7 >= length) {
                            JsonStringEncoder._illegal(cCharAt2);
                        }
                        final int i9 = i5 + 2;
                        final int i_convert = JsonStringEncoder._convert(cCharAt2, str.charAt(i7));
                        if (1114111 < i_convert) {
                            JsonStringEncoder._illegal(i_convert);
                        }
                        int i10 = i_appendByte + 1;
                        bArrFinishCurrentSegment[i_appendByte] = (byte) ((i_convert >> 18) | 240);
                        if (i10 >= bArrFinishCurrentSegment.length) {
                            bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                            i10 = 0;
                        }
                        int i11 = i10 + 1;
                        bArrFinishCurrentSegment[i10] = (byte) (((i_convert >> 12) & 63) | 128);
                        if (i11 >= bArrFinishCurrentSegment.length) {
                            bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                            i11 = 0;
                        }
                        final int i12 = i11 + 1;
                        bArrFinishCurrentSegment[i11] = (byte) (((i_convert >> 6) & 63) | 128);
                        i3 = (i_convert & 63) | 128;
                        i2 = i12;
                        i7 = i9;
                    }
                    i4 = i2;
                }
                if (i4 >= bArrFinishCurrentSegment.length) {
                    bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                    i4 = 0;
                }
                bArrFinishCurrentSegment[i4] = (byte) i3;
                i_appendByte = i4 + 1;
            }
            i5 = i7;
        }
        if (null == byteArrayBuilderFromInitial) {
            return Arrays.copyOfRange(bArrFinishCurrentSegment, 0, i_appendByte);
        }
        return byteArrayBuilderFromInitial.completeAndCoalesce(i_appendByte);
    }

    /*  WARN: Removed duplicated region for block: B:48:0x00dd  */
    /*  WARN: Removed duplicated region for block: B:58:0x00e6 A[SYNTHETIC] */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public byte[] encodeAsUTF8(final String str) {
        int i2;
        int i3;
        final int length = str.length();
        int length2 = 200;
        byte[] bArrFinishCurrentSegment = new byte[200];
        ByteArrayBuilder byteArrayBuilderFromInitial = null;
        int i4 = 0;
        int i5 = 0;
        loop0: while (true) {
            if (i4 >= length) {
                break;
            }
            int i6 = i4 + 1;
            int iCharAt = str.charAt(i4);
            while (127 >= iCharAt) {
                if (i5 >= length2) {
                    if (null == byteArrayBuilderFromInitial) {
                        byteArrayBuilderFromInitial = ByteArrayBuilder.fromInitial(bArrFinishCurrentSegment, i5);
                    }
                    final byte[] bArrFinishCurrentSegment2 = byteArrayBuilderFromInitial.finishCurrentSegment();
                    i5 = 0;
                    bArrFinishCurrentSegment = bArrFinishCurrentSegment2;
                    length2 = bArrFinishCurrentSegment2.length;
                }
                final int i7 = i5 + 1;
                bArrFinishCurrentSegment[i5] = (byte) iCharAt;
                if (i6 >= length) {
                    i5 = i7;
                    break loop0;
                }
                final int iCharAt2 = str.charAt(i6);
                i6++;
                iCharAt = iCharAt2;
                i5 = i7;
            }
            if (null == byteArrayBuilderFromInitial) {
                byteArrayBuilderFromInitial = ByteArrayBuilder.fromInitial(bArrFinishCurrentSegment, i5);
            }
            if (i5 >= length2) {
                bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                length2 = bArrFinishCurrentSegment.length;
                i5 = 0;
            }
            if (2048 > iCharAt) {
                i2 = i5 + 1;
                bArrFinishCurrentSegment[i5] = (byte) ((iCharAt >> 6) | Wbxml.EXT_0);
            } else if (55296 > iCharAt || 57343 < iCharAt) {
                int i8 = i5 + 1;
                bArrFinishCurrentSegment[i5] = (byte) ((iCharAt >> 12) | 224);
                if (i8 >= length2) {
                    bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                    length2 = bArrFinishCurrentSegment.length;
                    i8 = 0;
                }
                bArrFinishCurrentSegment[i8] = (byte) (((iCharAt >> 6) & 63) | 128);
                i2 = i8 + 1;
            } else {
                if (56319 < iCharAt) {
                    JsonStringEncoder._illegal(iCharAt);
                }
                if (i6 >= length) {
                    JsonStringEncoder._illegal(iCharAt);
                }
                final int i9 = i6 + 1;
                final int i_convert = JsonStringEncoder._convert(iCharAt, str.charAt(i6));
                if (1114111 < i_convert) {
                    JsonStringEncoder._illegal(i_convert);
                }
                int i10 = i5 + 1;
                bArrFinishCurrentSegment[i5] = (byte) ((i_convert >> 18) | 240);
                if (i10 >= length2) {
                    bArrFinishCurrentSegment = byteArrayBuilderFromInitial.finishCurrentSegment();
                    length2 = bArrFinishCurrentSegment.length;
                    i10 = 0;
                }
                int i11 = i10 + 1;
                bArrFinishCurrentSegment[i10] = (byte) (((i_convert >> 12) & 63) | 128);
                if (i11 >= length2) {
                    final byte[] bArrFinishCurrentSegment3 = byteArrayBuilderFromInitial.finishCurrentSegment();
                    i11 = 0;
                    bArrFinishCurrentSegment = bArrFinishCurrentSegment3;
                    length2 = bArrFinishCurrentSegment3.length;
                }
                final int i12 = i11 + 1;
                bArrFinishCurrentSegment[i11] = (byte) (((i_convert >> 6) & 63) | 128);
                i3 = i_convert;
                i4 = i9;
                i2 = i12;
                if (i2 < length2) {
                    final byte[] bArrFinishCurrentSegment4 = byteArrayBuilderFromInitial.finishCurrentSegment();
                    i2 = 0;
                    bArrFinishCurrentSegment = bArrFinishCurrentSegment4;
                    length2 = bArrFinishCurrentSegment4.length;
                }
                bArrFinishCurrentSegment[i2] = (byte) ((i3 & 63) | 128);
                i5 = i2 + 1;
            }
            i3 = iCharAt;
            i4 = i6;
            if (i2 < length2) {
            }
            bArrFinishCurrentSegment[i2] = (byte) ((i3 & 63) | 128);
            i5 = i2 + 1;
        }
        if (null == byteArrayBuilderFromInitial) {
            return Arrays.copyOfRange(bArrFinishCurrentSegment, 0, i5);
        }
        return byteArrayBuilderFromInitial.completeAndCoalesce(i5);
    }

    private char[] _qbuf() {
        return new char[]{'\\', 0, '0', '0', 0, 0};
    }

    private int _appendNumeric(final int i2, final char[] cArr) {
        cArr[1] = 'u';
        final char[] cArr2 = JsonStringEncoder.f796HC;
        cArr[4] = cArr2[i2 >> 4];
        cArr[5] = cArr2[i2 & 15];
        return 6;
    }

    private int _appendNamed(final int i2, final char[] cArr) {
        cArr[1] = (char) i2;
        return 2;
    }

    private int _appendByte(int i2, final int i3, final ByteArrayBuilder byteArrayBuilder, final int i4) {
        byteArrayBuilder.setCurrentSegmentLength(i4);
        byteArrayBuilder.append(92);
        if (0 > i3) {
            byteArrayBuilder.append(117);
            if (255 < i2) {
                final byte[] bArr = JsonStringEncoder.f795HB;
                byteArrayBuilder.append(bArr[i2 >> 12]);
                byteArrayBuilder.append(bArr[(i2 >> 8) & 15]);
                i2 &= 255;
            } else {
                byteArrayBuilder.append(48);
                byteArrayBuilder.append(48);
            }
            final byte[] bArr2 = JsonStringEncoder.f795HB;
            byteArrayBuilder.append(bArr2[i2 >> 4]);
            byteArrayBuilder.append(bArr2[i2 & 15]);
        } else {
            byteArrayBuilder.append((byte) i3);
        }
        return byteArrayBuilder.getCurrentSegmentLength();
    }

    private static int _convert(final int i2, final int i3) {
        if (56320 <= i3 && 57343 >= i3) {
            return ((i2 - 55296) << 10) + 65536 + (i3 - 56320);
        }
        throw new IllegalArgumentException("Broken surrogate pair: first char 0x" + Integer.toHexString(i2) + ", second 0x" + Integer.toHexString(i3) + "; illegal combination");
    }

    private static void _illegal(final int i2) {
        throw new IllegalArgumentException(UTF8Writer.illegalSurrogateDesc(i2));
    }
}
