package com.fasterxml.jackson.core.io;

import java.io.IOException;
import java.io.InputStream;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class MergedStream extends InputStream {

    /* renamed from: _b */
    private byte[] f797_b;
    private final IOContext _ctxt;
    private final int _end;
    private final InputStream _in;
    private int _ptr;

    public MergedStream(final IOContext iOContext, final InputStream inputStream, final byte[] bArr, final int i2, final int i3) {
        _ctxt = iOContext;
        _in = inputStream;
        f797_b = bArr;
        _ptr = i2;
        _end = i3;
    }

    @Override // java.io.InputStream
    public int available() throws IOException {
        if (null != this.f797_b) {
            return _end - _ptr;
        }
        return _in.available();
    }

    @Override // java.io.InputStream, java.io.Closeable, java.lang.AutoCloseable
    public void close() throws IOException {
        this._free();
        _in.close();
    }

    @Override // java.io.InputStream
    public synchronized void mark(final int i2) {
        if (null == this.f797_b) {
            _in.mark(i2);
        }
    }

    @Override // java.io.InputStream
    public boolean markSupported() {
        return null == this.f797_b && _in.markSupported();
    }

    @Override // java.io.InputStream
    public int read() throws IOException {
        final byte[] bArr = f797_b;
        if (null != bArr) {
            final int i2 = _ptr;
            final int i3 = i2 + 1;
            _ptr = i3;
            final int i4 = bArr[i2] & 255;
            if (i3 >= _end) {
                this._free();
            }
            return i4;
        }
        return _in.read();
    }

    @Override // java.io.InputStream
    public int read(final byte[] bArr) throws IOException {
        return this.read(bArr, 0, bArr.length);
    }

    @Override // java.io.InputStream
    public int read(final byte[] bArr, final int i2, int i3) throws IOException {
        final byte[] bArr2 = f797_b;
        if (null != bArr2) {
            final int i4 = _end;
            final int i5 = _ptr;
            final int i6 = i4 - i5;
            if (i3 > i6) {
                i3 = i6;
            }
            System.arraycopy(bArr2, i5, bArr, i2, i3);
            final int i7 = _ptr + i3;
            _ptr = i7;
            if (i7 >= _end) {
                this._free();
            }
            return i3;
        }
        return _in.read(bArr, i2, i3);
    }

    @Override // java.io.InputStream
    public synchronized void reset() throws IOException {
        if (null == this.f797_b) {
            _in.reset();
        }
    }

    @Override // java.io.InputStream
    public long skip(long j2) throws IOException {
        final long j3;
        if (null != this.f797_b) {
            final int i2 = _end;
            final int i3 = _ptr;
            j3 = i2 - i3;
            if (j3 > j2) {
                _ptr = i3 + ((int) j2);
                return j2;
            }
            this._free();
            j2 -= j3;
        } else {
            j3 = 0;
        }
        return 0 < j2 ? j3 + _in.skip(j2) : j3;
    }

    private void _free() {
        final byte[] bArr = f797_b;
        if (null != bArr) {
            f797_b = null;
            final IOContext iOContext = _ctxt;
            if (null != iOContext) {
                iOContext.releaseReadIOBuffer(bArr);
            }
        }
    }
}
