package com.fasterxml.jackson.core.io;

import org.kxml2.wap.Wbxml;

import java.io.IOException;
import java.io.OutputStream;
import java.io.Writer;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class UTF8Writer extends Writer {
    private final IOContext _context;
    private OutputStream _out;
    private byte[] _outBuffer;
    private final int _outBufferEnd;
    private int _outPtr;
    private int _surrogate;

    public UTF8Writer(final IOContext iOContext, final OutputStream outputStream) {
        _context = iOContext;
        _out = outputStream;
        _outBuffer = iOContext.allocWriteEncodingBuffer();
        _outBufferEnd = r1.length - 4;
    }

    @Override // java.io.Writer, java.lang.Appendable
    public Writer append(final char c2) throws IOException {
        this.write(c2);
        return this;
    }

    @Override // java.io.Writer, java.io.Closeable, java.lang.AutoCloseable
    public void close() throws IOException {
        final OutputStream outputStream = _out;
        if (null != outputStream) {
            final int i2 = _outPtr;
            if (0 < i2) {
                outputStream.write(_outBuffer, 0, i2);
                _outPtr = 0;
            }
            final OutputStream outputStream2 = _out;
            _out = null;
            final byte[] bArr = _outBuffer;
            if (null != bArr) {
                _outBuffer = null;
                _context.releaseWriteEncodingBuffer(bArr);
            }
            outputStream2.close();
            final int i3 = _surrogate;
            _surrogate = 0;
            if (0 < i3) {
                UTF8Writer.illegalSurrogate(i3);
            }
        }
    }

    @Override // java.io.Writer, java.io.Flushable
    public void flush() throws IOException {
        final OutputStream outputStream = _out;
        if (null != outputStream) {
            final int i2 = _outPtr;
            if (0 < i2) {
                outputStream.write(_outBuffer, 0, i2);
                _outPtr = 0;
            }
            _out.flush();
        }
    }

    @Override // java.io.Writer
    public void write(final char[] cArr) throws IOException {
        this.write(cArr, 0, cArr.length);
    }

    /*  WARN: Code restructure failed: missing block: B:59:0x0025, code lost:

        continue;
     */
    @Override // java.io.Writer
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public void write(final char[] cArr, int i2, int i3) throws IOException {
        if (2 > i3) {
            if (1 == i3) {
                this.write(cArr[i2]);
                return;
            }
            return;
        }
        if (0 < this._surrogate) {
            i3--;
            this.write(this.convertSurrogate(cArr[i2]));
            i2++;
        }
        int i4 = _outPtr;
        final byte[] bArr = _outBuffer;
        final int i5 = _outBufferEnd;
        final int i6 = i3 + i2;
        while (i2 < i6) {
            if (i4 >= i5) {
                _out.write(bArr, 0, i4);
                i4 = 0;
            }
            int i7 = i2 + 1;
            char c2 = cArr[i2];
            if ('\u0080' > c2) {
                int i8 = i4 + 1;
                bArr[i4] = (byte) c2;
                int i9 = i6 - i7;
                final int i10 = i5 - i8;
                if (i9 > i10) {
                    i9 = i10;
                }
                final int i11 = i9 + i7;
                while (true) {
                    i2 = i7;
                    i4 = i8;
                    if (i2 >= i11) {
                        break;
                    }
                    i7 = i2 + 1;
                    c2 = cArr[i2];
                    if ('\u0080' <= c2) {
                        break;
                    }
                    i8 = i4 + 1;
                    bArr[i4] = (byte) c2;
                }
            }
            if ('\u0800' > c2) {
                final int i12 = i4 + 1;
                bArr[i4] = (byte) ((c2 >> 6) | Wbxml.EXT_0);
                i4 += 2;
                bArr[i12] = (byte) ((c2 & '?') | 128);
            } else if ('\ud800' > c2 || '\udfff' < c2) {
                bArr[i4] = (byte) ((c2 >> '\f') | 224);
                final int i13 = i4 + 2;
                bArr[i4 + 1] = (byte) (((c2 >> 6) & 63) | 128);
                i4 += 3;
                bArr[i13] = (byte) ((c2 & '?') | 128);
            } else {
                if ('\udbff' < c2) {
                    _outPtr = i4;
                    UTF8Writer.illegalSurrogate(c2);
                }
                _surrogate = c2;
                if (i7 >= i6) {
                    break;
                }
                i2 = i7 + 1;
                final int iConvertSurrogate = this.convertSurrogate(cArr[i7]);
                if (1114111 < iConvertSurrogate) {
                    _outPtr = i4;
                    UTF8Writer.illegalSurrogate(iConvertSurrogate);
                }
                bArr[i4] = (byte) ((iConvertSurrogate >> 18) | 240);
                bArr[i4 + 1] = (byte) (((iConvertSurrogate >> 12) & 63) | 128);
                final int i14 = i4 + 3;
                bArr[i4 + 2] = (byte) (((iConvertSurrogate >> 6) & 63) | 128);
                i4 += 4;
                bArr[i14] = (byte) ((iConvertSurrogate & 63) | 128);
            }
            i2 = i7;
        }
        _outPtr = i4;
    }

    @Override // java.io.Writer
    public void write(int i2) throws IOException {
        final int i3;
        if (0 < this._surrogate) {
            i2 = this.convertSurrogate(i2);
        } else if (55296 <= i2 && 57343 >= i2) {
            if (56319 < i2) {
                UTF8Writer.illegalSurrogate(i2);
            }
            _surrogate = i2;
            return;
        }
        final int i4 = _outPtr;
        if (i4 >= _outBufferEnd) {
            _out.write(_outBuffer, 0, i4);
            _outPtr = 0;
        }
        if (128 > i2) {
            final byte[] bArr = _outBuffer;
            final int i5 = _outPtr;
            _outPtr = i5 + 1;
            bArr[i5] = (byte) i2;
            return;
        }
        final int i6 = _outPtr;
        if (2048 > i2) {
            final byte[] bArr2 = _outBuffer;
            final int i7 = i6 + 1;
            bArr2[i6] = (byte) ((i2 >> 6) | Wbxml.EXT_0);
            i3 = i6 + 2;
            bArr2[i7] = (byte) ((i2 & 63) | 128);
        } else if (65535 >= i2) {
            final byte[] bArr3 = _outBuffer;
            bArr3[i6] = (byte) ((i2 >> 12) | 224);
            final int i8 = i6 + 2;
            bArr3[i6 + 1] = (byte) (((i2 >> 6) & 63) | 128);
            i3 = i6 + 3;
            bArr3[i8] = (byte) ((i2 & 63) | 128);
        } else {
            if (1114111 < i2) {
                UTF8Writer.illegalSurrogate(i2);
            }
            final byte[] bArr4 = _outBuffer;
            bArr4[i6] = (byte) ((i2 >> 18) | 240);
            bArr4[i6 + 1] = (byte) (((i2 >> 12) & 63) | 128);
            final int i9 = i6 + 3;
            bArr4[i6 + 2] = (byte) (((i2 >> 6) & 63) | 128);
            i3 = i6 + 4;
            bArr4[i9] = (byte) ((i2 & 63) | 128);
        }
        _outPtr = i3;
    }

    @Override // java.io.Writer
    public void write(final String str) throws IOException {
        this.write(str, 0, str.length());
    }

    /*  WARN: Code restructure failed: missing block: B:59:0x0029, code lost:

        continue;
     */
    @Override // java.io.Writer
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public void write(final String str, int i2, int i3) throws IOException {
        if (2 > i3) {
            if (1 == i3) {
                this.write(str.charAt(i2));
                return;
            }
            return;
        }
        if (0 < this._surrogate) {
            i3--;
            this.write(this.convertSurrogate(str.charAt(i2)));
            i2++;
        }
        int i4 = _outPtr;
        final byte[] bArr = _outBuffer;
        final int i5 = _outBufferEnd;
        final int i6 = i3 + i2;
        while (i2 < i6) {
            if (i4 >= i5) {
                _out.write(bArr, 0, i4);
                i4 = 0;
            }
            int i7 = i2 + 1;
            char cCharAt = str.charAt(i2);
            if ('\u0080' > cCharAt) {
                int i8 = i4 + 1;
                bArr[i4] = (byte) cCharAt;
                int i9 = i6 - i7;
                final int i10 = i5 - i8;
                if (i9 > i10) {
                    i9 = i10;
                }
                final int i11 = i9 + i7;
                while (true) {
                    i2 = i7;
                    i4 = i8;
                    if (i2 >= i11) {
                        break;
                    }
                    i7 = i2 + 1;
                    cCharAt = str.charAt(i2);
                    if ('\u0080' <= cCharAt) {
                        break;
                    }
                    i8 = i4 + 1;
                    bArr[i4] = (byte) cCharAt;
                }
            }
            if ('\u0800' > cCharAt) {
                final int i12 = i4 + 1;
                bArr[i4] = (byte) ((cCharAt >> 6) | Wbxml.EXT_0);
                i4 += 2;
                bArr[i12] = (byte) ((cCharAt & '?') | 128);
            } else if ('\ud800' > cCharAt || '\udfff' < cCharAt) {
                bArr[i4] = (byte) ((cCharAt >> '\f') | 224);
                final int i13 = i4 + 2;
                bArr[i4 + 1] = (byte) (((cCharAt >> 6) & 63) | 128);
                i4 += 3;
                bArr[i13] = (byte) ((cCharAt & '?') | 128);
            } else {
                if ('\udbff' < cCharAt) {
                    _outPtr = i4;
                    UTF8Writer.illegalSurrogate(cCharAt);
                }
                _surrogate = cCharAt;
                if (i7 >= i6) {
                    break;
                }
                i2 = i7 + 1;
                final int iConvertSurrogate = this.convertSurrogate(str.charAt(i7));
                if (1114111 < iConvertSurrogate) {
                    _outPtr = i4;
                    UTF8Writer.illegalSurrogate(iConvertSurrogate);
                }
                bArr[i4] = (byte) ((iConvertSurrogate >> 18) | 240);
                bArr[i4 + 1] = (byte) (((iConvertSurrogate >> 12) & 63) | 128);
                final int i14 = i4 + 3;
                bArr[i4 + 2] = (byte) (((iConvertSurrogate >> 6) & 63) | 128);
                i4 += 4;
                bArr[i14] = (byte) ((iConvertSurrogate & 63) | 128);
            }
            i2 = i7;
        }
        _outPtr = i4;
    }

    private int convertSurrogate(final int i2) throws IOException {
        final int i3 = _surrogate;
        _surrogate = 0;
        if (56320 <= i2 && 57343 >= i2) {
            return ((i3 - 55296) << 10) + 65536 + (i2 - 56320);
        }
        throw new IOException("Broken surrogate pair: first char 0x" + Integer.toHexString(i3) + ", second 0x" + Integer.toHexString(i2) + "; illegal combination");
    }

    private static void illegalSurrogate(final int i2) throws IOException {
        throw new IOException(UTF8Writer.illegalSurrogateDesc(i2));
    }

    static String illegalSurrogateDesc(final int i2) {
        if (1114111 < i2) {
            return "Illegal character point (0x" + Integer.toHexString(i2) + ") to output; max is 0x10FFFF as per RFC 4627";
        }
        if (55296 > i2) {
            return "Illegal character point (0x" + Integer.toHexString(i2) + ") to output";
        }
        if (56319 >= i2) {
            return "Unmatched first part of surrogate pair (0x" + Integer.toHexString(i2) + ")";
        }
        return "Unmatched second part of surrogate pair (0x" + Integer.toHexString(i2) + ")";
    }
}
