package com.proje.mobilesales.features.reports.view.activity;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.fragment.app.Fragment;
import com.proje.mobilesales.R;
import com.proje.mobilesales.features.reports.repository.ReportWcfQueriesRepository;
import com.proje.mobilesales.features.reports.viewmodel.ReportWcfQueriesViewModel;
import kotlin.jvm.internal.Intrinsics;


public final class ReportExtractInvoiceHeaderActivity extends Fragment {
    private ReportExtractInvoiceActivity.ExtractInvHeader header;
    private ReportWcfQueriesRepository reportWcfQueriesRepository;
    private ReportWcfQueriesViewModel reportWcfQueriesViewModel;
    private AppCompatTextView tvBranch;
    private AppCompatTextView tvCustomer;
    private AppCompatTextView tvCyphCode;
    private AppCompatTextView tvDate;
    private AppCompatTextView tvDepartment;
    private AppCompatTextView tvDesc1;
    private AppCompatTextView tvDesc2;
    private AppCompatTextView tvDesc3;
    private AppCompatTextView tvDesc4;
    private AppCompatTextView tvDoCode;
    private AppCompatTextView tvFactory;
    private AppCompatTextView tvFicheNo;
    private AppCompatTextView tvPayment;
    private AppCompatTextView tvProjectCode;
    private AppCompatTextView tvSalesman;
    private AppCompatTextView tvShipAccount;
    private AppCompatTextView tvShipAddress;
    private AppCompatTextView tvShipAgent;
    private AppCompatTextView tvShipDeliveryMethod;
    private AppCompatTextView tvShipTransType;
    private AppCompatTextView tvSpeCode;
    private AppCompatTextView tvTradingGroup;
    private AppCompatTextView tvWarehouse;

    @Override // androidx.fragment.app.Fragment
    public View onCreateView(final LayoutInflater inflater, final ViewGroup viewGroup, final Bundle bundle) {
        Intrinsics.checkNotNullParameter(inflater, "inflater");
        final View inflate = inflater.inflate(R.layout.extract_invoice_header, viewGroup, false);
        Intrinsics.checkNotNull(inflate);
        this.initialize(inflate);
        final Bundle arguments = this.getArguments();
        Intrinsics.checkNotNull(arguments);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader = arguments.getParcelable("INVOICE");
        header = extractInvHeader;
        if (null != extractInvHeader) {
            this.setItemValues();
        }
        return inflate;
    }

    private void setItemValues() {
        final AppCompatTextView appCompatTextView = tvFicheNo;
        Intrinsics.checkNotNull(appCompatTextView);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader = header;
        Intrinsics.checkNotNull(extractInvHeader);
        appCompatTextView.setText(extractInvHeader.getFICHENO());
        final AppCompatTextView appCompatTextView2 = tvDate;
        Intrinsics.checkNotNull(appCompatTextView2);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader2 = header;
        Intrinsics.checkNotNull(extractInvHeader2);
        appCompatTextView2.setText(extractInvHeader2.getDATE_());
        final AppCompatTextView appCompatTextView3 = tvCustomer;
        Intrinsics.checkNotNull(appCompatTextView3);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader3 = header;
        Intrinsics.checkNotNull(extractInvHeader3);
        appCompatTextView3.setText(extractInvHeader3.getCUSTOMER());
        final AppCompatTextView appCompatTextView4 = tvBranch;
        Intrinsics.checkNotNull(appCompatTextView4);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader4 = header;
        Intrinsics.checkNotNull(extractInvHeader4);
        appCompatTextView4.setText(extractInvHeader4.getBRANCH());
        final AppCompatTextView appCompatTextView5 = tvDepartment;
        Intrinsics.checkNotNull(appCompatTextView5);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader5 = header;
        Intrinsics.checkNotNull(extractInvHeader5);
        appCompatTextView5.setText(extractInvHeader5.getDEPARTMENT());
        final AppCompatTextView appCompatTextView6 = tvFactory;
        Intrinsics.checkNotNull(appCompatTextView6);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader6 = header;
        Intrinsics.checkNotNull(extractInvHeader6);
        appCompatTextView6.setText(extractInvHeader6.getFACTORY());
        final AppCompatTextView appCompatTextView7 = tvWarehouse;
        Intrinsics.checkNotNull(appCompatTextView7);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader7 = header;
        Intrinsics.checkNotNull(extractInvHeader7);
        appCompatTextView7.setText(extractInvHeader7.getWAREHOUSE());
        final AppCompatTextView appCompatTextView8 = tvPayment;
        Intrinsics.checkNotNull(appCompatTextView8);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader8 = header;
        Intrinsics.checkNotNull(extractInvHeader8);
        appCompatTextView8.setText(extractInvHeader8.getPAYMENT());
        final AppCompatTextView appCompatTextView9 = tvTradingGroup;
        Intrinsics.checkNotNull(appCompatTextView9);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader9 = header;
        Intrinsics.checkNotNull(extractInvHeader9);
        appCompatTextView9.setText(extractInvHeader9.getTRADINGGRP());
        final AppCompatTextView appCompatTextView10 = tvDoCode;
        Intrinsics.checkNotNull(appCompatTextView10);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader10 = header;
        Intrinsics.checkNotNull(extractInvHeader10);
        appCompatTextView10.setText(extractInvHeader10.getDOCODE());
        final AppCompatTextView appCompatTextView11 = tvSpeCode;
        Intrinsics.checkNotNull(appCompatTextView11);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader11 = header;
        Intrinsics.checkNotNull(extractInvHeader11);
        appCompatTextView11.setText(extractInvHeader11.getSPECODE());
        final AppCompatTextView appCompatTextView12 = tvCyphCode;
        Intrinsics.checkNotNull(appCompatTextView12);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader12 = header;
        Intrinsics.checkNotNull(extractInvHeader12);
        appCompatTextView12.setText(extractInvHeader12.getCYPHCODE());
        final AppCompatTextView appCompatTextView13 = tvSalesman;
        Intrinsics.checkNotNull(appCompatTextView13);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader13 = header;
        Intrinsics.checkNotNull(extractInvHeader13);
        appCompatTextView13.setText(extractInvHeader13.getSALESMAN());
        final AppCompatTextView appCompatTextView14 = tvProjectCode;
        Intrinsics.checkNotNull(appCompatTextView14);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader14 = header;
        Intrinsics.checkNotNull(extractInvHeader14);
        appCompatTextView14.setText(extractInvHeader14.getPROJECTCODE());
        final AppCompatTextView appCompatTextView15 = tvShipAccount;
        Intrinsics.checkNotNull(appCompatTextView15);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader15 = header;
        Intrinsics.checkNotNull(extractInvHeader15);
        appCompatTextView15.setText(extractInvHeader15.getSHIPACCOUNT());
        final AppCompatTextView appCompatTextView16 = tvShipAddress;
        Intrinsics.checkNotNull(appCompatTextView16);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader16 = header;
        Intrinsics.checkNotNull(extractInvHeader16);
        appCompatTextView16.setText(extractInvHeader16.getSHIPADDRESS());
        final AppCompatTextView appCompatTextView17 = tvShipDeliveryMethod;
        Intrinsics.checkNotNull(appCompatTextView17);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader17 = header;
        Intrinsics.checkNotNull(extractInvHeader17);
        appCompatTextView17.setText(extractInvHeader17.getSHIPDELIVERYMETHOD());
        final AppCompatTextView appCompatTextView18 = tvShipAgent;
        Intrinsics.checkNotNull(appCompatTextView18);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader18 = header;
        Intrinsics.checkNotNull(extractInvHeader18);
        appCompatTextView18.setText(extractInvHeader18.getSHIPAGENT());
        final AppCompatTextView appCompatTextView19 = tvShipTransType;
        Intrinsics.checkNotNull(appCompatTextView19);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader19 = header;
        Intrinsics.checkNotNull(extractInvHeader19);
        appCompatTextView19.setText(extractInvHeader19.getSHIPTRANSTYPE());
        final AppCompatTextView appCompatTextView20 = tvDesc1;
        Intrinsics.checkNotNull(appCompatTextView20);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader20 = header;
        Intrinsics.checkNotNull(extractInvHeader20);
        appCompatTextView20.setText(extractInvHeader20.getDESC1());
        final AppCompatTextView appCompatTextView21 = tvDesc2;
        Intrinsics.checkNotNull(appCompatTextView21);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader21 = header;
        Intrinsics.checkNotNull(extractInvHeader21);
        appCompatTextView21.setText(extractInvHeader21.getDESC2());
        final AppCompatTextView appCompatTextView22 = tvDesc3;
        Intrinsics.checkNotNull(appCompatTextView22);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader22 = header;
        Intrinsics.checkNotNull(extractInvHeader22);
        appCompatTextView22.setText(extractInvHeader22.getDESC3());
        final AppCompatTextView appCompatTextView23 = tvDesc4;
        Intrinsics.checkNotNull(appCompatTextView23);
        final ReportExtractInvoiceActivity.ExtractInvHeader extractInvHeader23 = header;
        Intrinsics.checkNotNull(extractInvHeader23);
        appCompatTextView23.setText(extractInvHeader23.getDESC4());
    }

    private void initialize(final View view) {
        final View findViewById = view.findViewById(R.id.tvFicheNo);
        Intrinsics.checkNotNull(findViewById, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvFicheNo = (AppCompatTextView) findViewById;
        final View findViewById2 = view.findViewById(R.id.tvDate);
        Intrinsics.checkNotNull(findViewById2, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDate = (AppCompatTextView) findViewById2;
        final View findViewById3 = view.findViewById(R.id.tvCustomer);
        Intrinsics.checkNotNull(findViewById3, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvCustomer = (AppCompatTextView) findViewById3;
        final View findViewById4 = view.findViewById(R.id.tvBranch);
        Intrinsics.checkNotNull(findViewById4, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvBranch = (AppCompatTextView) findViewById4;
        final View findViewById5 = view.findViewById(R.id.tvDepartment);
        Intrinsics.checkNotNull(findViewById5, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDepartment = (AppCompatTextView) findViewById5;
        final View findViewById6 = view.findViewById(R.id.tvFactory);
        Intrinsics.checkNotNull(findViewById6, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvFactory = (AppCompatTextView) findViewById6;
        final View findViewById7 = view.findViewById(R.id.tvWarehouse);
        Intrinsics.checkNotNull(findViewById7, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvWarehouse = (AppCompatTextView) findViewById7;
        final View findViewById8 = view.findViewById(R.id.tvPayment);
        Intrinsics.checkNotNull(findViewById8, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvPayment = (AppCompatTextView) findViewById8;
        final View findViewById9 = view.findViewById(R.id.tvTradinggrp);
        Intrinsics.checkNotNull(findViewById9, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvTradingGroup = (AppCompatTextView) findViewById9;
        final View findViewById10 = view.findViewById(R.id.tvDocode);
        Intrinsics.checkNotNull(findViewById10, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDoCode = (AppCompatTextView) findViewById10;
        final View findViewById11 = view.findViewById(R.id.tvSpecode);
        Intrinsics.checkNotNull(findViewById11, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvSpeCode = (AppCompatTextView) findViewById11;
        final View findViewById12 = view.findViewById(R.id.tvCyphcode);
        Intrinsics.checkNotNull(findViewById12, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvCyphCode = (AppCompatTextView) findViewById12;
        final View findViewById13 = view.findViewById(R.id.tvSalesman);
        Intrinsics.checkNotNull(findViewById13, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvSalesman = (AppCompatTextView) findViewById13;
        final View findViewById14 = view.findViewById(R.id.tvProjectCode);
        Intrinsics.checkNotNull(findViewById14, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvProjectCode = (AppCompatTextView) findViewById14;
        final View findViewById15 = view.findViewById(R.id.tvShipAccount);
        Intrinsics.checkNotNull(findViewById15, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvShipAccount = (AppCompatTextView) findViewById15;
        final View findViewById16 = view.findViewById(R.id.tvShipAddress);
        Intrinsics.checkNotNull(findViewById16, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvShipAddress = (AppCompatTextView) findViewById16;
        final View findViewById17 = view.findViewById(R.id.tvShipDeliveryMethod);
        Intrinsics.checkNotNull(findViewById17, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvShipDeliveryMethod = (AppCompatTextView) findViewById17;
        final View findViewById18 = view.findViewById(R.id.tvShipAgent);
        Intrinsics.checkNotNull(findViewById18, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvShipAgent = (AppCompatTextView) findViewById18;
        final View findViewById19 = view.findViewById(R.id.tvShipTransType);
        Intrinsics.checkNotNull(findViewById19, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvShipTransType = (AppCompatTextView) findViewById19;
        final View findViewById20 = view.findViewById(R.id.tvDesc1);
        Intrinsics.checkNotNull(findViewById20, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDesc1 = (AppCompatTextView) findViewById20;
        final View findViewById21 = view.findViewById(R.id.tvDesc2);
        Intrinsics.checkNotNull(findViewById21, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDesc2 = (AppCompatTextView) findViewById21;
        final View findViewById22 = view.findViewById(R.id.tvDesc3);
        Intrinsics.checkNotNull(findViewById22, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDesc3 = (AppCompatTextView) findViewById22;
        final View findViewById23 = view.findViewById(R.id.tvDesc4);
        Intrinsics.checkNotNull(findViewById23, "null cannot be cast to non-null type androidx.appcompat.widget.AppCompatTextView");
        tvDesc4 = (AppCompatTextView) findViewById23;
        reportWcfQueriesRepository = new ReportWcfQueriesRepository();
        ReportWcfQueriesRepository reportWcfQueriesRepository = this.reportWcfQueriesRepository;
        if (null == reportWcfQueriesRepository) {
            Intrinsics.throwUninitializedPropertyAccessException("reportWcfQueriesRepository");
            reportWcfQueriesRepository = null;
        }
        reportWcfQueriesViewModel = new ReportWcfQueriesViewModel(reportWcfQueriesRepository);
    }
}
