package com.fasterxml.jackson.databind.node;

import com.fasterxml.jackson.core.Base64Variant;
import com.fasterxml.jackson.core.Base64Variants;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.SerializerProvider;
import java.io.IOException;
import java.util.Arrays;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class BinaryNode extends ValueNode {
    static final BinaryNode EMPTY_BINARY_NODE = new BinaryNode(new byte[0]);
    private static final long serialVersionUID = 2;
    protected final byte[] _data;

    public BinaryNode(final byte[] bArr) {
        _data = bArr;
    }

    public BinaryNode(final byte[] bArr, final int i2, final int i3) {
        if (0 == i2 && i3 == bArr.length) {
            _data = bArr;
            return;
        }
        final byte[] bArr2 = new byte[i3];
        _data = bArr2;
        System.arraycopy(bArr, i2, bArr2, 0, i3);
    }

    public static BinaryNode valueOf(final byte[] bArr) {
        if (null == bArr) {
            return null;
        }
        if (0 == bArr.length) {
            return BinaryNode.EMPTY_BINARY_NODE;
        }
        return new BinaryNode(bArr);
    }

    public static BinaryNode valueOf(final byte[] bArr, final int i2, final int i3) {
        if (null == bArr) {
            return null;
        }
        if (0 == i3) {
            return BinaryNode.EMPTY_BINARY_NODE;
        }
        return new BinaryNode(bArr, i2, i3);
    }

    @Override // com.fasterxml.jackson.databind.JsonNode
    public JsonNodeType getNodeType() {
        return JsonNodeType.BINARY;
    }

    @Override // com.fasterxml.jackson.databind.node.ValueNode, com.fasterxml.jackson.databind.node.BaseJsonNode, com.fasterxml.jackson.core.TreeNode
    public JsonToken asToken() {
        return JsonToken.VALUE_EMBEDDED_OBJECT;
    }

    @Override // com.fasterxml.jackson.databind.JsonNode
    public byte[] binaryValue() {
        return _data;
    }

    @Override // com.fasterxml.jackson.databind.JsonNode
    public String asText() {
        return Base64Variants.getDefaultVariant().encode(_data, false);
    }

    @Override // com.fasterxml.jackson.databind.node.BaseJsonNode, com.fasterxml.jackson.databind.JsonSerializable
    public final void serialize(final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws IOException {
        final Base64Variant base64Variant = serializerProvider.getConfig().getBase64Variant();
        final byte[] bArr = _data;
        jsonGenerator.writeBinary(base64Variant, bArr, 0, bArr.length);
    }

    @Override // com.fasterxml.jackson.databind.JsonNode
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (null != obj && (obj instanceof BinaryNode)) {
            return Arrays.equals(((BinaryNode) obj)._data, _data);
        }
        return false;
    }

    @Override // com.fasterxml.jackson.databind.node.BaseJsonNode
    public int hashCode() {
        final byte[] bArr = _data;
        if (null == bArr) {
            return -1;
        }
        return bArr.length;
    }
}
