package com.fasterxml.jackson.databind.util;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class ByteBufferBackedOutputStream extends OutputStream {

    /* renamed from: _b */
    protected final ByteBuffer f805_b;

    public ByteBufferBackedOutputStream(final ByteBuffer byteBuffer) {
        f805_b = byteBuffer;
    }

    @Override // java.io.OutputStream
    public void write(final int i2) throws IOException {
        f805_b.put((byte) i2);
    }

    @Override // java.io.OutputStream
    public void write(final byte[] bArr, final int i2, final int i3) throws IOException {
        f805_b.put(bArr, i2, i3);
    }
}
