package com.fasterxml.jackson.databind.util;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public final class CompactStringObjectMap implements Serializable {
    private static final CompactStringObjectMap EMPTY = new CompactStringObjectMap(1, 0, new Object[4]);
    private static final long serialVersionUID = 1;
    private final Object[] _hashArea;
    private final int _hashMask;
    private final int _spillCount;

    private static int findSize(final int i2) {
        if (5 >= i2) {
            return 8;
        }
        if (12 >= i2) {
            return 16;
        }
        int i3 = 32;
        while (i3 < i2 + (i2 >> 2)) {
            i3 += i3;
        }
        return i3;
    }

    private CompactStringObjectMap(final int i2, final int i3, final Object[] objArr) {
        _hashMask = i2;
        _spillCount = i3;
        _hashArea = objArr;
    }

    public static <T> CompactStringObjectMap construct(final Map<String, T> map) {
        if (map.isEmpty()) {
            return CompactStringObjectMap.EMPTY;
        }
        final int iFindSize = CompactStringObjectMap.findSize(map.size());
        final int i2 = iFindSize - 1;
        final int i3 = (iFindSize >> 1) + iFindSize;
        Object[] objArrCopyOf = new Object[i3 * 2];
        int i4 = 0;
        for (final Map.Entry<String, T> entry : map.entrySet()) {
            final String key = entry.getKey();
            if (null != key) {
                final int iHashCode = key.hashCode() & i2;
                int i5 = iHashCode + iHashCode;
                if (null != objArrCopyOf[i5]) {
                    i5 = ((iHashCode >> 1) + iFindSize) << 1;
                    if (null != objArrCopyOf[i5]) {
                        i5 = (i3 << 1) + i4;
                        i4 += 2;
                        if (i5 >= objArrCopyOf.length) {
                            objArrCopyOf = Arrays.copyOf(objArrCopyOf, objArrCopyOf.length + 4);
                        }
                    }
                }
                objArrCopyOf[i5] = key;
                objArrCopyOf[i5 + 1] = entry.getValue();
            }
        }
        return new CompactStringObjectMap(i2, i4, objArrCopyOf);
    }

    public Object find(final String str) {
        final int iHashCode = str.hashCode() & _hashMask;
        final int i2 = iHashCode << 1;
        final Object obj = _hashArea[i2];
        if (obj == str || str.equals(obj)) {
            return _hashArea[i2 + 1];
        }
        return this._find2(str, iHashCode, obj);
    }

    private Object _find2(final String str, final int i2, final Object obj) {
        if (null == obj) {
            return null;
        }
        final int i3 = _hashMask + 1;
        final int i4 = ((i2 >> 1) + i3) << 1;
        final Object obj2 = _hashArea[i4];
        if (str.equals(obj2)) {
            return _hashArea[i4 + 1];
        }
        if (null != obj2) {
            int i5 = (i3 + (i3 >> 1)) << 1;
            final int i6 = _spillCount + i5;
            while (i5 < i6) {
                final Object obj3 = _hashArea[i5];
                if (obj3 == str || str.equals(obj3)) {
                    return _hashArea[i5 + 1];
                }
                i5 += 2;
            }
        }
        return null;
    }

    public Object findCaseInsensitive(final String str) {
        final int length = _hashArea.length;
        for (int i2 = 0; i2 < length; i2 += 2) {
            final Object obj = _hashArea[i2];
            if (null != obj && ((String) obj).equalsIgnoreCase(str)) {
                return _hashArea[i2 + 1];
            }
        }
        return null;
    }

    public List<String> keys() {
        final int length = _hashArea.length;
        final ArrayList arrayList = new ArrayList(length >> 2);
        for (int i2 = 0; i2 < length; i2 += 2) {
            final Object obj = _hashArea[i2];
            if (null != obj) {
                arrayList.add(obj);
            }
        }
        return arrayList;
    }
}
