package com.fasterxml.jackson.databind.ser;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.ser.std.MapSerializer;

import java.util.Map;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class AnyGetterWriter {
    protected final AnnotatedMember _accessor;
    protected MapSerializer _mapSerializer;
    protected final BeanProperty _property;
    protected JsonSerializer<Object> _serializer;

    public AnyGetterWriter(final BeanProperty beanProperty, final AnnotatedMember annotatedMember, final JsonSerializer<?> jsonSerializer) {
        _accessor = annotatedMember;
        _property = beanProperty;
        _serializer = jsonSerializer;
        if (jsonSerializer instanceof MapSerializer) {
            _mapSerializer = (MapSerializer) jsonSerializer;
        }
    }

    public void fixAccess(final SerializationConfig serializationConfig) {
        _accessor.fixAccess(serializationConfig.isEnabled(MapperFeature.OVERRIDE_PUBLIC_ACCESS_MODIFIERS));
    }

    public void getAndSerialize(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws Exception {
        final Object value = _accessor.getValue(obj);
        if (null == value) {
            return;
        }
        if (!(value instanceof Map)) {
            serializerProvider.reportBadDefinition(_property.getType(), String.format("Value returned by 'any-getter' %s() not java.util.Map but %s", _accessor.getName(), value.getClass().getName()));
        }
        final MapSerializer mapSerializer = _mapSerializer;
        if (null != mapSerializer) {
            mapSerializer.serializeWithoutTypeInfo((Map) value, jsonGenerator, serializerProvider);
        } else {
            _serializer.serialize(value, jsonGenerator, serializerProvider);
        }
    }

    public void getAndFilter(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider, final PropertyFilter propertyFilter) throws Exception {
        final Object value = _accessor.getValue(obj);
        if (null == value) {
            return;
        }
        if (!(value instanceof Map)) {
            serializerProvider.reportBadDefinition(_property.getType(), String.format("Value returned by 'any-getter' (%s()) not java.util.Map but %s", _accessor.getName(), value.getClass().getName()));
        }
        final MapSerializer mapSerializer = _mapSerializer;
        if (null != mapSerializer) {
            mapSerializer.serializeFilteredAnyProperties(serializerProvider, jsonGenerator, obj, (Map) value, propertyFilter, null);
        } else {
            _serializer.serialize(value, jsonGenerator, serializerProvider);
        }
    }

    public void resolve(final SerializerProvider serializerProvider) throws JsonMappingException {
        final JsonSerializer<?> jsonSerializer = _serializer;
        if (jsonSerializer instanceof ContextualSerializer) {
            final JsonSerializer<?> jsonSerializerHandlePrimaryContextualization = serializerProvider.handlePrimaryContextualization(jsonSerializer, _property);
            _serializer = jsonSerializerHandlePrimaryContextualization;
            if (jsonSerializerHandlePrimaryContextualization instanceof MapSerializer) {
                _mapSerializer = (MapSerializer) jsonSerializerHandlePrimaryContextualization;
            }
        }
    }
}
