package com.fasterxml.jackson.databind.ser;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.SerializableString;
import com.fasterxml.jackson.core.io.SerializedString;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.JacksonStdImpl;
import com.fasterxml.jackson.databind.introspect.AnnotatedField;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.introspect.AnnotatedMethod;
import com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonObjectFormatVisitor;
import com.fasterxml.jackson.databind.jsonschema.JsonSchema;
import com.fasterxml.jackson.databind.jsonschema.SchemaAware;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap;
import com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter;
import com.fasterxml.jackson.databind.ser.std.BeanSerializerBase;
import com.fasterxml.jackson.databind.util.Annotations;
import com.fasterxml.jackson.databind.util.ClassUtil;
import com.fasterxml.jackson.databind.util.NameTransformer;

import java.io.IOException;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Type;
import java.util.HashMap;

// Class generated by  decompiler (1.5.3)
@JacksonStdImpl
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class BeanPropertyWriter extends PropertyWriter {
    public static final Object MARKER_FOR_EMPTY = JsonInclude.Include.NON_EMPTY;
    private static final long serialVersionUID = 1;
    protected transient Method _accessorMethod;
    protected final JavaType _cfgSerializationType;
    protected final transient Annotations _contextAnnotations;
    protected final JavaType _declaredType;
    protected transient PropertySerializerMap _dynamicSerializers;
    protected transient Field _field;
    protected final Class<?>[] _includeInViews;
    protected transient HashMap<Object, Object> _internalSettings;
    protected final AnnotatedMember _member;
    protected final SerializedString _name;
    protected JavaType _nonTrivialBaseType;
    protected JsonSerializer<Object> _nullSerializer;
    protected JsonSerializer<Object> _serializer;
    protected final boolean _suppressNulls;
    protected final Object _suppressableValue;
    protected TypeSerializer _typeSerializer;
    protected final PropertyName _wrapperName;

    public boolean isUnwrapping() {
        return false;
    }

    public BeanPropertyWriter(final BeanPropertyDefinition beanPropertyDefinition, final AnnotatedMember annotatedMember, final Annotations annotations, final JavaType javaType, final JsonSerializer<?> jsonSerializer, final TypeSerializer typeSerializer, final JavaType javaType2, final boolean z, final Object obj, final Class<?>[] clsArr) {
        super(beanPropertyDefinition);
        _member = annotatedMember;
        _contextAnnotations = annotations;
        _name = new SerializedString(beanPropertyDefinition.getName());
        _wrapperName = beanPropertyDefinition.getWrapperName();
        _declaredType = javaType;
        _serializer = jsonSerializer;
        _dynamicSerializers = null == jsonSerializer ? PropertySerializerMap.emptyForProperties() : null;
        _typeSerializer = typeSerializer;
        _cfgSerializationType = javaType2;
        if (annotatedMember instanceof AnnotatedField) {
            _accessorMethod = null;
            _field = (Field) annotatedMember.getMember();
        } else if (annotatedMember instanceof AnnotatedMethod) {
            _accessorMethod = (Method) annotatedMember.getMember();
            _field = null;
        } else {
            _accessorMethod = null;
            _field = null;
        }
        _suppressNulls = z;
        _suppressableValue = obj;
        _nullSerializer = null;
        _includeInViews = clsArr;
    }

    @Deprecated
    public BeanPropertyWriter(final BeanPropertyDefinition beanPropertyDefinition, final AnnotatedMember annotatedMember, final Annotations annotations, final JavaType javaType, final JsonSerializer<?> jsonSerializer, final TypeSerializer typeSerializer, final JavaType javaType2, final boolean z, final Object obj) {
        this(beanPropertyDefinition, annotatedMember, annotations, javaType, jsonSerializer, typeSerializer, javaType2, z, obj, null);
    }

    protected BeanPropertyWriter() {
        super(PropertyMetadata.STD_REQUIRED_OR_OPTIONAL);
        _member = null;
        _contextAnnotations = null;
        _name = null;
        _wrapperName = null;
        _includeInViews = null;
        _declaredType = null;
        _serializer = null;
        _dynamicSerializers = null;
        _typeSerializer = null;
        _cfgSerializationType = null;
        _accessorMethod = null;
        _field = null;
        _suppressNulls = false;
        _suppressableValue = null;
        _nullSerializer = null;
    }

    protected BeanPropertyWriter(final BeanPropertyWriter beanPropertyWriter) {
        this(beanPropertyWriter, beanPropertyWriter._name);
    }

    protected BeanPropertyWriter(final BeanPropertyWriter beanPropertyWriter, final PropertyName propertyName) {
        super(beanPropertyWriter);
        _name = new SerializedString(propertyName.getSimpleName());
        _wrapperName = beanPropertyWriter._wrapperName;
        _contextAnnotations = beanPropertyWriter._contextAnnotations;
        _declaredType = beanPropertyWriter._declaredType;
        _member = beanPropertyWriter._member;
        _accessorMethod = beanPropertyWriter._accessorMethod;
        _field = beanPropertyWriter._field;
        _serializer = beanPropertyWriter._serializer;
        _nullSerializer = beanPropertyWriter._nullSerializer;
        if (null != beanPropertyWriter._internalSettings) {
            _internalSettings = new HashMap<>(beanPropertyWriter._internalSettings);
        }
        _cfgSerializationType = beanPropertyWriter._cfgSerializationType;
        _dynamicSerializers = beanPropertyWriter._dynamicSerializers;
        _suppressNulls = beanPropertyWriter._suppressNulls;
        _suppressableValue = beanPropertyWriter._suppressableValue;
        _includeInViews = beanPropertyWriter._includeInViews;
        _typeSerializer = beanPropertyWriter._typeSerializer;
        _nonTrivialBaseType = beanPropertyWriter._nonTrivialBaseType;
    }

    protected BeanPropertyWriter(final BeanPropertyWriter beanPropertyWriter, final SerializedString serializedString) {
        super(beanPropertyWriter);
        _name = serializedString;
        _wrapperName = beanPropertyWriter._wrapperName;
        _member = beanPropertyWriter._member;
        _contextAnnotations = beanPropertyWriter._contextAnnotations;
        _declaredType = beanPropertyWriter._declaredType;
        _accessorMethod = beanPropertyWriter._accessorMethod;
        _field = beanPropertyWriter._field;
        _serializer = beanPropertyWriter._serializer;
        _nullSerializer = beanPropertyWriter._nullSerializer;
        if (null != beanPropertyWriter._internalSettings) {
            _internalSettings = new HashMap<>(beanPropertyWriter._internalSettings);
        }
        _cfgSerializationType = beanPropertyWriter._cfgSerializationType;
        _dynamicSerializers = beanPropertyWriter._dynamicSerializers;
        _suppressNulls = beanPropertyWriter._suppressNulls;
        _suppressableValue = beanPropertyWriter._suppressableValue;
        _includeInViews = beanPropertyWriter._includeInViews;
        _typeSerializer = beanPropertyWriter._typeSerializer;
        _nonTrivialBaseType = beanPropertyWriter._nonTrivialBaseType;
    }

    public BeanPropertyWriter rename(final NameTransformer nameTransformer) {
        final String strTransform = nameTransformer.transform(_name.getValue());
        return strTransform.equals(_name.toString()) ? this : this._new(PropertyName.construct(strTransform));
    }

    protected BeanPropertyWriter _new(final PropertyName propertyName) {
        return new BeanPropertyWriter(this, propertyName);
    }

    public void assignTypeSerializer(final TypeSerializer typeSerializer) {
        _typeSerializer = typeSerializer;
    }

    public void assignSerializer(final JsonSerializer<Object> jsonSerializer) {
        final JsonSerializer<Object> jsonSerializer2 = _serializer;
        if (null != jsonSerializer2 && jsonSerializer2 != jsonSerializer) {
            throw new IllegalStateException(String.format("Cannot override _serializer: had a %s, trying to set to %s", ClassUtil.classNameOf(_serializer), ClassUtil.classNameOf(jsonSerializer)));
        }
        _serializer = jsonSerializer;
    }

    public void assignNullSerializer(final JsonSerializer<Object> jsonSerializer) {
        final JsonSerializer<Object> jsonSerializer2 = _nullSerializer;
        if (null != jsonSerializer2 && jsonSerializer2 != jsonSerializer) {
            throw new IllegalStateException(String.format("Cannot override _nullSerializer: had a %s, trying to set to %s", ClassUtil.classNameOf(_nullSerializer), ClassUtil.classNameOf(jsonSerializer)));
        }
        _nullSerializer = jsonSerializer;
    }

    public BeanPropertyWriter unwrappingWriter(final NameTransformer nameTransformer) {
        return new UnwrappingBeanPropertyWriter(this, nameTransformer);
    }

    public void setNonTrivialBaseType(final JavaType javaType) {
        _nonTrivialBaseType = javaType;
    }

    public void fixAccess(final SerializationConfig serializationConfig) {
        _member.fixAccess(serializationConfig.isEnabled(MapperFeature.OVERRIDE_PUBLIC_ACCESS_MODIFIERS));
    }

    Object readResolve() {
        final AnnotatedMember annotatedMember = _member;
        if (annotatedMember instanceof AnnotatedField) {
            _accessorMethod = null;
            _field = (Field) annotatedMember.getMember();
        } else if (annotatedMember instanceof AnnotatedMethod) {
            _accessorMethod = (Method) annotatedMember.getMember();
            _field = null;
        }
        if (null == this._serializer) {
            _dynamicSerializers = PropertySerializerMap.emptyForProperties();
        }
        return this;
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty, com.fasterxml.jackson.databind.util.Named
    public String getName() {
        return _name.getValue();
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public PropertyName getFullName() {
        return new PropertyName(_name.getValue());
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public JavaType getType() {
        return _declaredType;
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public PropertyName getWrapperName() {
        return _wrapperName;
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public <A extends Annotation> A getAnnotation(final Class<A> cls) {
        final AnnotatedMember annotatedMember = _member;
        if (null == annotatedMember) {
            return null;
        }
        return annotatedMember.getAnnotation(cls);
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public <A extends Annotation> A getContextAnnotation(final Class<A> cls) {
        final Annotations annotations = _contextAnnotations;
        if (null == annotations) {
            return null;
        }
        return annotations.get(cls);
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public AnnotatedMember getMember() {
        return _member;
    }

    protected void _depositSchemaProperty(final ObjectNode objectNode, final JsonNode jsonNode) {
        objectNode.set(this.getName(), jsonNode);
    }

    public Object getInternalSetting(final Object obj) {
        final HashMap<Object, Object> map = _internalSettings;
        if (null == map) {
            return null;
        }
        return map.get(obj);
    }

    public Object setInternalSetting(final Object obj, final Object obj2) {
        if (null == this._internalSettings) {
            _internalSettings = new HashMap<>();
        }
        return _internalSettings.put(obj, obj2);
    }

    public Object removeInternalSetting(final Object obj) {
        final HashMap<Object, Object> map = _internalSettings;
        if (null == map) {
            return null;
        }
        final Object objRemove = map.remove(obj);
        if (0 == this._internalSettings.size()) {
            _internalSettings = null;
        }
        return objRemove;
    }

    public SerializableString getSerializedName() {
        return _name;
    }

    public boolean hasSerializer() {
        return null != this._serializer;
    }

    public boolean hasNullSerializer() {
        return null != this._nullSerializer;
    }

    public TypeSerializer getTypeSerializer() {
        return _typeSerializer;
    }

    public boolean willSuppressNulls() {
        return _suppressNulls;
    }

    public boolean wouldConflictWithName(final PropertyName propertyName) {
        final PropertyName propertyName2 = _wrapperName;
        if (null != propertyName2) {
            return propertyName2.equals(propertyName);
        }
        return propertyName.hasSimpleName(_name.getValue()) && !propertyName.hasNamespace();
    }

    public JsonSerializer<Object> getSerializer() {
        return _serializer;
    }

    public JavaType getSerializationType() {
        return _cfgSerializationType;
    }

    @Deprecated
    public Class<?> getRawSerializationType() {
        final JavaType javaType = _cfgSerializationType;
        if (null == javaType) {
            return null;
        }
        return javaType.getRawClass();
    }

    @Deprecated
    public Class<?> getPropertyType() {
        final Method method = _accessorMethod;
        if (null != method) {
            return method.getReturnType();
        }
        final Field field = _field;
        if (null != field) {
            return field.getType();
        }
        return null;
    }

    @Deprecated
    public Type getGenericPropertyType() {
        final Method method = _accessorMethod;
        if (null != method) {
            return method.getGenericReturnType();
        }
        final Field field = _field;
        if (null != field) {
            return field.getGenericType();
        }
        return null;
    }

    public Class<?>[] getViews() {
        return _includeInViews;
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter
    public void serializeAsField(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws Exception {
        final Method method = _accessorMethod;
        final Object objInvoke = null == method ? _field.get(obj) : method.invoke(obj, null);
        if (null == objInvoke) {
            if (null != this._nullSerializer) {
                jsonGenerator.writeFieldName(_name);
                _nullSerializer.serialize(null, jsonGenerator, serializerProvider);
                return;
            }
            return;
        }
        JsonSerializer<?> jsonSerializer_findAndAddDynamic = _serializer;
        if (null == jsonSerializer_findAndAddDynamic) {
            final Class<?> cls = objInvoke.getClass();
            final PropertySerializerMap propertySerializerMap = _dynamicSerializers;
            final JsonSerializer<?> jsonSerializerSerializerFor = propertySerializerMap.serializerFor(cls);
            jsonSerializer_findAndAddDynamic = null == jsonSerializerSerializerFor ? this._findAndAddDynamic(propertySerializerMap, cls, serializerProvider) : jsonSerializerSerializerFor;
        }
        final Object obj2 = _suppressableValue;
        if (null != obj2) {
            if (BeanPropertyWriter.MARKER_FOR_EMPTY == obj2) {
                if (jsonSerializer_findAndAddDynamic.isEmpty(serializerProvider, objInvoke)) {
                    return;
                }
            } else if (obj2.equals(objInvoke)) {
                return;
            }
        }
        if (objInvoke == obj && this._handleSelfReference(obj, jsonGenerator, serializerProvider, jsonSerializer_findAndAddDynamic)) {
            return;
        }
        jsonGenerator.writeFieldName(_name);
        final TypeSerializer typeSerializer = _typeSerializer;
        if (null == typeSerializer) {
            jsonSerializer_findAndAddDynamic.serialize(objInvoke, jsonGenerator, serializerProvider);
        } else {
            jsonSerializer_findAndAddDynamic.serializeWithType(objInvoke, jsonGenerator, serializerProvider, typeSerializer);
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter
    public void serializeAsOmittedField(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws Exception {
        if (jsonGenerator.canOmitFields()) {
            return;
        }
        jsonGenerator.writeOmittedField(_name.getValue());
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter
    public void serializeAsElement(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws Exception {
        final Method method = _accessorMethod;
        final Object objInvoke = null == method ? _field.get(obj) : method.invoke(obj, null);
        if (null == objInvoke) {
            final JsonSerializer<Object> jsonSerializer = _nullSerializer;
            if (null != jsonSerializer) {
                jsonSerializer.serialize(null, jsonGenerator, serializerProvider);
                return;
            } else {
                jsonGenerator.writeNull();
                return;
            }
        }
        JsonSerializer<?> jsonSerializer_findAndAddDynamic = _serializer;
        if (null == jsonSerializer_findAndAddDynamic) {
            final Class<?> cls = objInvoke.getClass();
            final PropertySerializerMap propertySerializerMap = _dynamicSerializers;
            final JsonSerializer<?> jsonSerializerSerializerFor = propertySerializerMap.serializerFor(cls);
            jsonSerializer_findAndAddDynamic = null == jsonSerializerSerializerFor ? this._findAndAddDynamic(propertySerializerMap, cls, serializerProvider) : jsonSerializerSerializerFor;
        }
        final Object obj2 = _suppressableValue;
        if (null != obj2) {
            if (BeanPropertyWriter.MARKER_FOR_EMPTY == obj2) {
                if (jsonSerializer_findAndAddDynamic.isEmpty(serializerProvider, objInvoke)) {
                    this.serializeAsPlaceholder(obj, jsonGenerator, serializerProvider);
                    return;
                }
            } else if (obj2.equals(objInvoke)) {
                this.serializeAsPlaceholder(obj, jsonGenerator, serializerProvider);
                return;
            }
        }
        if (objInvoke == obj && this._handleSelfReference(obj, jsonGenerator, serializerProvider, jsonSerializer_findAndAddDynamic)) {
            return;
        }
        final TypeSerializer typeSerializer = _typeSerializer;
        if (null == typeSerializer) {
            jsonSerializer_findAndAddDynamic.serialize(objInvoke, jsonGenerator, serializerProvider);
        } else {
            jsonSerializer_findAndAddDynamic.serializeWithType(objInvoke, jsonGenerator, serializerProvider, typeSerializer);
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter
    public void serializeAsPlaceholder(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider) throws Exception {
        final JsonSerializer<Object> jsonSerializer = _nullSerializer;
        if (null != jsonSerializer) {
            jsonSerializer.serialize(null, jsonGenerator, serializerProvider);
        } else {
            jsonGenerator.writeNull();
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter, com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, com.fasterxml.jackson.databind.BeanProperty
    public void depositSchemaProperty(final JsonObjectFormatVisitor jsonObjectFormatVisitor, final SerializerProvider serializerProvider) throws JsonMappingException {
        if (null != jsonObjectFormatVisitor) {
            if (this.isRequired()) {
                jsonObjectFormatVisitor.property(this);
            } else {
                jsonObjectFormatVisitor.optionalProperty(this);
            }
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.PropertyWriter
    @Deprecated
    public void depositSchemaProperty(final ObjectNode objectNode, final SerializerProvider serializerProvider) throws JsonMappingException {
        final JsonNode defaultSchemaNode;
        final JavaType serializationType = this._cfgSerializationType;
        final Type type = null == serializationType ? this._declaredType : serializationType.getRawClass();
        Object serializer = this._serializer;
        if (null == serializer) {
            serializer = serializerProvider.findValueSerializer(this._declaredType, this);
        }
        final boolean z = !this.isRequired();
        if (serializer instanceof SchemaAware) {
            defaultSchemaNode = ((SchemaAware) serializer).getSchema(serializerProvider, type, z);
        } else {
            defaultSchemaNode = JsonSchema.getDefaultSchemaNode();
        }
        this._depositSchemaProperty(objectNode, defaultSchemaNode);
    }

    protected JsonSerializer<Object> _findAndAddDynamic(final PropertySerializerMap propertySerializerMap, final Class<?> cls, final SerializerProvider serializerProvider) throws JsonMappingException {
        final PropertySerializerMap.SerializerAndMapResult serializerAndMapResultFindAndAddPrimarySerializer;
        final JavaType javaType = _nonTrivialBaseType;
        if (null != javaType) {
            serializerAndMapResultFindAndAddPrimarySerializer = propertySerializerMap.findAndAddPrimarySerializer(serializerProvider.constructSpecializedType(javaType, cls), serializerProvider, this);
        } else {
            serializerAndMapResultFindAndAddPrimarySerializer = propertySerializerMap.findAndAddPrimarySerializer(cls, serializerProvider, this);
        }
        final PropertySerializerMap propertySerializerMap2 = serializerAndMapResultFindAndAddPrimarySerializer.map();
        if (propertySerializerMap != propertySerializerMap2) {
            _dynamicSerializers = propertySerializerMap2;
        }
        return serializerAndMapResultFindAndAddPrimarySerializer.serializer();
    }

    public final Object get(final Object obj) throws Exception {
        final Method method = _accessorMethod;
        return null == method ? _field.get(obj) : method.invoke(obj, null);
    }

    protected boolean _handleSelfReference(final Object obj, final JsonGenerator jsonGenerator, final SerializerProvider serializerProvider, final JsonSerializer<?> jsonSerializer) throws IOException {
        if (jsonSerializer.usesObjectId()) {
            return false;
        }
        if (serializerProvider.isEnabled(SerializationFeature.FAIL_ON_SELF_REFERENCES)) {
            if (!(jsonSerializer instanceof BeanSerializerBase)) {
                return false;
            }
            serializerProvider.reportBadDefinition(this._declaredType, "Direct self-reference leading to cycle");
            return false;
        }
        if (!serializerProvider.isEnabled(SerializationFeature.WRITE_SELF_REFERENCES_AS_NULL)) {
            return false;
        }
        if (null == this._nullSerializer) {
            return true;
        }
        if (!jsonGenerator.getOutputContext().inArray()) {
            jsonGenerator.writeFieldName(_name);
        }
        _nullSerializer.serialize(null, jsonGenerator, serializerProvider);
        return true;
    }

    public String toString() {
        final StringBuilder sb = new StringBuilder(40);
        sb.append("property '");
        sb.append(this.getName());
        sb.append("' (");
        if (null != this._accessorMethod) {
            sb.append("via method ");
            sb.append(_accessorMethod.getDeclaringClass().getName());
            sb.append("#");
            sb.append(_accessorMethod.getName());
        } else if (null != this._field) {
            sb.append("field \"");
            sb.append(_field.getDeclaringClass().getName());
            sb.append("#");
            sb.append(_field.getName());
        } else {
            sb.append("virtual");
        }
        if (null == this._serializer) {
            sb.append(", no static serializer");
        } else {
            sb.append(", static serializer of type " + _serializer.getClass().getName());
        }
        sb.append(')');
        return sb.toString();
    }
}
