package okhttp3;

import java.net.Socket;

// Class generated by  decompiler (1.5.3)
/* compiled from: Connection.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public interface Connection {
    Handshake handshake();

    Protocol protocol();

    Route route();

    Socket socket();
}
