package okhttp3;

import androidx.core.location.LocationRequestCompat;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import kotlin.text.Regex;
import kotlin.text.StringsKt;
import okhttp3.internal.Util;
import okhttp3.internal.hostnames;
import okhttp3.internal.http.dates;
import okhttp3.internal.publicsuffix.PublicSuffixDatabase;
import org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement;
import org.springframework.http.HttpHeaders;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static kotlin.jvm.internal.Intrinsics.*;

// Class generated by  decompiler (1.5.3)
/* compiled from: Cookie.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class Cookie {
    public static final Companion Companion = new Companion(null);
    private static final Pattern YEAR_PATTERN = Pattern.compile("(\\d{2,4})[^\\d]*");
    private static final Pattern MONTH_PATTERN = Pattern.compile("(?i)(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec).*");
    private static final Pattern DAY_OF_MONTH_PATTERN = Pattern.compile("(\\d{1,2})[^\\d]*");
    private static final Pattern TIME_PATTERN = Pattern.compile("(\\d{1,2}):(\\d{1,2}):(\\d{1,2})[^\\d]*");
    private final String domain;
    private final long expiresAt;
    private final boolean hostOnly;
    private final boolean httpOnly;
    private final String name;
    private final String path;
    private final boolean persistent;
    private final boolean secure;
    private final String value;

    public Cookie(final String str, final String str2, final long j2, final String str3, final String str4, final boolean z, final boolean z2, final boolean z3, final boolean z4, final DefaultConstructorMarker defaultConstructorMarker) {
        this(str, str2, j2, str3, str4, z, z2, z3, z4);
    }

    private Cookie(final String str, final String str2, final long j2, final String str3, final String str4, final boolean z, final boolean z2, final boolean z3, final boolean z4) {
        name = str;
        value = str2;
        expiresAt = j2;
        domain = str3;
        path = str4;
        secure = z;
        httpOnly = z2;
        persistent = z3;
        hostOnly = z4;
    }

    public static Cookie parse(final HttpUrl httpUrl, final String str) {
        return Cookie.Companion.parse(httpUrl, str);
    }

    public static List<Cookie> parseAll(final HttpUrl httpUrl, final Headers headers) {
        return Cookie.Companion.parseAll(httpUrl, headers);
    }

    public String name() {
        return name;
    }

    public String value() {
        return value;
    }

    public long expiresAt() {
        return expiresAt;
    }

    public String domain() {
        return domain;
    }

    public String path() {
        return path;
    }

    public boolean secure() {
        return secure;
    }

    public boolean httpOnly() {
        return httpOnly;
    }

    public boolean persistent() {
        return persistent;
    }

    public boolean hostOnly() {
        return hostOnly;
    }

    public boolean matches(final HttpUrl url) {
        final boolean zDomainMatch;
        Intrinsics.checkNotNullParameter(url, "url");
        if (hostOnly) {
            zDomainMatch = areEqual(url.host(), domain);
        } else {
            zDomainMatch = Cookie.Companion.domainMatch(url.host(), domain);
        }
        if (zDomainMatch && Cookie.Companion.pathMatch(url, path)) {
            return !secure || url.isHttps();
        }
        return false;
    }

    public boolean equals(final Object obj) {
        if (obj instanceof Cookie cookie) {
            return areEqual(cookie.name, name) && areEqual(cookie.value, value) && cookie.expiresAt == expiresAt && areEqual(cookie.domain, domain) && areEqual(cookie.path, path) && cookie.secure == secure && cookie.httpOnly == httpOnly && cookie.persistent == persistent && cookie.hostOnly == hostOnly;
        }
        return false;
    }

    @IgnoreJRERequirement
    public int hashCode() {
        return ((((((((((((((((527 + name.hashCode()) * 31) + value.hashCode()) * 31) + Long.hashCode(expiresAt)) * 31) + domain.hashCode()) * 31) + path.hashCode()) * 31) + Boolean.hashCode(secure)) * 31) + Boolean.hashCode(httpOnly)) * 31) + Boolean.hashCode(persistent)) * 31) + Boolean.hashCode(hostOnly);
    }

    public String toString() {
        return this.toStringokhttp(false);
    }

    /* renamed from: -deprecated_name, reason: not valid java name */
    public String m1749deprecated_name() {
        return name;
    }

    /* renamed from: -deprecated_value, reason: not valid java name */
    public String m1753deprecated_value() {
        return value;
    }

    /* renamed from: -deprecated_persistent, reason: not valid java name */
    public boolean m1751deprecated_persistent() {
        return persistent;
    }

    /* renamed from: -deprecated_expiresAt, reason: not valid java name */
    public long m1746deprecated_expiresAt() {
        return expiresAt;
    }

    /* renamed from: -deprecated_hostOnly, reason: not valid java name */
    public boolean m1747deprecated_hostOnly() {
        return hostOnly;
    }

    /* renamed from: -deprecated_domain, reason: not valid java name */
    public String m1745deprecated_domain() {
        return domain;
    }

    /* renamed from: -deprecated_path, reason: not valid java name */
    public String m1750deprecated_path() {
        return path;
    }

    /* renamed from: -deprecated_httpOnly, reason: not valid java name */
    public boolean m1748deprecated_httpOnly() {
        return httpOnly;
    }

    /* renamed from: -deprecated_secure, reason: not valid java name */
    public boolean m1752deprecated_secure() {
        return secure;
    }

    public String toStringokhttp(final boolean z) {
        final StringBuilder sb = new StringBuilder();
        sb.append(this.name());
        sb.append('=');
        sb.append(this.value());
        if (this.persistent()) {
            if (Long.MIN_VALUE == expiresAt()) {
                sb.append("; max-age=0");
            } else {
                sb.append("; expires=");
                sb.append(dates.toHttpDateString(new Date(this.expiresAt())));
            }
        }
        if (!this.hostOnly()) {
            sb.append("; domain=");
            if (z) {
                sb.append(".");
            }
            sb.append(this.domain());
        }
        sb.append("; path=");
        sb.append(this.path());
        if (this.secure()) {
            sb.append("; secure");
        }
        if (this.httpOnly()) {
            sb.append("; httponly");
        }
        final String string = sb.toString();
        checkNotNullExpressionValue(string, "toString()");
        return string;
    }

    /* compiled from: Cookie.kt */
    public static final class Builder {
        private String domain;
        private boolean hostOnly;
        private boolean httpOnly;
        private String name;
        private boolean persistent;
        private boolean secure;
        private String value;
        private long expiresAt = dates.MAX_DATE;
        private String path = "/";

        public Builder name(final String name) {
            Intrinsics.checkNotNullParameter(name, "name");
            if (!areEqual(StringsKt.trim(name).toString(), name)) {
                throw new IllegalArgumentException("name is not trimmed");
            }
            this.name = name;
            return this;
        }

        public Builder value(final String value) {
            Intrinsics.checkNotNullParameter(value, "value");
            if (!areEqual(StringsKt.trim(value).toString(), value)) {
                throw new IllegalArgumentException("value is not trimmed");
            }
            this.value = value;
            return this;
        }

        public Builder expiresAt(long j2) {
            if (0 >= j2) {
                j2 = Long.MIN_VALUE;
            }
            if (dates.MAX_DATE < j2) {
                j2 = 253402300799999L;
            }
            expiresAt = j2;
            persistent = true;
            return this;
        }

        public Builder domain(final String domain) {
            Intrinsics.checkNotNullParameter(domain, "domain");
            return this.domain(domain, false);
        }

        public Builder hostOnlyDomain(final String domain) {
            Intrinsics.checkNotNullParameter(domain, "domain");
            return this.domain(domain, true);
        }

        private Builder domain(final String str, final boolean z) {
            final String canonicalHost = hostnames.toCanonicalHost(str);
            if (null == canonicalHost) {
                throw new IllegalArgumentException(stringPlus("unexpected domain: ", str));
            }
            domain = canonicalHost;
            hostOnly = z;
            return this;
        }

        public Builder path(final String path) {
            Intrinsics.checkNotNullParameter(path, "path");
            if (!StringsKt.startsWithdefault(path, "/", false, 2, (Object) null)) {
                throw new IllegalArgumentException("path must start with '/'");
            }
            this.path = path;
            return this;
        }

        public Builder secure() {
            secure = true;
            return this;
        }

        public Builder httpOnly() {
            httpOnly = true;
            return this;
        }

        public Cookie build() {
            final String str = name;
            if (null == str) {
                throw new NullPointerException("builder.name == null");
            }
            final String str2 = value;
            if (null == str2) {
                throw new NullPointerException("builder.value == null");
            }
            final long j2 = expiresAt;
            final String str3 = domain;
            if (null != str3) {
                return new Cookie(str, str2, j2, str3, path, secure, httpOnly, persistent, hostOnly, null);
            }
            throw new NullPointerException("builder.domain == null");
        }
    }

    /* compiled from: Cookie.kt */
    public static final class Companion {
        public Companion(final DefaultConstructorMarker defaultConstructorMarker) {
            this();
        }

        private Companion() {
        }

        private boolean domainMatch(final String str, final String str2) {
            if (areEqual(str, str2)) {
                return true;
            }
            return StringsKt.endsWithdefault(str, str2, false, 2, (Object) null) && '.' == str.charAt((str.length() - str2.length()) - 1) && !Util.canParseAsIpAddress(str);
        }

        private boolean pathMatch(final HttpUrl httpUrl, final String str) {
            final String strEncodedPath = httpUrl.encodedPath();
            if (areEqual(strEncodedPath, str)) {
                return true;
            }
            return StringsKt.startsWithdefault(strEncodedPath, str, false, 2, (Object) null) && (StringsKt.endsWithdefault(str, "/", false, 2, (Object) null) || '/' == strEncodedPath.charAt(str.length()));
        }

        public Cookie parse(final HttpUrl url, final String setCookie) {
            Intrinsics.checkNotNullParameter(url, "url");
            Intrinsics.checkNotNullParameter(setCookie, "setCookie");
            return this.parseokhttp(System.currentTimeMillis(), url, setCookie);
        }

        /*  WARN: Removed duplicated region for block: B:43:0x00d7 A[PHI: r1
  0x00d7: PHI (r1v23 long) = (r1v7 long), (r1v11 long) binds: [B:42:0x00d5, B:53:0x00fd] A[DONT_GENERATE, DONT_INLINE]] */
        /*
            Code decompiled incorrectly, please refer to instructions dump.
        */
        public Cookie parseokhttp(final long j2, final HttpUrl url, final String setCookie) throws NumberFormatException {
            long j3;
            final long j4;
            final Cookie cookie;
            final String str;
            final String str2;
            String strTrimSubstring;
            Intrinsics.checkNotNullParameter(url, "url");
            Intrinsics.checkNotNullParameter(setCookie, "setCookie");
            final int iDelimiterOffsetdefault = Util.delimiterOffset(setCookie, ';', 0, 0, 6, null);
            final int iDelimiterOffsetdefault2 = Util.delimiterOffset(setCookie, '=', 0, iDelimiterOffsetdefault, 2, null);
            if (iDelimiterOffsetdefault2 == iDelimiterOffsetdefault) {
                return null;
            }
            final String strTrimSubstringdefault = Util.trimSubstringdefault(setCookie, 0, iDelimiterOffsetdefault2, 1, null);
            if (0 == strTrimSubstringdefault.length() || -1 != Util.indexOfControlOrNonAscii(strTrimSubstringdefault)) {
                return null;
            }
            final String strTrimSubstring2 = Util.trimSubstring(setCookie, iDelimiterOffsetdefault2 + 1, iDelimiterOffsetdefault);
            if (-1 != Util.indexOfControlOrNonAscii(strTrimSubstring2)) {
                return null;
            }
            int i2 = iDelimiterOffsetdefault + 1;
            final int length = setCookie.length();
            String domain = null;
            String str3 = null;
            boolean z = false;
            boolean z2 = false;
            boolean z3 = false;
            boolean z4 = true;
            long maxAge = -1;
            long expires = dates.MAX_DATE;
            while (i2 < length) {
                final int iDelimiterOffset = Util.delimiterOffset(setCookie, ';', i2, length);
                final int iDelimiterOffset2 = Util.delimiterOffset(setCookie, '=', i2, iDelimiterOffset);
                final String strTrimSubstring3 = Util.trimSubstring(setCookie, i2, iDelimiterOffset2);
                if (iDelimiterOffset2 < iDelimiterOffset) {
                    strTrimSubstring = Util.trimSubstring(setCookie, iDelimiterOffset2 + 1, iDelimiterOffset);
                } else {
                    strTrimSubstring = "";
                }
                if (StringsKt.equals(strTrimSubstring3, "expires", true)) {
                    try {
                        expires = this.parseExpires(strTrimSubstring, 0, strTrimSubstring.length());
                        z3 = true;
                    } catch (final NumberFormatException | IllegalArgumentException unused) {
                    }
                } else if (StringsKt.equals(strTrimSubstring3, "max-age", true)) {
                    maxAge = this.parseMaxAge(strTrimSubstring);
                    z3 = true;
                } else if (StringsKt.equals(strTrimSubstring3, "domain", true)) {
                    domain = this.parseDomain(strTrimSubstring);
                    z4 = false;
                } else if (StringsKt.equals(strTrimSubstring3, "path", true)) {
                    str3 = strTrimSubstring;
                } else if (StringsKt.equals(strTrimSubstring3, "secure", true)) {
                    z = true;
                } else if (StringsKt.equals(strTrimSubstring3, "httponly", true)) {
                    z2 = true;
                }
                i2 = iDelimiterOffset + 1;
            }
            long j5 = Long.MIN_VALUE;
            if (Long.MIN_VALUE != maxAge) {
                if (-1 != maxAge) {
                    j5 = j2 + (9223372036854775L >= maxAge ? maxAge * 1000 : LocationRequestCompat.PASSIVE_INTERVAL);
                    if (j5 >= j2) {
                        j4 = dates.MAX_DATE;
                        if (dates.MAX_DATE >= j5) {
                            j3 = j5;
                        }
                    } else {
                        j4 = dates.MAX_DATE;
                    }
                    j3 = j4;
                } else {
                    j3 = expires;
                }
            }
            final String strHost = url.host();
            if (null == domain) {
                str = strHost;
                cookie = null;
            } else {
                if (!this.domainMatch(strHost, domain)) {
                    return null;
                }
                cookie = null;
                str = domain;
            }
            if (strHost.length() != str.length() && null == PublicSuffixDatabase.Companion.get().getEffectiveTldPlusOne(str)) {
                return cookie;
            }
            String strSubstring = "/";
            final String str4 = str3;
            if (null == str4 || !StringsKt.startsWithdefault(str4, "/", false, 2, (Object) cookie)) {
                final String strEncodedPath = url.encodedPath();
                final int iLastIndexOfdefault = StringsKt.lastIndexOfdefault((CharSequence) strEncodedPath, '/', 0, false, 6, (Object) null);
                if (0 != iLastIndexOfdefault) {
                    strSubstring = strEncodedPath.substring(0, iLastIndexOfdefault);
                    checkNotNullExpressionValue(strSubstring, "this as java.lang.String\u2026ing(startIndex, endIndex)");
                }
                str2 = strSubstring;
            } else {
                str2 = str4;
            }
            return new Cookie(strTrimSubstringdefault, strTrimSubstring2, j3, str, str2, z, z2, z3, z4, null);
        }

        private long parseExpires(final String str, final int i2, final int i3) throws NumberFormatException {
            int iDateCharacterOffset = this.dateCharacterOffset(str, i2, i3, false);
            final Matcher matcher = TIME_PATTERN.matcher(str);
            int i4 = -1;
            int i5 = -1;
            int i6 = -1;
            int iIndexOfdefault = -1;
            int i7 = -1;
            int i8 = -1;
            while (iDateCharacterOffset < i3) {
                final int iDateCharacterOffset2 = this.dateCharacterOffset(str, iDateCharacterOffset + 1, i3, true);
                matcher.region(iDateCharacterOffset, iDateCharacterOffset2);
                if (-1 != i5 || !matcher.usePattern(TIME_PATTERN).matches()) {
                    if (-1 != i6 || !matcher.usePattern(DAY_OF_MONTH_PATTERN).matches()) {
                        if (-1 != iIndexOfdefault || !matcher.usePattern(MONTH_PATTERN).matches()) {
                            if (-1 == i4 && matcher.usePattern(YEAR_PATTERN).matches()) {
                                final String strGroup = matcher.group(1);
                                checkNotNullExpressionValue(strGroup, "matcher.group(1)");
                                i4 = Integer.parseInt(strGroup);
                            }
                        } else {
                            final String strGroup2 = matcher.group(1);
                            checkNotNullExpressionValue(strGroup2, "matcher.group(1)");
                            final Locale US = Locale.US;
                            checkNotNullExpressionValue(US, "US");
                            final String lowerCase = strGroup2.toLowerCase(US);
                            checkNotNullExpressionValue(lowerCase, "this as java.lang.String).toLowerCase(locale)");
                            final String strPattern = MONTH_PATTERN.pattern();
                            checkNotNullExpressionValue(strPattern, "MONTH_PATTERN.pattern()");
                            iIndexOfdefault = StringsKt.indexOfdefault((CharSequence) strPattern, lowerCase, 0, false, 6, (Object) null) / 4;
                        }
                    } else {
                        final String strGroup3 = matcher.group(1);
                        checkNotNullExpressionValue(strGroup3, "matcher.group(1)");
                        i6 = Integer.parseInt(strGroup3);
                    }
                } else {
                    final String strGroup4 = matcher.group(1);
                    checkNotNullExpressionValue(strGroup4, "matcher.group(1)");
                    i5 = Integer.parseInt(strGroup4);
                    final String strGroup5 = matcher.group(2);
                    checkNotNullExpressionValue(strGroup5, "matcher.group(2)");
                    i7 = Integer.parseInt(strGroup5);
                    final String strGroup6 = matcher.group(3);
                    checkNotNullExpressionValue(strGroup6, "matcher.group(3)");
                    i8 = Integer.parseInt(strGroup6);
                }
                iDateCharacterOffset = this.dateCharacterOffset(str, iDateCharacterOffset2 + 1, i3, false);
            }
            if (70 <= i4 && 100 > i4) {
                i4 += 1900;
            }
            if (0 <= i4 && 70 > i4) {
                i4 += 2000;
            }
            if (1601 > i4) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            if (-1 == iIndexOfdefault) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            if (1 > i6 || 32 <= i6) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            if (0 > i5 || 24 <= i5) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            if (0 > i7 || 60 <= i7) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            if (0 > i8 || 60 <= i8) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            final GregorianCalendar gregorianCalendar = new GregorianCalendar(Util.UTC);
            gregorianCalendar.setLenient(false);
            gregorianCalendar.set(1, i4);
            gregorianCalendar.set(2, iIndexOfdefault - 1);
            gregorianCalendar.set(5, i6);
            gregorianCalendar.set(11, i5);
            gregorianCalendar.set(12, i7);
            gregorianCalendar.set(13, i8);
            gregorianCalendar.set(14, 0);
            return gregorianCalendar.getTimeInMillis();
        }

        private int dateCharacterOffset(final String str, int i2, final int i3, final boolean z) {
            while (i2 < i3) {
                final int i4 = i2 + 1;
                final char cCharAt = str.charAt(i2);
                if (((' ' > cCharAt && '\t' != cCharAt) || '\u007f' <= cCharAt || ('9' >= cCharAt && '0' <= cCharAt) || (('z' >= cCharAt && 'a' <= cCharAt) || (('Z' >= cCharAt && 'A' <= cCharAt) || ':' == cCharAt))) == (!z)) {
                    return i2;
                }
                i2 = i4;
            }
            return i3;
        }

        private long parseMaxAge(final String str) throws NumberFormatException {
            try {
                final long j2 = Long.parseLong(str);
                if (0 >= j2) {
                    return Long.MIN_VALUE;
                }
                return j2;
            } catch (final NumberFormatException e2) {
                if (new Regex("-?\\d+").matches(str)) {
                    if (StringsKt.startsWithdefault(str, "-", false, 2, (Object) null)) {
                        return Long.MIN_VALUE;
                    }
                    return LocationRequestCompat.PASSIVE_INTERVAL;
                }
                throw e2;
            }
        }

        private String parseDomain(final String str) {
            if (StringsKt.endsWithdefault(str, ".", false, 2, (Object) null)) {
                throw new IllegalArgumentException("Failed requirement.");
            }
            final String canonicalHost = hostnames.toCanonicalHost(StringsKt.removePrefix(str, "."));
            if (null != canonicalHost) {
                return canonicalHost;
            }
            throw new IllegalArgumentException();
        }

        public List<Cookie> parseAll(final HttpUrl url, final Headers headers) {
            Intrinsics.checkNotNullParameter(url, "url");
            Intrinsics.checkNotNullParameter(headers, "headers");
            final List<String> listValues = headers.values(HttpHeaders.SET_COOKIE);
            final int size = listValues.size();
            ArrayList arrayList = null;
            int i2 = 0;
            while (i2 < size) {
                final int i3 = i2 + 1;
                final Cookie cookie = this.parse(url, listValues.get(i2));
                if (null != cookie) {
                    if (null == arrayList) {
                        arrayList = new ArrayList();
                    }
                    arrayList.add(cookie);
                }
                i2 = i3;
            }
            if (null != arrayList) {
                final List<Cookie> listUnmodifiableList = Collections.unmodifiableList(arrayList);
                checkNotNullExpressionValue(listUnmodifiableList, "{\n        Collections.un\u2026ableList(cookies)\n      }");
                return listUnmodifiableList;
            }
            return CollectionsKt.emptyList();
        }
    }
}
