package okhttp3;

import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import okhttp3.internal.Util;
import okio.Buffer;
import okio.BufferedSink;

import java.io.EOFException;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;

import static kotlin.jvm.internal.Intrinsics.checkNotNull;

// Class generated by  decompiler (1.5.3)
/* compiled from: FormBody.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class FormBody extends RequestBody {
    public static final Companion Companion = new Companion(null);
    private static final MediaType CONTENT_TYPE = MediaType.Companion.get("application/x-www-form-urlencoded");
    private final List<String> encodedNames;
    private final List<String> encodedValues;

    public FormBody(final List<String> encodedNames, final List<String> encodedValues) {
        Intrinsics.checkNotNullParameter(encodedNames, "encodedNames");
        Intrinsics.checkNotNullParameter(encodedValues, "encodedValues");
        this.encodedNames = Util.toImmutableList(encodedNames);
        this.encodedValues = Util.toImmutableList(encodedValues);
    }

    public FormBody(FormBody contentTypeOverridingRequestBody, MediaType mediaType) {
        super();
    }

    public int size() {
        return encodedNames.size();
    }

    /* renamed from: -deprecated_size */
    public int m1755deprecated_size() {
        return this.size();
    }

    public String encodedName(final int i2) {
        return encodedNames.get(i2);
    }

    public String name(final int i2) {
        return HttpUrl.Companion.percentDecodeokhttpdefault(HttpUrl.Companion, this.encodedName(i2), 0, 0, true, 3, null);
    }

    public String encodedValue(final int i2) {
        return encodedValues.get(i2);
    }

    public String value(final int i2) {
        return HttpUrl.Companion.percentDecodeokhttpdefault(HttpUrl.Companion, this.encodedValue(i2), 0, 0, true, 3, null);
    }

    @Override // okhttp3.RequestBody
    public MediaType contentType() {
        return FormBody.CONTENT_TYPE;
    }

    @Override // okhttp3.RequestBody
    public long contentLength() {
        return this.writeOrCountBytes(null, true);
    }

    @Override // okhttp3.RequestBody
    public void writeTo(final BufferedSink sink) throws IOException {
        Intrinsics.checkNotNullParameter(sink, "sink");
        this.writeOrCountBytes(sink, false);
    }

    private long writeOrCountBytes(final BufferedSink bufferedSink, final boolean z) throws EOFException {
        final Buffer buffer;
        if (z) {
            buffer = new Buffer();
        } else {
            checkNotNull(bufferedSink);
            buffer = bufferedSink.getBuffer();
        }
        final int size = encodedNames.size();
        int i2 = 0;
        while (i2 < size) {
            final int i3 = i2 + 1;
            if (0 < i2) {
                buffer.writeByte(38);
            }
            buffer.writeUtf8(encodedNames.get(i2));
            buffer.writeByte(61);
            buffer.writeUtf8(encodedValues.get(i2));
            i2 = i3;
        }
        if (!z) {
            return 0L;
        }
        final long size2 = buffer.size();
        buffer.clear();
        return size2;
    }

    /* compiled from: FormBody.kt */
    public static final class Builder {
        private final Charset charset;
        private final List<String> names;
        private final List<String> values;

        public Builder() {
            this(null, 1, null);
        }

        public Builder(final Charset charset) {
            this.charset = charset;
            names = new ArrayList();
            values = new ArrayList();
        }

        public Builder(final Charset charset, final int i2, final DefaultConstructorMarker defaultConstructorMarker) {
            this(0 != (i2 & 1) ? null : charset);
        }

        public Builder add(final String name, final String value) {
            Intrinsics.checkNotNullParameter(name, "name");
            Intrinsics.checkNotNullParameter(value, "value");
            final List<String> list = names;
            final HttpUrl.Companion companion = HttpUrl.Companion;
            list.add(HttpUrl.Companion.canonicalizeokhttpdefault(companion, name, 0, 0, HttpUrl.FORM_ENCODE_SET, false, false, true, false, charset, 91, null));
            values.add(HttpUrl.Companion.canonicalizeokhttpdefault(companion, value, 0, 0, HttpUrl.FORM_ENCODE_SET, false, false, true, false, charset, 91, null));
            return this;
        }

        public Builder addEncoded(final String name, final String value) {
            Intrinsics.checkNotNullParameter(name, "name");
            Intrinsics.checkNotNullParameter(value, "value");
            final List<String> list = names;
            final HttpUrl.Companion companion = HttpUrl.Companion;
            list.add(HttpUrl.Companion.canonicalizeokhttpdefault(companion, name, 0, 0, HttpUrl.FORM_ENCODE_SET, true, false, true, false, charset, 83, null));
            values.add(HttpUrl.Companion.canonicalizeokhttpdefault(companion, value, 0, 0, HttpUrl.FORM_ENCODE_SET, true, false, true, false, charset, 83, null));
            return this;
        }

        public FormBody build() {
            return new FormBody(names, values);
        }
    }

    /* compiled from: FormBody.kt */
    public static final class Companion {
        public Companion(final DefaultConstructorMarker defaultConstructorMarker) {
            this();
        }

        private Companion() {
        }
    }
}
