package okhttp3;

import kotlin.collections.CollectionsKt;
import kotlin.jvm.functions.Function0;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import okhttp3.internal.Util;

import javax.net.ssl.SSLPeerUnverifiedException;
import javax.net.ssl.SSLSession;
import java.io.IOException;
import java.security.Principal;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

import static kotlin.jvm.internal.Intrinsics.*;

// Class generated by  decompiler (1.5.3)
/* compiled from: Handshake.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class Handshake {
    public static final Companion Companion = new Companion(null);
    private final CipherSuite cipherSuite;
    private final List<Certificate> localCertificates;
    private final Lazy peerCertificatesdelegate;
    private final TlsVersion tlsVersion;


    public Handshake(final TlsVersion tlsVersion, final CipherSuite cipherSuite, final List<? extends Certificate> localCertificates, Function0<? extends List<? extends Certificate>> peerCertificatesFn) {
        Intrinsics.checkNotNullParameter(tlsVersion, "tlsVersion");
        Intrinsics.checkNotNullParameter(cipherSuite, "cipherSuite");
        Intrinsics.checkNotNullParameter(localCertificates, "localCertificates");
        Intrinsics.checkNotNullParameter(peerCertificatesFn, "peerCertificatesFn");
        this.tlsVersion = tlsVersion;
        this.cipherSuite = cipherSuite;
        this.localCertificates = localCertificates;
        peerCertificatesdelegate = LazyKt.lazy(new Function0<List<? extends Certificate>>() { // from class: okhttp3.Handshake.peerCertificates.2

             {
                super(0);
            }

            @Override // kotlin.jvm.functions.Function0
            public List<? extends Certificate> invoke() {
                try {
                    return peerCertificatesFn.invoke();
                } catch (final SSLPeerUnverifiedException unused) {
                    return CollectionsKt.emptyList();
                }
            }
        });
    }

    public static Handshake get(final SSLSession sSLSession) throws IOException {
        return Handshake.Companion.get(sSLSession);
    }

    public static Handshake get(final TlsVersion tlsVersion, final CipherSuite cipherSuite, final List<? extends Certificate> list, final List<? extends Certificate> list2) {
        return Handshake.Companion.get(tlsVersion, cipherSuite, list, list2);
    }

    public TlsVersion tlsVersion() {
        return tlsVersion;
    }

    public CipherSuite cipherSuite() {
        return cipherSuite;
    }

    public List<Certificate> localCertificates() {
        return localCertificates;
    }

    public List<Certificate> peerCertificates() {
        return (List) peerCertificatesdelegate.getValue();
    }

    /* renamed from: -deprecated_tlsVersion, reason: not valid java name */
    public TlsVersion m1761deprecated_tlsVersion() {
        return tlsVersion;
    }

    /* renamed from: -deprecated_cipherSuite, reason: not valid java name */
    public CipherSuite m1756deprecated_cipherSuite() {
        return cipherSuite;
    }

    /* renamed from: -deprecated_peerCertificates, reason: not valid java name */
    public List<Certificate> m1759deprecated_peerCertificates() {
        return this.peerCertificates();
    }

    public Principal peerPrincipal() {
        final Object objFirstOrNull = CollectionsKt.firstOrNull((List<? extends Object>) this.peerCertificates());
        final X509Certificate x509Certificate = objFirstOrNull instanceof X509Certificate ? (X509Certificate) objFirstOrNull : null;
        if (null == x509Certificate) {
            return null;
        }
        return x509Certificate.getSubjectX500Principal();
    }

    /* renamed from: -deprecated_peerPrincipal, reason: not valid java name */
    public Principal m1760deprecated_peerPrincipal() {
        return this.peerPrincipal();
    }

    /* renamed from: -deprecated_localCertificates, reason: not valid java name */
    public List<Certificate> m1757deprecated_localCertificates() {
        return localCertificates;
    }

    public Principal localPrincipal() {
        final Object objFirstOrNull = CollectionsKt.firstOrNull((List<? extends Object>) localCertificates);
        final X509Certificate x509Certificate = objFirstOrNull instanceof X509Certificate ? (X509Certificate) objFirstOrNull : null;
        if (null == x509Certificate) {
            return null;
        }
        return x509Certificate.getSubjectX500Principal();
    }

    /* renamed from: -deprecated_localPrincipal, reason: not valid java name */
    public Principal m1758deprecated_localPrincipal() {
        return this.localPrincipal();
    }

    public boolean equals(final Object obj) {
        if (obj instanceof Handshake handshake) {
            return handshake.tlsVersion == tlsVersion && areEqual(handshake.cipherSuite, cipherSuite) && areEqual(handshake.peerCertificates(), this.peerCertificates()) && areEqual(handshake.localCertificates, localCertificates);
        }
        return false;
    }

    public int hashCode() {
        return ((((((527 + tlsVersion.hashCode()) * 31) + cipherSuite.hashCode()) * 31) + this.peerCertificates().hashCode()) * 31) + localCertificates.hashCode();
    }

    public String toString() {
        final List<Certificate> listPeerCertificates = this.peerCertificates();
        final ArrayList arrayList = new ArrayList(CollectionsKt.collectionSizeOrDefault(listPeerCertificates, 10));
        final Iterator<T> it = listPeerCertificates.iterator();
        while (it.hasNext()) {
            arrayList.add(this.getName((Certificate) it.next()));
        }
        final String string = arrayList.toString();
        final StringBuilder sb = new StringBuilder();
        sb.append("Handshake{tlsVersion=");
        sb.append(tlsVersion);
        sb.append(" cipherSuite=");
        sb.append(cipherSuite);
        sb.append(" peerCertificates=");
        sb.append(string);
        sb.append(" localCertificates=");
        final List<Certificate> list = localCertificates;
        final ArrayList arrayList2 = new ArrayList(CollectionsKt.collectionSizeOrDefault(list, 10));
        final Iterator<T> it2 = list.iterator();
        while (it2.hasNext()) {
            arrayList2.add(this.getName((Certificate) it2.next()));
        }
        sb.append(arrayList2);
        sb.append('}');
        return sb.toString();
    }

    private String getName(final Certificate certificate) {
        if (certificate instanceof X509Certificate) {
            return ((X509Certificate) certificate).getSubjectDN().toString();
        }
        final String type = certificate.getType();
        checkNotNullExpressionValue(type, "type");
        return type;
    }

    /* compiled from: Handshake.kt */
    public static final class Companion {
        public Companion(final DefaultConstructorMarker defaultConstructorMarker) {
            this();
        }

        private Companion() {
        }

        public Handshake get(final SSLSession sSLSession) throws IOException {
            List<Certificate> listEmptyList;
            Intrinsics.checkNotNullParameter(sSLSession, "<this>");
            final String cipherSuite = sSLSession.getCipherSuite();
            if (null == cipherSuite) {
                throw new IllegalStateException("cipherSuite == null");
            }
            if (areEqual(cipherSuite, "TLS_NULL_WITH_NULL_NULL") || areEqual(cipherSuite, "SSL_NULL_WITH_NULL_NULL")) {
                throw new IOException(stringPlus("cipherSuite == ", cipherSuite));
            }
            final CipherSuite cipherSuiteForJavaName = CipherSuite.Companion.forJavaName(cipherSuite);
            final String protocol = sSLSession.getProtocol();
            if (null == protocol) {
                throw new IllegalStateException("tlsVersion == null");
            }
            if (areEqual("NONE", protocol)) {
                throw new IOException("tlsVersion == NONE");
            }
            final TlsVersion tlsVersionForJavaName = TlsVersion.Companion.forJavaName(protocol);
            try {
                listEmptyList = this.toImmutableList(sSLSession.getPeerCertificates());
            } catch (final SSLPeerUnverifiedException unused) {
                listEmptyList = CollectionsKt.emptyList();
            }
            return new Handshake(tlsVersionForJavaName, cipherSuiteForJavaName, this.toImmutableList(sSLSession.getLocalCertificates()), new Function0<List<? extends Certificate>>() { // from class: okhttp3.HandshakeCompanionhandshake1

                 {
                    super(0);
                }

                @Override // kotlin.jvm.functions.Function0
                public List<? extends Certificate> invoke() {
                    return listEmptyList;
                }
            });
        }

        private List<Certificate> toImmutableList(final Certificate[] certificateArr) {
            if (null != certificateArr) {
                return Util.immutableListOf(Arrays.copyOf(certificateArr, certificateArr.length));
            }
            return CollectionsKt.emptyList();
        }

        /* renamed from: -deprecated_get, reason: not valid java name */
        public Handshake m1762deprecated_get(final SSLSession sslSession) throws IOException {
            Intrinsics.checkNotNullParameter(sslSession, "sslSession");
            return this.get(sslSession);
        }

        public Handshake get(final TlsVersion tlsVersion, final CipherSuite cipherSuite, final List<? extends Certificate> peerCertificates, final List<? extends Certificate> localCertificates) {
            Intrinsics.checkNotNullParameter(tlsVersion, "tlsVersion");
            Intrinsics.checkNotNullParameter(cipherSuite, "cipherSuite");
            Intrinsics.checkNotNullParameter(peerCertificates, "peerCertificates");
            Intrinsics.checkNotNullParameter(localCertificates, "localCertificates");
            List immutableList = Util.toImmutableList(peerCertificates);
            return new Handshake(tlsVersion, cipherSuite, Util.toImmutableList(localCertificates), new Function0<List<? extends Certificate>>() { // from class: okhttp3.HandshakeCompanionget1

                 {
                    super(0);
                }

                @Override // kotlin.jvm.functions.Function0
                public List<? extends Certificate> invoke() {
                    return immutableList;
                }
            });
        }
    }
}
