package okhttp3;

import kotlin.jvm.internal.Intrinsics;

import java.io.IOException;

// Class generated by  decompiler (1.5.3)
/* compiled from: JavaNetAuthenticator.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class JavaNetAuthenticator implements Authenticator {
    @Override // okhttp3.Authenticator
    public Request authenticate(final Route route, final Response response) throws IOException {
        Intrinsics.checkNotNullParameter(response, "response");
        return JAVA_NET_AUTHENTICATOR.authenticate(route, response);
    }
}
