package okhttp3;

import kotlin.collections.CollectionsKt;
import kotlin.collections.MapsKt;
import kotlin.jvm.internal.Intrinsics;
import kotlin.text.StringsKt;
import okhttp3.internal.Util;
import okhttp3.internal.http.HttpMethod;
import org.springframework.http.HttpHeaders;

import java.net.URL;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static kotlin.jvm.internal.Intrinsics.*;

// Class generated by  decompiler (1.5.3)
/* compiled from: Request.kt */
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes3.dex */
public final class Request {
    private final RequestBody body;
    private final Headers headers;
    private final String method;
    private final Map<Class<?>, Object> tags;
    private final HttpUrl url;
    private CacheControl lazyCacheControl;

    public Request(final HttpUrl url, final String method, final Headers headers, final RequestBody requestBody, final Map<Class<?>, ? extends Object> tags) {
        Intrinsics.checkNotNullParameter(url, "url");
        Intrinsics.checkNotNullParameter(method, "method");
        Intrinsics.checkNotNullParameter(headers, "headers");
        Intrinsics.checkNotNullParameter(tags, "tags");
        this.url = url;
        this.method = method;
        this.headers = headers;
        body = requestBody;
        this.tags = tags;
    }

    public HttpUrl url() {
        return url;
    }

    public String method() {
        return method;
    }

    public Headers headers() {
        return headers;
    }

    public RequestBody body() {
        return body;
    }

    public Map<Class<?>, Object> getTagsokhttp() {
        return tags;
    }

    public boolean isHttps() {
        return url.isHttps();
    }

    public String header(final String name) {
        Intrinsics.checkNotNullParameter(name, "name");
        return headers.get(name);
    }

    public List<String> headers(final String name) {
        Intrinsics.checkNotNullParameter(name, "name");
        return headers.values(name);
    }

    public Object tag() {
        return this.tag(Object.class);
    }

    public <T> T tag(final Class<? extends T> type) {
        Intrinsics.checkNotNullParameter(type, "type");
        return type.cast(tags.get(type));
    }

    public Builder newBuilder() {
        return new Builder(this);
    }

    public CacheControl cacheControl() {
        final CacheControl cacheControl = lazyCacheControl;
        if (null != cacheControl) {
            return cacheControl;
        }
        final CacheControl cacheControl2 = CacheControl.Companion.parse(headers);
        lazyCacheControl = cacheControl2;
        return cacheControl2;
    }

    /* renamed from: -deprecated_url */
    public HttpUrl m1831deprecated_url() {
        return url;
    }

    /* renamed from: -deprecated_method */
    public String m1830deprecated_method() {
        return method;
    }

    /* renamed from: -deprecated_headers */
    public Headers m1829deprecated_headers() {
        return headers;
    }

    /* renamed from: -deprecated_body */
    public RequestBody m1827deprecated_body() {
        return body;
    }

    /* renamed from: -deprecated_cacheControl */
    public CacheControl m1828deprecated_cacheControl() {
        return this.cacheControl();
    }

    public String toString() {
        final StringBuilder sb = new StringBuilder();
        sb.append("Request{method=");
        sb.append(this.method());
        sb.append(", url=");
        sb.append(this.url());
        if (0 != headers().size()) {
            sb.append(", headers=[");
            int i2 = 0;
            for (final Tuples<? extends String, ? extends String> tuples : this.headers()) {
                final int i3 = i2 + 1;
                if (0 > i2) {
                    CollectionsKt.throwIndexOverflow();
                }
                final Tuples<? extends String, ? extends String> tuples2 = tuples;
                final String strComponent1 = tuples2.component1();
                final String strComponent2 = tuples2.component2();
                if (0 < i2) {
                    sb.append(", ");
                }
                sb.append(strComponent1);
                sb.append(':');
                sb.append(strComponent2);
                i2 = i3;
            }
            sb.append(']');
        }
        if (!this.tags.isEmpty()) {
            sb.append(", tags=");
            sb.append(this.tags);
        }
        sb.append('}');
        final String string = sb.toString();
        checkNotNullExpressionValue(string, "StringBuilder().apply(builderAction).toString()");
        return string;
    }

    /* compiled from: Request.kt */
    public static class Builder {
        private RequestBody body;
        private Headers.Builder headers;
        private String method;
        private Map<Class<?>, Object> tags;
        private HttpUrl url;

        public Builder() {
            tags = new LinkedHashMap();
            method = "GET";
            headers = new Headers.Builder();
        }

        public Builder(final Request request) {
            final Map<Class<?>, Object> mutableMap;
            Intrinsics.checkNotNullParameter(request, "request");
            tags = new LinkedHashMap();
            url = request.url();
            method = request.method();
            body = request.body();
            if (request.getTagsokhttp().isEmpty()) {
                mutableMap = new LinkedHashMap<>();
            } else {
                mutableMap = MapsKt.toMutableMap(request.getTagsokhttp());
            }
            tags = mutableMap;
            headers = request.headers().newBuilder();
        }

        public static Builder deletedefault(final Builder builder, RequestBody requestBody, final int i2, final Object obj) {
            if (null != obj) {
                throw new UnsupportedOperationException("Super calls with default arguments not supported in this target, function: delete");
            }
            if (0 != (i2 & 1)) {
                requestBody = Util.EMPTY_REQUEST;
            }
            return builder.delete(requestBody);
        }

        public final Builder delete() {
            return Builder.deletedefault(this, null, 1, null);
        }

        public final HttpUrl getUrlokhttp() {
            return url;
        }

        public final void setUrlokhttp(final HttpUrl httpUrl) {
            url = httpUrl;
        }

        public final String getMethodokhttp() {
            return method;
        }

        public final void setMethodokhttp(final String str) {
            Intrinsics.checkNotNullParameter(str, "<set-?>");
            method = str;
        }

        public final Headers.Builder getHeadersokhttp() {
            return headers;
        }

        public final void setHeadersokhttp(final Headers.Builder builder) {
            Intrinsics.checkNotNullParameter(builder, "<set-?>");
            headers = builder;
        }

        public final RequestBody getBodyokhttp() {
            return body;
        }

        public final void setBodyokhttp(final RequestBody requestBody) {
            body = requestBody;
        }

        public final Map<Class<?>, Object> getTagsokhttp() {
            return tags;
        }

        public final void setTagsokhttp(final Map<Class<?>, Object> map) {
            Intrinsics.checkNotNullParameter(map, "<set-?>");
            tags = map;
        }

        public Builder url(final HttpUrl url) {
            Intrinsics.checkNotNullParameter(url, "url");
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            Intrinsics.checkNotNullParameter(url, "url");
            if (StringsKt.startsWith(url, "ws:", true)) {
                final String strSubstring = url.substring(3);
                checkNotNullExpressionValue(strSubstring, "this as java.lang.String).substring(startIndex)");
                url = stringPlus("http:", strSubstring);
            } else if (StringsKt.startsWith(url, "wss:", true)) {
                final String strSubstring2 = url.substring(4);
                checkNotNullExpressionValue(strSubstring2, "this as java.lang.String).substring(startIndex)");
                url = stringPlus("https:", strSubstring2);
            }
            return this.url(HttpUrl.Companion.get(url));
        }

        public Builder url(final URL url) {
            Intrinsics.checkNotNullParameter(url, "url");
            final HttpUrl.Companion companion = HttpUrl.Companion;
            final String string = url.toString();
            checkNotNullExpressionValue(string, "url.toString()");
            return this.url(companion.get(string));
        }

        public Builder header(final String name, final String value) {
            Intrinsics.checkNotNullParameter(name, "name");
            Intrinsics.checkNotNullParameter(value, "value");
            this.headers.set(name, value);
            return this;
        }

        public Builder addHeader(final String name, final String value) {
            Intrinsics.checkNotNullParameter(name, "name");
            Intrinsics.checkNotNullParameter(value, "value");
            this.headers.add(name, value);
            return this;
        }

        public Builder removeHeader(final String name) {
            Intrinsics.checkNotNullParameter(name, "name");
            this.headers.removeAll(name);
            return this;
        }

        public Builder headers(final Headers headers) {
            Intrinsics.checkNotNullParameter(headers, "headers");
            this.setHeadersokhttp(headers.newBuilder());
            return this;
        }

        public Builder cacheControl(final CacheControl cacheControl) {
            Intrinsics.checkNotNullParameter(cacheControl, "cacheControl");
            final String string = cacheControl.toString();
            return 0 == string.length() ? this.removeHeader(HttpHeaders.CACHE_CONTROL) : this.header(HttpHeaders.CACHE_CONTROL, string);
        }

        public Builder get() {
            return this.method("GET", null);
        }

        public Builder head() {
            return this.method("HEAD", null);
        }

        public Builder post(final RequestBody body) {
            Intrinsics.checkNotNullParameter(body, "body");
            return this.method("POST", body);
        }

        public Builder delete(final RequestBody requestBody) {
            return this.method("DELETE", requestBody);
        }

        public Builder put(final RequestBody body) {
            Intrinsics.checkNotNullParameter(body, "body");
            return this.method("PUT", body);
        }

        public Builder patch(final RequestBody body) {
            Intrinsics.checkNotNullParameter(body, "body");
            return this.method("PATCH", body);
        }

        public Builder method(final String method, final RequestBody requestBody) {
            Intrinsics.checkNotNullParameter(method, "method");
            if (0 >= method.length()) {
                throw new IllegalArgumentException("method.isEmpty() == true");
            }
            if (null == requestBody) {
                if (HttpMethod.requiresRequestBody(method)) {
                    throw new IllegalArgumentException(("method " + method + " must have a request body."));
                }
            } else if (!HttpMethod.permitsRequestBody(method)) {
                throw new IllegalArgumentException(("method " + method + " must not have a request body."));
            }
            this.setMethodokhttp(method);
            this.body = requestBody;
            return this;
        }

        public Builder tag(final Object obj) {
            return this.tag(Object.class, obj);
        }

        public <T> Builder tag(final Class<? super T> type, final T t) {
            Intrinsics.checkNotNullParameter(type, "type");
            if (null == t) {
                this.tags.remove(type);
            } else {
                if (this.tags.isEmpty()) {
                    this.setTagsokhttp(new LinkedHashMap());
                }
                final Map<Class<?>, Object> tagsokhttp = this.tags;
                final T tCast = type.cast(t);
                checkNotNull(tCast);
                tagsokhttp.put(type, tCast);
            }
            return this;
        }

        public Request build() {
            final HttpUrl httpUrl = url;
            if (null != httpUrl) {
                return new Request(httpUrl, method, headers.build(), body, Util.toImmutableMap(tags));
            }
            throw new IllegalStateException("url == null");
        }
    }
}
