package com.fasterxml.jackson.databind.module;

import com.fasterxml.jackson.core.Version;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.deser.BeanDeserializerModifier;
import com.fasterxml.jackson.databind.deser.ValueInstantiator;
import com.fasterxml.jackson.databind.jsontype.NamedType;
import com.fasterxml.jackson.databind.ser.BeanSerializerModifier;

import java.io.Serializable;
import java.util.*;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class SimpleModule extends Module implements Serializable {
    private static final long serialVersionUID = 1;
    protected SimpleAbstractTypeResolver _abstractTypes;
    protected BeanDeserializerModifier _deserializerModifier;
    protected SimpleDeserializers _deserializers;
    protected SimpleKeyDeserializers _keyDeserializers;
    protected SimpleSerializers _keySerializers;
    protected HashMap<Class<?>, Class<?>> _mixins;
    protected final String _name;
    protected PropertyNamingStrategy _namingStrategy;
    protected BeanSerializerModifier _serializerModifier;
    protected SimpleSerializers _serializers;
    protected LinkedHashSet<NamedType> _subtypes;
    protected SimpleValueInstantiators _valueInstantiators;
    protected final Version _version;

    public SimpleModule() {
        final String name;
        _serializers = null;
        _deserializers = null;
        _keySerializers = null;
        _keyDeserializers = null;
        _abstractTypes = null;
        _valueInstantiators = null;
        _deserializerModifier = null;
        _serializerModifier = null;
        _mixins = null;
        _subtypes = null;
        _namingStrategy = null;
        if (SimpleModule.class == getClass()) {
            name = "SimpleModule-" + System.identityHashCode(this);
        } else {
            name = this.getClass().getName();
        }
        _name = name;
        _version = Version.unknownVersion();
    }

    public SimpleModule(final String str) {
        this(str, Version.unknownVersion());
    }

    public SimpleModule(final Version version) {
        _serializers = null;
        _deserializers = null;
        _keySerializers = null;
        _keyDeserializers = null;
        _abstractTypes = null;
        _valueInstantiators = null;
        _deserializerModifier = null;
        _serializerModifier = null;
        _mixins = null;
        _subtypes = null;
        _namingStrategy = null;
        _name = version.getArtifactId();
        _version = version;
    }

    public SimpleModule(final String str, final Version version) {
        _serializers = null;
        _deserializers = null;
        _keySerializers = null;
        _keyDeserializers = null;
        _abstractTypes = null;
        _valueInstantiators = null;
        _deserializerModifier = null;
        _serializerModifier = null;
        _mixins = null;
        _subtypes = null;
        _namingStrategy = null;
        _name = str;
        _version = version;
    }

    public SimpleModule(final String str, final Version version, final Map<Class<?>, JsonDeserializer<?>> map) {
        this(str, version, map, null);
    }

    public SimpleModule(final String str, final Version version, final List<JsonSerializer<?>> list) {
        this(str, version, null, list);
    }

    public SimpleModule(final String str, final Version version, final Map<Class<?>, JsonDeserializer<?>> map, final List<JsonSerializer<?>> list) {
        _serializers = null;
        _deserializers = null;
        _keySerializers = null;
        _keyDeserializers = null;
        _abstractTypes = null;
        _valueInstantiators = null;
        _deserializerModifier = null;
        _serializerModifier = null;
        _mixins = null;
        _subtypes = null;
        _namingStrategy = null;
        _name = str;
        _version = version;
        if (null != map) {
            _deserializers = new SimpleDeserializers(map);
        }
        if (null != list) {
            _serializers = new SimpleSerializers(list);
        }
    }

    @Override // com.fasterxml.jackson.databind.Module
    public Object getTypeId() {
        if (SimpleModule.class == getClass()) {
            return null;
        }
        return super.getTypeId();
    }

    public void setSerializers(final SimpleSerializers simpleSerializers) {
        _serializers = simpleSerializers;
    }

    public void setDeserializers(final SimpleDeserializers simpleDeserializers) {
        _deserializers = simpleDeserializers;
    }

    public void setKeySerializers(final SimpleSerializers simpleSerializers) {
        _keySerializers = simpleSerializers;
    }

    public void setKeyDeserializers(final SimpleKeyDeserializers simpleKeyDeserializers) {
        _keyDeserializers = simpleKeyDeserializers;
    }

    public void setAbstractTypes(final SimpleAbstractTypeResolver simpleAbstractTypeResolver) {
        _abstractTypes = simpleAbstractTypeResolver;
    }

    public void setValueInstantiators(final SimpleValueInstantiators simpleValueInstantiators) {
        _valueInstantiators = simpleValueInstantiators;
    }

    public SimpleModule setDeserializerModifier(final BeanDeserializerModifier beanDeserializerModifier) {
        _deserializerModifier = beanDeserializerModifier;
        return this;
    }

    public SimpleModule setSerializerModifier(final BeanSerializerModifier beanSerializerModifier) {
        _serializerModifier = beanSerializerModifier;
        return this;
    }

    protected SimpleModule setNamingStrategy(final PropertyNamingStrategy propertyNamingStrategy) {
        _namingStrategy = propertyNamingStrategy;
        return this;
    }

    public SimpleModule addSerializer(final JsonSerializer<?> jsonSerializer) {
        this._checkNotNull(jsonSerializer, "serializer");
        if (null == this._serializers) {
            _serializers = new SimpleSerializers();
        }
        _serializers.addSerializer(jsonSerializer);
        return this;
    }

    public <T> SimpleModule addSerializer(final Class<? extends T> cls, final JsonSerializer<T> jsonSerializer) {
        this._checkNotNull(cls, "type to register serializer for");
        this._checkNotNull(jsonSerializer, "serializer");
        if (null == this._serializers) {
            _serializers = new SimpleSerializers();
        }
        _serializers.addSerializer(cls, jsonSerializer);
        return this;
    }

    public <T> SimpleModule addKeySerializer(final Class<? extends T> cls, final JsonSerializer<T> jsonSerializer) {
        this._checkNotNull(cls, "type to register key serializer for");
        this._checkNotNull(jsonSerializer, "key serializer");
        if (null == this._keySerializers) {
            _keySerializers = new SimpleSerializers();
        }
        _keySerializers.addSerializer(cls, jsonSerializer);
        return this;
    }

    public <T> SimpleModule addDeserializer(final Class<T> cls, final JsonDeserializer<? extends T> jsonDeserializer) {
        this._checkNotNull(cls, "type to register deserializer for");
        this._checkNotNull(jsonDeserializer, "deserializer");
        if (null == this._deserializers) {
            _deserializers = new SimpleDeserializers();
        }
        _deserializers.addDeserializer(cls, jsonDeserializer);
        return this;
    }

    public SimpleModule addKeyDeserializer(final Class<?> cls, final KeyDeserializer keyDeserializer) {
        this._checkNotNull(cls, "type to register key deserializer for");
        this._checkNotNull(keyDeserializer, "key deserializer");
        if (null == this._keyDeserializers) {
            _keyDeserializers = new SimpleKeyDeserializers();
        }
        _keyDeserializers.addDeserializer(cls, keyDeserializer);
        return this;
    }

    public <T> SimpleModule addAbstractTypeMapping(final Class<T> cls, final Class<? extends T> cls2) {
        this._checkNotNull(cls, "abstract type to map");
        this._checkNotNull(cls2, "concrete type to map to");
        if (null == this._abstractTypes) {
            _abstractTypes = new SimpleAbstractTypeResolver();
        }
        _abstractTypes = _abstractTypes.addMapping(cls, cls2);
        return this;
    }

    public SimpleModule registerSubtypes(final Class<?>... clsArr) {
        if (null == this._subtypes) {
            _subtypes = new LinkedHashSet<>();
        }
        for (final Class<?> cls : clsArr) {
            this._checkNotNull(cls, "subtype to register");
            _subtypes.add(new NamedType(cls));
        }
        return this;
    }

    public SimpleModule registerSubtypes(final NamedType... namedTypeArr) {
        if (null == this._subtypes) {
            _subtypes = new LinkedHashSet<>();
        }
        for (final NamedType namedType : namedTypeArr) {
            this._checkNotNull(namedType, "subtype to register");
            _subtypes.add(namedType);
        }
        return this;
    }

    public SimpleModule registerSubtypes(final Collection<Class<?>> collection) {
        if (null == this._subtypes) {
            _subtypes = new LinkedHashSet<>();
        }
        for (final Class<?> cls : collection) {
            this._checkNotNull(cls, "subtype to register");
            _subtypes.add(new NamedType(cls));
        }
        return this;
    }

    public SimpleModule addValueInstantiator(final Class<?> cls, final ValueInstantiator valueInstantiator) {
        this._checkNotNull(cls, "class to register value instantiator for");
        this._checkNotNull(valueInstantiator, "value instantiator");
        if (null == this._valueInstantiators) {
            _valueInstantiators = new SimpleValueInstantiators();
        }
        _valueInstantiators = _valueInstantiators.addValueInstantiator(cls, valueInstantiator);
        return this;
    }

    public SimpleModule setMixInAnnotation(final Class<?> cls, final Class<?> cls2) {
        this._checkNotNull(cls, "target type");
        this._checkNotNull(cls2, "mixin class");
        if (null == this._mixins) {
            _mixins = new HashMap<>();
        }
        _mixins.put(cls, cls2);
        return this;
    }

    @Override // com.fasterxml.jackson.databind.Module
    public String getModuleName() {
        return _name;
    }

    @Override // com.fasterxml.jackson.databind.Module
    public void setupModule(final Module.SetupContext setupContext) {
        final SimpleSerializers simpleSerializers = _serializers;
        if (null != simpleSerializers) {
            setupContext.addSerializers(simpleSerializers);
        }
        final SimpleDeserializers simpleDeserializers = _deserializers;
        if (null != simpleDeserializers) {
            setupContext.addDeserializers(simpleDeserializers);
        }
        final SimpleSerializers simpleSerializers2 = _keySerializers;
        if (null != simpleSerializers2) {
            setupContext.addKeySerializers(simpleSerializers2);
        }
        final SimpleKeyDeserializers simpleKeyDeserializers = _keyDeserializers;
        if (null != simpleKeyDeserializers) {
            setupContext.addKeyDeserializers(simpleKeyDeserializers);
        }
        final SimpleAbstractTypeResolver simpleAbstractTypeResolver = _abstractTypes;
        if (null != simpleAbstractTypeResolver) {
            setupContext.addAbstractTypeResolver(simpleAbstractTypeResolver);
        }
        final SimpleValueInstantiators simpleValueInstantiators = _valueInstantiators;
        if (null != simpleValueInstantiators) {
            setupContext.addValueInstantiators(simpleValueInstantiators);
        }
        final BeanDeserializerModifier beanDeserializerModifier = _deserializerModifier;
        if (null != beanDeserializerModifier) {
            setupContext.addBeanDeserializerModifier(beanDeserializerModifier);
        }
        final BeanSerializerModifier beanSerializerModifier = _serializerModifier;
        if (null != beanSerializerModifier) {
            setupContext.addBeanSerializerModifier(beanSerializerModifier);
        }
        final LinkedHashSet<NamedType> linkedHashSet = _subtypes;
        if (null != linkedHashSet && 0 < linkedHashSet.size()) {
            final LinkedHashSet<NamedType> linkedHashSet2 = _subtypes;
            setupContext.registerSubtypes(linkedHashSet2.toArray(new NamedType[linkedHashSet2.size()]));
        }
        final PropertyNamingStrategy propertyNamingStrategy = _namingStrategy;
        if (null != propertyNamingStrategy) {
            setupContext.setNamingStrategy(propertyNamingStrategy);
        }
        final HashMap<Class<?>, Class<?>> map = _mixins;
        if (null != map) {
            for (final Map.Entry<Class<?>, Class<?>> entry : map.entrySet()) {
                setupContext.setMixInAnnotations(entry.getKey(), entry.getValue());
            }
        }
    }

    @Override // com.fasterxml.jackson.databind.Module
    public Version version() {
        return _version;
    }

    protected void _checkNotNull(final Object obj, final String str) {
        if (null == obj) {
            throw new IllegalArgumentException(String.format("Cannot pass `null` as %s", str));
        }
    }
}
