package com.fasterxml.jackson.databind.module;

import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.ser.Serializers;
import com.fasterxml.jackson.databind.type.*;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class SimpleSerializers extends Serializers.Base implements Serializable {
    private static final long serialVersionUID = 3;
    protected HashMap<ClassKey, JsonSerializer<?>> _classMappings;
    protected HashMap<ClassKey, JsonSerializer<?>> _interfaceMappings;
    protected boolean _hasEnumSerializer;

    public SimpleSerializers() {
    }

    public SimpleSerializers(final List<JsonSerializer<?>> list) {
        this.addSerializers(list);
    }

    public void addSerializer(final JsonSerializer<?> jsonSerializer) {
        final Class<?> clsHandledType = jsonSerializer.handledType();
        if (null == clsHandledType || Object.class == clsHandledType) {
            throw new IllegalArgumentException("JsonSerializer of type " + jsonSerializer.getClass().getName() + " does not define valid handledType() -- must either register with method that takes type argument  or make serializer extend 'com.fasterxml.jackson.databind.ser.std.StdSerializer'");
        }
        this._addSerializer(clsHandledType, jsonSerializer);
    }

    public <T> void addSerializer(final Class<? extends T> cls, final JsonSerializer<T> jsonSerializer) {
        this._addSerializer(cls, jsonSerializer);
    }

    public void addSerializers(final List<JsonSerializer<?>> list) {
        final Iterator<JsonSerializer<?>> it = list.iterator();
        while (it.hasNext()) {
            this.addSerializer(it.next());
        }
    }

    @Override // com.fasterxml.jackson.databind.ser.Serializers.Base, com.fasterxml.jackson.databind.ser.Serializers
    public JsonSerializer<?> findSerializer(final SerializationConfig serializationConfig, final JavaType javaType, final BeanDescription beanDescription) {
        JsonSerializer<?> jsonSerializer_findInterfaceMapping;
        final JsonSerializer<?> jsonSerializer;
        Class<?> rawClass = javaType.getRawClass();
        final ClassKey classKey = new ClassKey(rawClass);
        if (rawClass.isInterface()) {
            final HashMap<ClassKey, JsonSerializer<?>> map = _interfaceMappings;
            if (null != map && null != (jsonSerializer = map.get(classKey))) {
                return jsonSerializer;
            }
        } else {
            final HashMap<ClassKey, JsonSerializer<?>> map2 = _classMappings;
            if (null != map2) {
                final JsonSerializer<?> jsonSerializer2 = map2.get(classKey);
                if (null != jsonSerializer2) {
                    return jsonSerializer2;
                }
                if (_hasEnumSerializer && javaType.isEnumType()) {
                    classKey.reset(Enum.class);
                    final JsonSerializer<?> jsonSerializer3 = _classMappings.get(classKey);
                    if (null != jsonSerializer3) {
                        return jsonSerializer3;
                    }
                }
                for (Class<?> superclass = rawClass; null != superclass; superclass = superclass.getSuperclass()) {
                    classKey.reset(superclass);
                    final JsonSerializer<?> jsonSerializer4 = _classMappings.get(classKey);
                    if (null != jsonSerializer4) {
                        return jsonSerializer4;
                    }
                }
            }
        }
        if (null == this._interfaceMappings) {
            return null;
        }
        final JsonSerializer<?> jsonSerializer_findInterfaceMapping2 = this._findInterfaceMapping(rawClass, classKey);
        if (null != jsonSerializer_findInterfaceMapping2) {
            return jsonSerializer_findInterfaceMapping2;
        }
        if (rawClass.isInterface()) {
            return null;
        }
        do {
            rawClass = rawClass.getSuperclass();
            if (null == rawClass) {
                return null;
            }
            jsonSerializer_findInterfaceMapping = this._findInterfaceMapping(rawClass, classKey);
        } while (null == jsonSerializer_findInterfaceMapping);
        return jsonSerializer_findInterfaceMapping;
    }

    @Override // com.fasterxml.jackson.databind.ser.Serializers.Base, com.fasterxml.jackson.databind.ser.Serializers
    public JsonSerializer<?> findArraySerializer(final SerializationConfig serializationConfig, final ArrayType arrayType, final BeanDescription beanDescription, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer) {
        return this.findSerializer(serializationConfig, arrayType, beanDescription);
    }

    @Override // com.fasterxml.jackson.databind.ser.Serializers.Base, com.fasterxml.jackson.databind.ser.Serializers
    public JsonSerializer<?> findCollectionSerializer(final SerializationConfig serializationConfig, final CollectionType collectionType, final BeanDescription beanDescription, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer) {
        return this.findSerializer(serializationConfig, collectionType, beanDescription);
    }

    @Override // com.fasterxml.jackson.databind.ser.Serializers.Base, com.fasterxml.jackson.databind.ser.Serializers
    public JsonSerializer<?> findCollectionLikeSerializer(final SerializationConfig serializationConfig, final CollectionLikeType collectionLikeType, final BeanDescription beanDescription, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer) {
        return this.findSerializer(serializationConfig, collectionLikeType, beanDescription);
    }

    @Override // com.fasterxml.jackson.databind.ser.Serializers.Base, com.fasterxml.jackson.databind.ser.Serializers
    public JsonSerializer<?> findMapSerializer(final SerializationConfig serializationConfig, final MapType mapType, final BeanDescription beanDescription, final JsonSerializer<Object> jsonSerializer, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer2) {
        return this.findSerializer(serializationConfig, mapType, beanDescription);
    }

    @Override // com.fasterxml.jackson.databind.ser.Serializers.Base, com.fasterxml.jackson.databind.ser.Serializers
    public JsonSerializer<?> findMapLikeSerializer(final SerializationConfig serializationConfig, final MapLikeType mapLikeType, final BeanDescription beanDescription, final JsonSerializer<Object> jsonSerializer, final TypeSerializer typeSerializer, final JsonSerializer<Object> jsonSerializer2) {
        return this.findSerializer(serializationConfig, mapLikeType, beanDescription);
    }

    protected JsonSerializer<?> _findInterfaceMapping(final Class<?> cls, final ClassKey classKey) {
        for (final Class<?> cls2 : cls.getInterfaces()) {
            classKey.reset(cls2);
            final JsonSerializer<?> jsonSerializer = _interfaceMappings.get(classKey);
            if (null != jsonSerializer) {
                return jsonSerializer;
            }
            final JsonSerializer<?> jsonSerializer_findInterfaceMapping = this._findInterfaceMapping(cls2, classKey);
            if (null != jsonSerializer_findInterfaceMapping) {
                return jsonSerializer_findInterfaceMapping;
            }
        }
        return null;
    }

    protected void _addSerializer(final Class<?> cls, final JsonSerializer<?> jsonSerializer) {
        final ClassKey classKey = new ClassKey(cls);
        if (cls.isInterface()) {
            if (null == this._interfaceMappings) {
                _interfaceMappings = new HashMap<>();
            }
            _interfaceMappings.put(classKey, jsonSerializer);
        } else {
            if (null == this._classMappings) {
                _classMappings = new HashMap<>();
            }
            _classMappings.put(classKey, jsonSerializer);
            if (Enum.class == cls) {
                _hasEnumSerializer = true;
            }
        }
    }
}
