package com.fasterxml.jackson.databind.module;

import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.DeserializationConfig;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.KeyDeserializer;
import com.fasterxml.jackson.databind.deser.KeyDeserializers;
import com.fasterxml.jackson.databind.type.ClassKey;
import java.io.Serializable;
import java.util.HashMap;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public class SimpleKeyDeserializers implements KeyDeserializers, Serializable {
    private static final long serialVersionUID = 1;
    protected HashMap<ClassKey, KeyDeserializer> _classMappings;

    public SimpleKeyDeserializers addDeserializer(final Class<?> cls, final KeyDeserializer keyDeserializer) {
        if (null == this._classMappings) {
            _classMappings = new HashMap<>();
        }
        _classMappings.put(new ClassKey(cls), keyDeserializer);
        return this;
    }

    @Override // com.fasterxml.jackson.databind.deser.KeyDeserializers
    public KeyDeserializer findKeyDeserializer(final JavaType javaType, final DeserializationConfig deserializationConfig, final BeanDescription beanDescription) {
        final HashMap<ClassKey, KeyDeserializer> map = _classMappings;
        if (null == map) {
            return null;
        }
        return map.get(new ClassKey(javaType.getRawClass()));
    }
}
