package com.fasterxml.jackson.databind.deser.std;

import com.fasterxml.jackson.databind.JsonDeserializer;
import java.nio.ByteBuffer;
import java.util.HashSet;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

// Class generated by  decompiler (1.5.3)
/* loaded from: D:\Android\sil\Yeni klasör (2)\classes.dex */
public enum JdkDeserializers {
    ;
    private static final HashSet<String> _classNames = new HashSet<>();

    static {
        final Class[] clsArr = {UUID.class, AtomicBoolean.class, AtomicInteger.class, AtomicLong.class, StackTraceElement.class, ByteBuffer.class, Void.class};
        for (int i2 = 0; 7 > i2; i2++) {
            JdkDeserializers._classNames.add(clsArr[i2].getName());
        }
        for (final Class<?> cls : FromStringDeserializer.types()) {
            JdkDeserializers._classNames.add(cls.getName());
        }
    }

    public static JsonDeserializer<?> find(final Class<?> cls, final String str) {
        if (!JdkDeserializers._classNames.contains(str)) {
            return null;
        }
        final FromStringDeserializer<?> fromStringDeserializerFindDeserializer = FromStringDeserializer.findDeserializer(cls);
        if (null != fromStringDeserializerFindDeserializer) {
            return fromStringDeserializerFindDeserializer;
        }
        if (UUID.class == cls) {
            return new UUIDDeserializer();
        }
        if (StackTraceElement.class == cls) {
            return new StackTraceElementDeserializer();
        }
        if (AtomicBoolean.class == cls) {
            return new AtomicBooleanDeserializer();
        }
        if (AtomicInteger.class == cls) {
            return new AtomicIntegerDeserializer();
        }
        if (AtomicLong.class == cls) {
            return new AtomicLongDeserializer();
        }
        if (ByteBuffer.class == cls) {
            return new ByteBufferDeserializer();
        }
        if (Void.class == cls) {
            return NullifyingDeserializer.instance;
        }
        return null;
    }

    public static boolean hasDeserializerFor(final Class<?> cls) {
        return JdkDeserializers._classNames.contains(cls.getName());
    }
}
