name: Build Android app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install SDK platforms
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-36" "build-tools;36.1.0"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - name: Android debug build
        run: ./gradlew clean assembleDebug --stacktrace
